### ISSUE TITLE
bug: cannot list tables from database containing special characters

### ISSUE THREAD

**Issue by nextchamp-saqib** [ibis-project/ibis#10459]
### What happened?

```python
db = ibis.connect("mysql://user:pass@localhost:3306/test-database")
db.list_tables()
# raises: Failed to parse 'test-database' into <class 'sqlglot.expressions.Table'>
```

It seems `quoting` the `database_name` fixes the issue:

```python
In [5]: sqlglot.parse_one('`test-db`', into=sqlglot.exp.Table, dialect="MySQL")
Out[5]: Table(this=Identifier(this=test-db, quoted=True))
```

### What version of ibis are you using?

9.5.0

### What backend(s) are you using, if any?

MySQL

### Relevant log output

```sh
### Traceback

Traceback (most recent call last):
  File "apps/insights/insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.py", line 210, in test_connection
    db.list_tables()/
  File "env/lib/python3.10/site-packages/ibis/backends/mysql/__init__.py", line 339, in list_tables
    table_loc = self._to_sqlglot_table(table_loc)
  File "env/lib/python3.10/site-packages/ibis/backends/sql/__init__.py", line 588, in _to_sqlglot_table
    table = sg.parse_one(database, into=sg.exp.Table, dialect=self.dialect)
  File "env/lib/python3.10/site-packages/sqlglot/__init__.py", line 137, in parse_one
    result = dialect.parse_into(into, sql, **opts)
  File "env/lib/python3.10/site-packages/sqlglot/dialects/dialect.py", line 511, in parse_into
    return self.parser(**opts).parse_into(expression_type, self.tokenize(sql), sql)
  File "env/lib/python3.10/site-packages/sqlglot/parser.py", line 1210, in parse_into
    raise ParseError(
sqlglot.errors.ParseError: Failed to parse 'test-database' into <class 'sqlglot.expressions.Table'>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for the report @nextchamp-saqib !  I can reproduce this.  Not sure how to fix it cleanly -- if you have any control over database naming, your best bet for a workaround right now is to not use hyphens in the name.

**Comment by cpcloud** [comment]
It looks like we're explicitly unquoting the catalog and database for `list_tables` in the MySQL backend.

@gforsyth Any recollection of why we're doing that?

**Comment by cpcloud** [comment]
Oh, right, because of the information_schema querying. Also, this is failing before the unquoting.

**Comment by gforsyth** [comment]
> Oh, right, because of the information_schema querying

I've got to document that inline, at least, because it's a strange thing to do.
