### ISSUE TITLE
bug: read postgres sys tables getting exception

### ISSUE THREAD

**Issue by ruiyang2015** [ibis-project/ibis#10456]
### What happened?

for following snippet to reproduce the issue:
```
import ibis
c = ibis.postgres.connect(...)
t = c.table('pg_class', database='pg_catalog')
```
or
```
t = c.sql('select * from pg_catalog.pg_class')
```
both raise exception like this:
```
  File "/Users/ruiyang/Go/src/github.com/ascend-io/ascend-core/.venv/lib/python3.11/site-packages/ibis/backends/sql/datatypes.py", line 172, in to_ibis
    if method := getattr(cls, f"_from_sqlglot_{typecode.name}", None):
                                               ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'

```
while this works but i would like to get an ibis table express object instead of raw data
```
rows = c.raw_sql('select * from pg_catalog.pg_class').fetchall()
```

### What version of ibis are you using?

9.5.0

### What backend(s) are you using, if any?

Postgres

### Relevant log output

```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ruiyang/Go/src/github.com/ascend-io/ascend-core/.venv/lib/python3.11/site-packages/ibis/backends/sql/__init__.py", line 137, in table
    table_schema = self.get_schema(name, catalog=catalog, database=database)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruiyang/Go/src/github.com/ascend-io/ascend-core/.venv/lib/python3.11/site-packages/ibis/backends/postgres/__init__.py", line 549, in get_schema
    raise com.IbisError(f"Table not found: {name!r}")
ibis.common.exceptions.IbisError: Table not found: 'pg_class'
>>> t = c.table('pg_class', database='pg_catalog')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ruiyang/Go/src/github.com/ascend-io/ascend-core/.venv/lib/python3.11/site-packages/ibis/backends/sql/__init__.py", line 137, in table
    table_schema = self.get_schema(name, catalog=catalog, database=database)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruiyang/Go/src/github.com/ascend-io/ascend-core/.venv/lib/python3.11/site-packages/ibis/backends/postgres/__init__.py", line 552, in get_schema
    {
  File "/Users/ruiyang/Go/src/github.com/ascend-io/ascend-core/.venv/lib/python3.11/site-packages/ibis/backends/postgres/__init__.py", line 553, in <dictcomp>
    col: type_mapper.from_string(typestr, nullable=nullable)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruiyang/Go/src/github.com/ascend-io/ascend-core/.venv/lib/python3.11/site-packages/ibis/backends/sql/datatypes.py", line 475, in from_string
    return super().from_string(text, nullable=nullable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruiyang/Go/src/github.com/ascend-io/ascend-core/.venv/lib/python3.11/site-packages/ibis/backends/sql/datatypes.py", line 204, in from_string
    return cls.to_ibis(sgtype, nullable=nullable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruiyang/Go/src/github.com/ascend-io/ascend-core/.venv/lib/python3.11/site-packages/ibis/backends/sql/datatypes.py", line 172, in to_ibis
    if method := getattr(cls, f"_from_sqlglot_{typecode.name}", None):
                                               ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for reporting @ruiyang2015 -- I thought I'd mapped all the weird postgres internal types but I missed this one.  Looks like the source of the error is the strange `OID` type, that is an unsigned 4-byte integer that is only used internally.  I'll push up a fix.
