### ISSUE TITLE
null timestamp in postgres causes error

### ISSUE THREAD

**Issue by John-Boik** [ibis-project/ibis#1159]
Hello. I have a postgres database in which some timestamp fields contain null values. If I select a block of rows that happen to have all null values for a particular timestamp field, I get the error "data type not understood". For example, suppose the table test has a timestamp column with all nulls. Then 

```
con = ibis.postgres.connect(....)
test = con.table('test')
print(test)
```
will raise the error. It does not seem to matter if the field is a timestamp with or without time zone. 

I am using Ibis version 0.11.2.

Any assistance would be greatly appreciated.

The full error message is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 70, in <module>
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/ibis/expr/types.py", line 59, in __repr__
    result = self.execute()
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/ibis/expr/types.py", line 203, in execute
    return execute(self, limit=limit, async=async)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/ibis/client.py", line 318, in execute
    return backend.execute(expr, limit=limit, async=async)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/ibis/client.py", line 234, in execute
    return self._execute_query(ast.queries[0], async=async)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/ibis/client.py", line 238, in _execute_query
    return klass(self, ddl).execute()
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/ibis/client.py", line 57, in execute
    result = self._fetch(cur)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/ibis/sql/alchemy.py", line 697, in _fetch
    df[column] = df[column].astype(new_dtype)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/pandas/util/_decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/pandas/core/generic.py", line 3410, in astype
    **kwargs)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/pandas/core/internals.py", line 3224, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/pandas/core/internals.py", line 3091, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/pandas/core/internals.py", line 471, in astype
    **kwargs)
  File "/home/johnb/.virtualenvs/ETR/lib/python3.5/site-packages/pandas/core/internals.py", line 493, in _astype
    dtype = np.dtype(dtype)
TypeError: data type not understood
```

**Comment by John-Boik** [comment]
It is a strange and hard to track down problem. Some timestamp columns that are all null work fine, and others throw the error. Not sure what is happening. But, I can say that none of the errors occur if I switch back to release 9c3735d.

**Comment by John-Boik** [comment]
I see this is a [pandas bug](https://github.com/pandas-dev/pandas/issues/12513).
My crude and temporary fix was to alter ~/lib/python3.5/site-packages/pandas/core/internals.py, line ~573 to:
```
        # astype processing
        try:        
            dtype = np.dtype(dtype)
        except:
            # fix??   https://github.com/pandas-dev/pandas/issues/12513          
            if dtype ==  'datetime64[ns, UTC]':          
                dtype = np.arange(2).reshape((1, 2)).astype('datetime64[ns]').dtype
            else:
                assert False
```

**Comment by cpcloud** [comment]
We might be able to work around this. I will look into this for 0.13

**Comment by cpcloud** [comment]
@John-Boik Is this still an issue for you? I'm having trouble reproducing your problem. Here's how I'm going about it:

```sql
postgres=# create table ts_all_nulls (col timestamp);
CREATE TABLE
postgres=# insert into ts_all_nulls values (null), (null), (null);
INSERT 0 3
```

then, in IPython

```
In [12]: import ibis

In [13]: con = ibis.postgres.connect(host='localhost', user='postgres', password='postgres')

In [14]: t = con.table('ts_all_nulls')

In [15]: ibis.options.interactive = False

In [16]: t.execute()
Out[16]: 
  col
0 NaT
1 NaT
2 NaT

In [17]: t.col.execute()
Out[17]: 
0   NaT
1   NaT
2   NaT
Name: col, dtype: datetime64[ns]

In [18]: ibis.options.interactive = True

In [19]: t
Out[19]: 
  col
0 NaT
1 NaT
2 NaT

In [20]: t.col
Out[20]: 
0   NaT
1   NaT
2   NaT
Name: col, dtype: datetime64[ns]
```

That results looks fine to me.

Is there something else I should be doing to trigger the error?

**Comment by cpcloud** [comment]
@John-Boik Closing this for now. If this is still an issue, please reopen with a reproducible example. Is there a specific version of pandas that's causing this issue for you?
