### ISSUE TITLE
Error JSONDecodeError

### ISSUE THREAD

**Issue by elvainch** [ibis-project/ibis#1383]
I have this code

def insert_df_impala(df):
    hdfs = ibis.hdfs_connect(host='hadoophost', port=8020)
    client = ibis.impala.connect(host='impalahost', port=21050, hdfs_client=hdfs,user='myuser', password='mypassword')
    db = client.database('default')
    db.create_table('tablename',df)

and it fails in the last line. If I commented it out the connection works well.

Here is the stacktrace:

`C:\Anaconda3\lib\site-packages\ibis\sql\postgres\compiler.py:187: UserWarning: locale specific date formats (%c, %x, %X) are not yet implemented for Windows
  'for %s' % platform.system()
Traceback (most recent call last):
  File "D:/mstr/ggg/CallApi.py", line 45, in <module>
    insert_df_impala(df)
  File "D:/mstr/ggg/CallApi.py", line 42, in insert_df_impala
    db.create_table('tablename',df)
  File "C:\Anaconda3\lib\site-packages\ibis\impala\client.py", line 54, in create_table
    database=self.name, **kwargs)
  File "C:\Anaconda3\lib\site-packages\ibis\impala\client.py", line 840, in create_table
    writer, to_insert = write_temp_dataframe(self, obj)
  File "C:\Anaconda3\lib\site-packages\ibis\impala\pandas_interop.py", line 224, in write_temp_dataframe
    path = writer.write_temp_csv()
  File "C:\Anaconda3\lib\site-packages\ibis\impala\pandas_interop.py", line 147, in write_temp_csv
    self.write_csv(hdfs_path)
  File "C:\Anaconda3\lib\site-packages\ibis\impala\pandas_interop.py", line 172, in write_csv
    self.hdfs.put(path, f)
  File "C:\Anaconda3\lib\site-packages\ibis\filesystems.py", line 320, in put
    **kwargs)
  File "C:\Anaconda3\lib\site-packages\hdfs\client.py", line 441, in write
    consumer(data)
  File "C:\Anaconda3\lib\site-packages\hdfs\client.py", line 434, in consumer
    url=res.headers['location'],
  File "C:\Anaconda3\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
Exception ignored in: <bound method DataFrameWriter.__del__ of <ibis.impala.pandas_interop.DataFrameWriter object at 0x00000000090F7400>>
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\ibis\impala\pandas_interop.py", line 201, in __del__
    self.cleanup()
  File "C:\Anaconda3\lib\site-packages\ibis\impala\pandas_interop.py", line 207, in cleanup
    self.hdfs.rmdir(path)
  File "C:\Anaconda3\lib\site-packages\ibis\filesystems.py", line 226, in rmdir
    self.client.delete(path, recursive=True)
  File "C:\Anaconda3\lib\site-packages\hdfs\client.py", line 821, in delete
    return self._delete(hdfs_path, recursive=recursive).json()['boolean']
  File "C:\Anaconda3\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

The ibis version is 0.12, impyla 0.14, hdfs 2.0.16,

**Comment by toryhaavik** [comment]
Hi, is this still an issue? If not, I'd like to close it
