### ISSUE TITLE
ImpalaClient.table() returning ValueError: too many values to unpack

### ISSUE THREAD

**Issue by nmcclure** [ibis-project/ibis#1400]
After successfully connecting to an impala database, database.table('tablename') returns ValueError: too many values to unpack. I'm able to create an ImpalaClient.database, and list the tables in it, but any table I try to create with either client.table or database.table return the same value error.

```
>>> import ibis
>>> con = ibis.impala.connect(host=hostName, port=portNumber,
                            auth_mechanism='GSSAPI', use_ssl=True,
                            kerberos_service_name='impala',
                            ca_cert=certPath)

Without an HDFS connection, certain functionality may be disabled

>>> table = con.table('case', database='sfdc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/anaconda3/envs/test/lib/python2.7/site-packages/ibis/client.py", line 119, in table
    schema = self._get_table_schema(qualified_name)
  File "/data/anaconda3/envs/test/lib/python2.7/site-packages/ibis/impala/client.py", line 1188, in _get_table_schema
    return self.get_schema(tname)
  File "/data/anaconda3/envs/test/lib/python2.7/site-packages/ibis/impala/client.py", line 718, in get_schema
    names, types, comments = zip(*tuples)
ValueError: too many values to unpack
```

I'm using Anaconda Python 2.7.14, ibis 0.13, and impyla 0.14.1
Any hints/tips on what could be causing this would be appreciated.

**Comment by cpcloud** [comment]
@nmcclure Can you try this?

```
con = ...
db = con.database('sfdc')
table = db.case
```

If that doesn't work can you try downgrading to `impyla==0.14.0` and see if that resolves the issue?

**Comment by nmcclure** [comment]
Hi @cpcloud, thanks for your response. 
I tried the method you suggested (table = db.TABLENAME), and downgraded impyla to 0.14.0. After each, I tried to create an impalaclient.tableand got the same 'ValueError: too many values to unpack" error.

**Comment by cpcloud** [comment]
Oh sorry I misread the path there. That's actually an issue in ibis, let me have a look

**Comment by cpcloud** [comment]
@nmcclure Can you show the output of `conda list`?

**Comment by nmcclure** [comment]
Hi Phil, sorry about this...I wiped the VM I was trying to get ibis working on and can't get the list of packages anymore. I'll close this issue.

**Comment by ddonetskov** [comment]
I have got the same issue. Could you please help to resolve it?

```
>python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibis
D:\Python36\lib\site-packages\ibis\sql\postgres\compiler.py:236: UserWarning: locale specific date formats (%c, %x, %X) are not yet implemented for Windows
  'for %s' % platform.system()
>>>
>>> client = ibis.impala.connect(host = hostname, port = 21050)
Without an HDFS connection, certain functionality may be disabled
>>> db = client.database()
>>> client.list_databases()
['_impala_builtins', 'default']
>>> db.list_tables()
['ev_nginx', 'my_first_table']
>>> k_ev_nginx = db.ev_nginx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python36\lib\site-packages\ibis\client.py", line 385, in __getattr__
    return self.table(key)
  File "D:\Python36\lib\site-packages\ibis\client.py", line 427, in table
    return self.client.table(qualified_name, self.name)
  File "D:\Python36\lib\site-packages\ibis\client.py", line 119, in table
    schema = self._get_table_schema(qualified_name)
  File "D:\Python36\lib\site-packages\ibis\impala\client.py", line 1188, in _get_table_schema
    return self.get_schema(tname)
  File "D:\Python36\lib\site-packages\ibis\impala\client.py", line 718, in get_schema
    names, types, comments = zip(*tuples)
ValueError: too many values to unpack (expected 3)
>>>
```

**Comment by cpcloud** [comment]
@ddonetskov please show the output of `conda list` as well as the schemas of your tables.

**Comment by ddonetskov** [comment]
@cpcloud, thank you very much for helpin with it!

The table was created in the Impala WebIU with the following command

```
-- create a table in Impala and Kudu with the mapping
create table ev_nginx (
  ts                timestamp not null ,
  http_user_id      bigint,
  http_referrer     string,
  username          string,
  created_at        timestamp,
  created_at_reg    timestamp,
  reg_channel       string,
  inn               bigint,
  url_parsed        string,
  url_path_1        string,
  url_path_2        string,
  url_path_3        string,
  url_path_4        string,
  url_path_5        string,
  url_path_6        string,
  url_path_7        string,
  url_path_8        string,
  url_path_9        string,
  url_params        string,
  url_query         string,
  id                bigint,
  title             string,
  slug              string,
  type_id           bigint,
  type_name         string,
  category_id       bigint,
  category_name     string,
  category_code     string,
  primary key (ts, http_user_id))
  stored as kudu;
```

I don't use 'conda' but 'pip', the list of installed packages is attached.

[pip_freeze.txt](https://github.com/ibis-project/ibis/files/2027525/pip_freeze.txt)
