### ISSUE TITLE
MapD: ~/ibis/ci/ibis-testing-data/functional_alltypes.csv does not exist

### ISSUE THREAD

**Issue by randyzwitch** [ibis-project/ibis#1500]
When following the [conda setup instructions](http://docs.ibis-project.org/developer.html#conda-environment-setup), part 2, running `ci/datamgr.py mapd` gives the following error:

```
(ibis36v2) Randys-MacBook-Pro-2:ibis randyzwitch$ ci/datamgr.py mapd
Traceback (most recent call last):
  File "ci/datamgr.py", line 16, in <module>
    from ibis.compat import Path
ModuleNotFoundError: No module named 'ibis'
(ibis36v2) Randys-MacBook-Pro-2:ibis randyzwitch$ python setup.py develop
running develop
running egg_info
creating ibis_framework.egg-info
writing ibis_framework.egg-info/PKG-INFO
writing dependency_links to ibis_framework.egg-info/dependency_links.txt
writing requirements to ibis_framework.egg-info/requires.txt
writing top-level names to ibis_framework.egg-info/top_level.txt
writing manifest file 'ibis_framework.egg-info/SOURCES.txt'
reading manifest file 'ibis_framework.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*CMakeCache*' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.make' found anywhere in distribution
warning: no previously-included files matching '*.cmake' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.ll' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '#*' found anywhere in distribution
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '*.png' found anywhere in distribution
writing manifest file 'ibis_framework.egg-info/SOURCES.txt'
running build_ext
Creating /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/ibis-framework.egg-link (link to .)
Adding ibis-framework 0.13.0+53.g037db67 to easy-install.pth file

Installed /Users/randyzwitch/ibis
Processing dependencies for ibis-framework==0.13.0+53.g037db67
Searching for python-dateutil>=2.5.0
Reading https://pypi.org/simple/python-dateutil/
Downloading https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl#sha256=1adb80e7a782c12e52ef9a8182bebeb73f1d7e24e374397af06fb4956c8dc5c0
Best match: python-dateutil 2.7.3
Processing python_dateutil-2.7.3-py2.py3-none-any.whl
Installing python_dateutil-2.7.3-py2.py3-none-any.whl to /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages
writing requirements to /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/python_dateutil-2.7.3-py3.6.egg/EGG-INFO/requires.txt
Adding python-dateutil 2.7.3 to easy-install.pth file

Installed /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/python_dateutil-2.7.3-py3.6.egg
Searching for toolz==0.9.0
Best match: toolz 0.9.0
Adding toolz 0.9.0 to easy-install.pth file

Using /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages
Searching for regex==2018.6.9
Best match: regex 2018.6.9
Adding regex 2018.6.9 to easy-install.pth file

Using /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages
Searching for pytz==2018.4
Best match: pytz 2018.4
Adding pytz 2018.4 to easy-install.pth file

Using /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages
Searching for pandas==0.23.1
Best match: pandas 0.23.1
Adding pandas 0.23.1 to easy-install.pth file

Using /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages
Searching for numpy==1.13.1
Best match: numpy 1.13.1
Adding numpy 1.13.1 to easy-install.pth file

Using /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages
Searching for multipledispatch==0.5.0
Best match: multipledispatch 0.5.0
Adding multipledispatch 0.5.0 to easy-install.pth file

Using /Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages
Finished processing dependencies for ibis-framework==0.13.0+53.g037db67
(ibis36v2) Randys-MacBook-Pro-2:ibis randyzwitch$ ci/datamgr.py mapd
Initializing MapD...
[MAPD|WW]Exception: Database ibis_testing already exists.
[MAPD|II] Creating tables ... OK
[MAPD|II] Loading data ...
/Users/randyzwitch/ibis/ci/ibis-testing-data/functional_alltypes.csv
Traceback (most recent call last):
  File "ci/datamgr.py", line 360, in <module>
    cli(auto_envvar_prefix='IBIS_TEST')
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "ci/datamgr.py", line 273, in mapd
    for table, df in read_tables(tables, data_directory):
  File "ci/datamgr.py", line 60, in read_tables
    df = pd.read_csv(str(path), index_col=None, header=0)
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/randyzwitch/miniconda3/envs/ibis36v2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/Users/randyzwitch/ibis/ci/ibis-testing-data/functional_alltypes.csv' does not exist
```

During the setup.py process, those files appear to be getting written to `/tmp/`:

```
Skipping download due to ibis-testing-data.tar.gz already exists.
Extracting archive to /tmp ...
Initializing ClickHouse...
/tmp/ibis-testing-data/functional_alltypes.csv
Initializing PostgreSQL...
```

So it just appears that the MapD python code is looking at the wrong place for the files.

**Comment by randyzwitch** [comment]
Moving the files to the `/Users/randyzwitch/ibis/ci/` allows the build script to work.

Tangent: installing the tables into a custom `ibis_testing` database is valid, but non-canonical, especially given that our Immerse interface (http://localhost:9092/) with auto-login goes to the 'mapd' database. If it's not too late to switch, I'd suggest switching to the `mapd` database, since your build code runs against a Docker container anyway, so there's no risk of overwriting data.

**Comment by xmnlab** [comment]
@randyzwitch 

I think the main propose of these scripts is for CI tasks. these instructions is for developer not for end-user. So I think keep ibis_testing is better because will keep uniformity with other backends.

about the problem you reported. I don't know why this is happening .. in principle all the other backend use the same data. maybe you could try just `ci/datamgr.py download` and figure out if the problem persists.

**Comment by randyzwitch** [comment]
> I think the main propose of these scripts is for CI tasks. these instructions is for developer not for end-user. So I think keep ibis_testing is better because it keeps uniformity with other backends.

That's fair, just wanted to point it out.

> maybe you could try just ci/datamgr.py download and figure out if the problem persists.

The process already works to load the data into other backends, just for MapD it looks like the wrong location. So I think there is just something about the MapD install script that needs a quick change to also look in the `/tmp` directory. Otherwise, the load process works.

**Comment by cpcloud** [comment]
We should get rid of any documentation that suggests development can be easily done without using the docker setup, which means you need to use `./build.sh` to setup services and load data, and `./test.sh` to run tests.

It *is* possible to do run tests with the docker-compose setup, but you can only work on things that run against backends that are either local or can be executed against completely remotely (e.g., BigQuery).

@randyzwitch Do you have any issue with using this workflow?

**Comment by randyzwitch** [comment]
That's perfectly fine with me, I'm just trying to get up to speed.

**Comment by cpcloud** [comment]
@randyzwitch Can this be closed? The [contributing docs](http://docs.ibis-project.org/contributing.html) now reflect the preferred workflow.
