### ISSUE TITLE
AttributeError: 'TSSLSocket' object has no attribute 'isOpen'

### ISSUE THREAD

**Issue by ZebulonPi** [ibis-project/ibis#1813]
Trying to get Ibis set up (after having issues with impyla/sasl/thrift-sasl/Python 3.7... please kill me now), and I'm running into this error:

Traceback (most recent call last):
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 131, in _get_cursor
    cursor = self.connection_pool.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ibis_test.py", line 19, in <module>
    auth_mechanism='LDAP')
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/api.py", line 118, in connect
    client = ImpalaClient(con, hdfs_client=hdfs_client)
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 791, in __init__
    self._ensure_temp_db_exists()
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 1394, in _ensure_temp_db_exists
    if not self.exists_database(name):
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 909, in exists_database
    return bool(self.list_databases(like=name))
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 1004, in list_databases
    with self._execute(statement, results=True) as cur:
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/client.py", line 122, in _execute
    cur = self.con.execute(query)
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 102, in execute
    cursor = self._get_cursor()
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 134, in _get_cursor
    return self._new_cursor()
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 147, in _new_cursor
    con = impyla.connect(database=self.database, **params)
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/impala/dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism, krb_host=krb_host)
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/impala/hiveserver2.py", line 779, in connect
    transport.open()
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 67, in open
    if not self._trans.isOpen():
AttributeError: 'TSSLSocket' object has no attribute 'isOpen'

Had set up a virtual env for the test to make sure I had packages in isolation:

name: ibis_test
channels:
  - conda-forge
  - default
dependencies:
  - pandas
  - pip
  - python==3.6
  - thrift_sasl
  - pip:
    - ibis-framework[impala]
prefix: /anaconda3/envs/ibis_test

Not sure if this is the same issue as the Impyla issue, or something different... please advise!

**Comment by cpcloud** [comment]
@ZebulonPi Can you try with an older version of `thrift_sasl`? Looks like 0.2.1 might be viable given this issue: https://github.com/cloudera/impyla/issues/268

**Comment by ZebulonPi** [comment]
I'll give it a shot and let you know, though thrift-sasl-0.2.1 uses thriftpy, and thriftpy does not support Python 3.7, so we'll be locked into 3.6 until this gets resolved. As its a venv it should be fine (if it works), I'll try ASAP and let you know. Thanks for the quick reply!

**Comment by ZebulonPi** [comment]
Darn it...

Traceback (most recent call last):
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 131, in _get_cursor
    cursor = self.connection_pool.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ibis_test.py", line 19, in <module>
    auth_mechanism='LDAP')
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/api.py", line 118, in connect
    client = ImpalaClient(con, hdfs_client=hdfs_client)
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 791, in __init__
    self._ensure_temp_db_exists()
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 1394, in _ensure_temp_db_exists
    if not self.exists_database(name):
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 909, in exists_database
    return bool(self.list_databases(like=name))
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 1004, in list_databases
    with self._execute(statement, results=True) as cur:
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/client.py", line 122, in _execute
    cur = self.con.execute(query)
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 102, in execute
    cursor = self._get_cursor()
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 134, in _get_cursor
    return self._new_cursor()
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/ibis/impala/client.py", line 147, in _new_cursor
    con = impyla.connect(database=self.database, **params)
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/impala/dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism, krb_host=krb_host)
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/impala/hiveserver2.py", line 779, in connect
    transport.open()
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 75, in open
    self._send_message(self.START, chosen_mech)
  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 94, in _send_message
    self._trans.write(header + body)
TypeError: can't concat bytes to str

**Comment by ZebulonPi** [comment]
A quick pip freeze gives me this, if it helps:

bitarray==0.9.3
certifi==2019.3.9
chardet==3.0.4
docopt==0.6.2
hdfs==2.5.2
ibis-framework==1.0.0
idna==2.8
impyla==0.15.0
multipledispatch==0.6.0
numpy==1.16.4
pandas==0.24.2
ply==3.11
pure-sasl==0.6.1
python-dateutil==2.8.0
pytz==2019.1
regex==2019.6.5
requests==2.22.0
six==1.12.0
SQLAlchemy==1.3.4
thrift==0.11.0
thrift-sasl==0.2.1
thriftpy==0.3.9
thriftpy2==0.4.0
toolz==0.9.0
urllib3==1.25.3

**Comment by cpcloud** [comment]
@ZebulonPi It looks like the `isOpen` issue has been fixed in master, but there hasn't been a release of `thrift_sasl` since that fix was merged. Can you try installing from `thrift_sasl` master using `pip install https://github.com/cloudera/thrift_sasl/archive/master.zip` and see if that resolves the issue? If so, we'll close this issue and we can request that the maintainers of `thrift_sasl` cut a release.

**Comment by ZebulonPi** [comment]
@cpcloud I'll give that a shot, and report back! Thanks!

**Comment by ZebulonPi** [comment]
Making the connection to the lake now (yay!), but running into a different error further downstream.

  File "/Users/jasongreenwood/anaconda3/envs/ibis_test/lib/python3.6/site-packages/impala/hiveserver2.py", line 876, in __init__
    is_null.frombytes(nulls)
TypeError: byte string expected

Interestingly, I ALSO get that error when running impyla in that same venv. This seems to say that they fixed the connection issues in thrift-sasl, but may have introduced something else in there, or its a manifestation of [#338](https://github.com/cloudera/impyla/issues/338)

**Comment by cpcloud** [comment]
Closing per comment above.
