### ISSUE TITLE
CI/BUG: LinuxBuildDocs failing

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2027]
Initially reported at https://github.com/ibis-project/ibis/pull/2024#issuecomment-550143737

```
Traceback (most recent call last):
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 326, in build_update
    len(to_build))
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 339, in build
    updated_docnames = set(self.read())
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 445, in read
    self._read_serial(docnames)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 467, in _read_serial
    self.read_doc(docname)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/io.py", line 323, in read_doc
    pub.publish()
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    super().apply_transforms()
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/docutils/transforms/__init__.py", line 172, in apply_transforms
    transform.apply(**kwargs)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/transforms/__init__.py", line 414, in apply
    self.app.emit('doctree-read', self.document)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/application.py", line 440, in emit
    return self.events.emit(event, self, *args)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sphinx/events.py", line 76, in emit
    results.append(callback(*args))
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/releases/__init__.py", line 612, in generate_changelog
    doctree.walk(changelog_visitor)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/docutils/nodes.py", line 142, in walk
    if child.walk(visitor):
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/docutils/nodes.py", line 142, in walk
    if child.walk(visitor):
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/docutils/nodes.py", line 134, in walk
    visitor.dispatch_visit(self)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/docutils/nodes.py", line 1912, in dispatch_visit
    return method(node)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/releases/__init__.py", line 595, in visit_bullet_list
    releases, _ = construct_releases(node.children, self.app)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/releases/__init__.py", line 502, in construct_releases
    stripped_entries[index + 1:], manager
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/releases/__init__.py", line 429, in handle_upcoming_major_release
    version = Version(obj.number)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/releases/models.py", line 14, in __init__
    super(Version, self).__init__(version_string, partial)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/semantic_version/base.py", line 102, in __init__
    raise ValueError("Call either Version('1.2.3') or Version(major=1, ...).")
ValueError: Call either Version('1.2.3') or Version(major=1, ...).

Exception occurred:
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/semantic_version/base.py", line 102, in __init__
    raise ValueError("Call either Version('1.2.3') or Version(major=1, ...).")
ValueError: Call either Version('1.2.3') or Version(major=1, ...).
The full traceback has been saved in /tmp/sphinx-err-izxs725u.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

##[error]Bash exited with code '2'.
##[section]Finishing: Build docs
```

**Comment by scottcode** [comment]
I'm trying to reproduce this locally (still in docker) but am getting a Timeout error (see [this gist](https://gist.github.com/scottcode/7f3354b6fa4085e986a671964c2d2de5) for the full error output)

`nbsphinx.NotebookError: TimeoutError in notebooks/tutorial/8-More-Analytics-Helpers.ipynb:
Cell execution timed out`

**Comment by scottcode** [comment]
I increased the timeout limit to 60 seconds using the configuration described in the [nbsphinx docs](https://nbsphinx.readthedocs.io/en/0.3.5/timeout.html). It got further, but then I ran into this error `HiveServer2Error: Failed after retrying 3 times` (see [full error](https://gist.github.com/scottcode/9c379c2093354fc18d22e0be3757c5ae)). I'm not sure yet what causes the `HiveServer2Error` or how to get past it.

Given the original error message from the build pipeline about `semantic_version`, I wonder--when I get that far--if the problem will be something like: the `semantic_version` package is being given a versioneer dirty version string and doesn't know how to handle it. Just a hypothesis until I can replicate the error locally.

**Comment by scottcode** [comment]
The `HiveServer2Error` is occurring in `notebooks/tutorial/8-More-Analytics-Helpers.ipynb`

**Comment by scottcode** [comment]
Tracking the local `HiveServer2Error`. Debugging it, I see that the exception it gets each time is below:

```
*** thriftpy2.transport.TTransportException: TTransportException(type=4, message='TSocket read 0 bytes')
```

**Comment by xmnlab** [comment]
@scottcode I am trying to debug that here too. I will post here any update

**Comment by xmnlab** [comment]
issue related: https://github.com/bitprophet/releases/issues/84
