### ISSUE TITLE
bug(PostgreSQL): TopK used as filter is failing

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2132]
TopK used as filter is failing:

```
> SELECT t0.index, t0."Unnamed: 0", t0.id, t0.bool_col, t0.tinyint_col, t0.smallint_col, t0.int_col, t0.bigint_col, t0.float_col, t0.double_col, t0.date_string_col, t0.string_col, t0.timestamp_col, t0.year, t0.month 
FROM functional_alltypes AS t0, (SELECT t0.index AS index, t0."Unnamed: 0" AS "Unnamed: 0", t0.id AS id, t0.bool_col AS bool_col, t0.tinyint_col AS tinyint_col, t0.smallint_col AS smallint_col, t0.int_col AS int_col, t0.bigint_col AS bigint_col, t0.float_col AS float_col, t0.double_col AS double_col, t0.date_string_col AS date_string_col, t0.string_col AS string_col, t0.timestamp_col AS timestamp_col, t0.year AS year, t0.month AS month 
FROM functional_alltypes AS t0 
WHERE EXISTS (SELECT 1 
FROM (SELECT t2.string_col AS string_col, t2.count AS count 
FROM (SELECT t0.string_col AS string_col, count(t0.string_col) AS count 
FROM functional_alltypes AS t0 GROUP BY t0.string_col) AS t2 ORDER BY t2.count DESC 
 LIMIT %(param_1)s) AS t1 
WHERE t0.string_col = t1.string_col))


[EE] Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: subquery in FROM must have an alias
LINE 2: FROM functional_alltypes AS t0, (SELECT t0.index AS index, t...
                                        ^
HINT:  For example, FROM (SELECT ...) [AS] foo.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<ipython-input-8-24e49116336e>", line 16, in <module>
    display(expr.execute())
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/expr/types.py", line 202, in execute
    return execute(self, limit=limit, params=params, **kwargs)
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/client.py", line 352, in execute
    return backend.execute(expr, limit=limit, params=params, **kwargs)
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/client.py", line 215, in execute
    result = self._execute_query(query_ast, **kwargs)
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/client.py", line 220, in _execute_query
    return query.execute()
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/client.py", line 54, in execute
    self.compiled_sql, results=True, **kwargs
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/sql/alchemy.py", line 1212, in _execute
    return AlchemyProxy(self.con.execute(query))
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2182, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/xmn/miniconda3/envs/ibis-nb/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) subquery in FROM must have an alias
LINE 2: FROM functional_alltypes AS t0, (SELECT t0.index AS index, t...
                                        ^
HINT:  For example, FROM (SELECT ...) [AS] foo.

[SQL: SELECT t0.index, t0."Unnamed: 0", t0.id, t0.bool_col, t0.tinyint_col, t0.smallint_col, t0.int_col, t0.bigint_col, t0.float_col, t0.double_col, t0.date_string_col, t0.string_col, t0.timestamp_col, t0.year, t0.month 
FROM functional_alltypes AS t0, (SELECT t0.index AS index, t0."Unnamed: 0" AS "Unnamed: 0", t0.id AS id, t0.bool_col AS bool_col, t0.tinyint_col AS tinyint_col, t0.smallint_col AS smallint_col, t0.int_col AS int_col, t0.bigint_col AS bigint_col, t0.float_col AS float_col, t0.double_col AS double_col, t0.date_string_col AS date_string_col, t0.string_col AS string_col, t0.timestamp_col AS timestamp_col, t0.year AS year, t0.month AS month 
FROM functional_alltypes AS t0 
WHERE EXISTS (SELECT 1 
FROM (SELECT t2.string_col AS string_col, t2.count AS count 
FROM (SELECT t0.string_col AS string_col, count(t0.string_col) AS count 
FROM functional_alltypes AS t0 GROUP BY t0.string_col) AS t2 ORDER BY t2.count DESC 
 LIMIT %(param_1)s) AS t1 
WHERE t0.string_col = t1.string_col))]
[parameters: {'param_1': 3}]
(Background on this error at: http://sqlalche.me/e/f405)

```

The code used is:

```python
alltypes = con.table('functional_alltypes')
alltypes = alltypes.sort_by(alltypes.string_col)
expr = alltypes[alltypes.string_col.topk(3)]
expr.execute()
```

**Comment by cpcloud** [comment]
xref: #3163
