### ISSUE TITLE
feat: add left semi join support to clickhouse

### ISSUE THREAD

**Issue by xmnlab** [ibis-project/ibis#2133]
When TopK is used as filter it uses Semi Left Join. It seems Clickhouse doesn't implement Semi-Lef-Join, so it raises the follow error:

```
[EE] Traceback (most recent call last):
  File "<ipython-input-8-24e49116336e>", line 15, in <module>
    print('>', expr.compile())
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/expr/types.py", line 215, in compile
    return compile(self, limit=limit, params=params)
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/client.py", line 370, in compile
    return backend.compile(expr, limit=limit, params=params, **kwargs)
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/client.py", line 233, in compile
    return query_ast.compile()
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/sql/compiler.py", line 54, in compile
    compiled_queries = [q.compile() for q in self.queries]
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/sql/compiler.py", line 54, in <listcomp>
    compiled_queries = [q.compile() for q in self.queries]
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/sql/compiler.py", line 1567, in compile
    from_frag = self.format_table_set()
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/sql/compiler.py", line 1684, in format_table_set
    fragment += helper.get_result()
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/clickhouse/compiler.py", line 109, in get_result
    self._walk_join_tree(op)
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/sql/compiler.py", line 1795, in _walk_join_tree
    jname = self._get_join_type(op)
  File "/home/xmn/dev/quansight/ibis-project/ibis/ibis/sql/compiler.py", line 1836, in _get_join_type
    return self._join_names[type(op)]
KeyError: <class 'ibis.expr.operations.LeftSemiJoin'>
```

the code used was:

```python

alltypes = con.table('functional_alltypes')
expr = alltypes[alltypes.string_col.topk(3)]
expr.execute()
```

Maybe could be related to #512

**Comment by cpcloud** [comment]
Thanks for reporting this @xmnlab! We need a champion for this, and PRs are definitely welcome.
