### ISSUE TITLE
CI: `feedstock` job is failing

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2397]
Example of failure:
https://github.com/ibis-project/ibis/pull/2395/checks?check_run_id=1133810073
https://github.com/ibis-project/ibis/pull/2395/checks?check_run_id=1131556647

```
...
Executing transaction: ...working... done
Traceback (most recent call last):
  File "/usr/share/miniconda/conda-bld/ibis-framework_1600432670470/test_tmp/run_test.py", line 26, in <module>
    import ibis.backends.omniscidb
ModuleNotFoundError: No module named 'ibis.backends'
Tests failed for ibis-framework-1.3.0+150.g61fd377-py37_6.tar.bz2 - moving package to /usr/share/miniconda/conda-bld/broken
WARNING:conda_build.build:Tests failed for ibis-framework-1.3.0+150.g61fd377-py37_6.tar.bz2 - moving package to /usr/share/miniconda/conda-bld/broken
WARNING conda_build.build:tests_failed(2904): Tests failed for ibis-framework-1.3.0+150.g61fd377-py37_6.tar.bz2 - moving package to /usr/share/miniconda/conda-bld/broken
export PREFIX=/usr/share/miniconda/conda-bld/ibis-framework_1600432670470/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
export SRC_DIR=/usr/share/miniconda/conda-bld/ibis-framework_1600432670470/test_tmp
import: 'ibis'
import: 'ibis.bigquery'
import: 'ibis.clickhouse'
import: 'ibis.file.csv'
TESTS FAILED: ibis-framework-1.3.0+150.g61fd377-py37_6.tar.bz2
import: 'ibis.file.parquet'
import: 'ibis.file.hdf5'
import: 'ibis.impala'
import: 'ibis.sql.mysql'
import: 'ibis.backends.omniscidb'
Traceback (most recent call last):
  File "./ci/feedstock.py", line 146, in <module>
    cli()
  File "/usr/share/miniconda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/share/miniconda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/share/miniconda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/share/miniconda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/share/miniconda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./ci/feedstock.py", line 107, in build
    stderr=click.get_binary_stream('stderr'),
  File "/usr/share/miniconda/lib/python3.7/site-packages/plumbum/commands/base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/share/miniconda/lib/python3.7/site-packages/plumbum/commands/base.py", line 232, in run
    return p.run()
  File "/usr/share/miniconda/lib/python3.7/site-packages/plumbum/commands/base.py", line 193, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/share/miniconda/lib/python3.7/site-packages/plumbum/commands/processes.py", line 302, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/share/miniconda/lib/python3.7/site-packages/plumbum/commands/processes.py", line 22, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/share/miniconda/lib/python3.7/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /usr/share/miniconda/bin/conda build --channel conda-forge --python 3.7 /tmp/ibis-framework-feedstock/recipe

```

**Comment by timothydijamco** [comment]
This looks related to https://github.com/ibis-project/ibis/pull/2392, however, the CI was working fine after this was merged and only started failing a few hours later

**Comment by datapythonista** [comment]
Thanks for reporting @timothydijamco, not so familiar with that build, not sure what's the problem. But having a look now.
