### ISSUE TITLE
Pandas: case() statement when() does not match null values

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#2516]
The `when()` function in a case statement does not match `NULL` values (at least not in the Pandas backend).

```python
import ibis
import pandas


pd_source = pandas.DataFrame({"count": ["hello", None, "world"]})
client = ibis.pandas.connect({"source": pd_source})
source = client.table("source")

# https://ibis-project.org/docs/generated/ibis.ifelse.html#ibis.ifelse
string_col = source["count"].cast("string")
expr = source[
    string_col.case()
    .when(ibis.NA, ibis.literal("null"))
    .else_(ibis.literal('"') + string_col + ibis.literal('"'))
    .end()
    .name("json")
]
print(expr.execute()
```

Output:

```
$ python trynull.py
      json
0  "hello"
1      NaN
2  "world"
```

But I would expect

```
$ python trynull.py
      json
0  "hello"
1      null
2  "world"
```

**Comment by tswast** [comment]
This is more of a problem when trying to apply functions like `re_replace`, which do not handle `NULL` values as well as string concatenation. Replacing the `else_(...)` above with `.else_(string_col.re_replace(r"\\", r"\\\\"))` raises the following exception:

```
Traceback (most recent call last):
  File "2020/data-validator-pr130-null-json/trynull.py", line 19, in <module>
    print(expr.execute())
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/expr/types.py", line 202, in execute
    return execute(self, limit=limit, params=params, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/client.py", line 352, in execute
    return backend.execute(expr, limit=limit, params=params, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/client.py", line 372, in execute
    return execute_and_reset(query, params=params, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 375, in execute_and_reset
    expr, params=params, scope=scope, aggcontext=aggcontext, **kwargs
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 332, in main_execute
    return execute_with_scope(expr, new_scope, aggcontext=aggcontext, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 190, in execute_with_scope
    **kwargs,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 280, in execute_until_in_scope
    **kwargs,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/execution/selection.py", line 291, in execute_selection_dataframe
    selection, op, data, scope=scope, **kwargs
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/execution/selection.py", line 115, in compute_projection_column_expr
    result = execute(expr, scope=new_scope, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 332, in main_execute
    return execute_with_scope(expr, new_scope, aggcontext=aggcontext, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 190, in execute_with_scope
    **kwargs,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 255, in execute_until_in_scope
    for arg in computable_args
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 255, in <listcomp>
    for arg in computable_args
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 255, in execute_until_in_scope
    for arg in computable_args
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 255, in <listcomp>
    for arg in computable_args
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 280, in execute_until_in_scope
    **kwargs,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/execution/generic.py", line 795, in execute_node_value_list
    return [execute(arg, **kwargs) for arg in op.values]
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/execution/generic.py", line 795, in <listcomp>
    return [execute(arg, **kwargs) for arg in op.values]
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 332, in main_execute
    return execute_with_scope(expr, new_scope, aggcontext=aggcontext, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 190, in execute_with_scope
    **kwargs,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 255, in execute_until_in_scope
    for arg in computable_args
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 255, in <listcomp>
    for arg in computable_args
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 280, in execute_until_in_scope
    **kwargs,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/execution/generic.py", line 795, in execute_node_value_list
    return [execute(arg, **kwargs) for arg in op.values]
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/execution/generic.py", line 795, in <listcomp>
    return [execute(arg, **kwargs) for arg in op.values]
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 332, in main_execute
    return execute_with_scope(expr, new_scope, aggcontext=aggcontext, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 190, in execute_with_scope
    **kwargs,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/core.py", line 280, in execute_until_in_scope
    **kwargs,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/execution/strings.py", line 287, in execute_series_regex_replace
    return data.apply(replacer)
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/pandas/core/series.py", line 3848, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/ibis/pandas/execution/strings.py", line 285, in replacer
    return pattern.sub(replacement, x)
TypeError: expected string or buffer
```

**Comment by tswast** [comment]
The same behavior is observed if I use `ibis.null()` or `None` instead of `ibis.NA`.

`float("nan")` fails with `TypeError: Base expression and passed case are not comparable`, which probably makes sense.

**Comment by cpcloud** [comment]
This might be possible to address, depending on:

1) whether there's consistent treatment of `NULL` in a `CASE WHEN`, since AIUI the `switch` style case requires the ability to compare two values for equality.
2) whether pandas can be made to do this.

**Comment by cpcloud** [comment]
Closing for now. PRs welcome.
