### ISSUE TITLE
CI: Docs build failing

### ISSUE THREAD

**Issue by timothydijamco** [ibis-project/ibis#2771]
In #2770, the docs build began failing. The version of Sphinx when succeeding was `3.5.4`, but changed to `4.0.0` in the failing CI run.

```
Run sphinx-build -b html docs/source /tmp/ibis-project.org/docs -W -T
Running Sphinx v4.0.0
making output directory... done

Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/share/miniconda/lib/python3.8/site-packages/sphinx/application.py", line 267, in __init__
    self.events.emit('config-inited', self.config)
  File "/usr/share/miniconda/lib/python3.8/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/share/miniconda/lib/python3.8/site-packages/sphinx/config.py", line 447, in check_confval_types
    logger.warning(msg.format(name=confval.name,
  File "/usr/share/miniconda/lib/python3.8/logging/__init__.py", line 1808, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/usr/share/miniconda/lib/python3.8/site-packages/sphinx/util/logging.py", line 123, in log
    super().log(level, msg, *args, **kwargs)
  File "/usr/share/miniconda/lib/python3.8/logging/__init__.py", line 1840, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/share/miniconda/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/share/miniconda/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/share/miniconda/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/share/miniconda/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/share/miniconda/lib/python3.8/logging/__init__.py", line 946, in handle
    rv = self.filter(record)
  File "/usr/share/miniconda/lib/python3.8/logging/__init__.py", line 807, in filter
    result = f.filter(record)
  File "/usr/share/miniconda/lib/python3.8/site-packages/sphinx/util/logging.py", line 423, in filter
    raise exc
sphinx.errors.SphinxWarning: The config value `autosummary_generate' has type `list'; expected `bool'.

Warning, treated as error:
The config value `autosummary_generate' has type `list'; expected `bool'.
Error: Process completed with exit code 2.
```
from https://github.com/ibis-project/ibis/runs/2547543488

**Comment by timothydijamco** [comment]
Will take a look to see if it's a quick change on our end for compatibility, otherwise I will pin `sphinx` to a lower version for now

**Comment by rajpratyush** [comment]
is this issue open for work??
@timothydijamco

**Comment by datapythonista** [comment]
> is this issue open for work??
> @timothydijamco

Technically this is the same as #2783. If you update to the latest Sphinx, this is the error you'll face.
