### ISSUE TITLE
CI: Require new Impyla version once issue with bitarray 2.1.0 is fixed

### ISSUE THREAD

**Issue by emilyreff7** [ibis-project/ibis#2780]
Recent CIs have picked up bitarray version 2.1.0 and started failing in Impala / Clickhouse 3.7 pipeline with 
```
Traceback (most recent call last):
  File "ci/impalamgr.py", line 15, in <module>
    from ibis.backends.impala.tests.conftest import IbisTestEnv
  File "/home/runner/work/ibis/ibis/ibis/backends/impala/__init__.py", line 6, in <module>
    from .client import (  # noqa: F401
  File "/home/runner/work/ibis/ibis/ibis/backends/impala/client.py", line 43, in <module>
    from .compat import HS2Error, ImpylaError, impyla
  File "/home/runner/work/ibis/ibis/ibis/backends/impala/compat.py", line 15, in <module>
    import impala.dbapi as impyla  # noqa
  File "/usr/share/miniconda/site-packages/impala/dbapi.py", line 28, in <module>
    import impala.hiveserver2 as hs2
  File "/usr/share/miniconda/site-packages/impala/hiveserver2.py", line 26, in <module>
    from bitarray import bitarray
  File "/usr/share/miniconda/site-packages/bitarray/__init__.py", line 14, in <module>
    from bitarray._bitarray import (bitarray, decodetree, _sysinfo,
ModuleNotFoundError: No module named 'bitarray._bitarray'
```

The following PR was merged as a temporary fix: https://github.com/ibis-project/ibis/pull/2781

An issue was opened on the Impyla side to investigate: https://github.com/cloudera/impyla/issues/450

Once this is fixed on their end, we should unpin bitarray and require the new Impyla, requiring bitarray to be whatever compatible version is included in the impyla fix.

**Comment by cpcloud** [comment]
We're no longer pinning bitarray, so this is fixed.
