### ISSUE TITLE
[UDF] Error when trying to add UDF support to MySQL

### ISSUE THREAD

**Issue by kesmit13** [ibis-project/ibis#3050]
I'm trying to add UDF support to a MySQL-like database. I'm using the Impala UDFs as a prototype, but it's not quite working. I get an exception in trying to format the SQL of the UDF expression. I'm passing a `Column` to a UDF named `square` which takes an `int64` and returns an `int64`. It looks like the code in `backends/base/sql/registry/helpers.py:format_call` is expecting a string in `format_args`, but the `translator.translate` function is returning a `Column`. Here is the example code:

```
import ibis
import ibis.expr.operations as ops
import ibis.expr.datatypes as dt
import ibis.expr.rules as rlz
import ibis.expr.signature as sig
from ibis.backends.base.sql.registry import fixed_arity
from ibis.backends.mysql.compiler import MySQLExprTranslator

def _create_operation_class(name, input_type, output_type):
    func_dict = {'signature': input_type, 'output_type': output_type}
    klass = type(name, (ops.ValueOp,), func_dict)
    return klass

def add_operation(op, func_name, db):
    full_name = f'{db}.{func_name}'
    arity = len(op.signature)
    translator = fixed_arity(full_name, arity)
    MySQLExprTranslator._registry[op] = translator

def _type_signature(inputs, output):
    input_type = _ibis_signature(inputs)
    output_type = rlz.shape_like('args', dt.dtype(output))
    return input_type, output_type

def _ibis_signature(inputs):
    if isinstance(inputs, sig.TypeSignature):
        return inputs
    arguments = [
        (f'_{i}', sig.Argument(rlz.value(dtype)))
        for i, dtype in enumerate(inputs)
    ]
    return sig.TypeSignature(arguments)

def create_function(name, inputs, outputs, database):
    op = _create_operation_class(name, *_type_signature(tuple([dt.dtype(x) for x in inputs]), dt.dtype(outputs)))
    add_operation(op, name, database)
    def to_expr(*args):
        return op(*args).to_expr()
    return to_expr

square = create_function("square", ['int64'], 'int64', 'x_db')
conn = ibis.mysql.connect(host='localhost', database='x_db')
phones = conn.table('phones')
print(square(phones.index).execute())
```

The exception I get is:
```
Traceback (most recent call last):
  File "/Users/me/src/Notebooks/func.py", line 46, in <module>
    print(square(phones.index).execute())
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/expr/types.py", line 273, in execute
    return self._find_backend().execute(
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/__init__.py", line 122, in execute
    sql = query_ast.compile()
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/compiler/base.py", line 41, in compile
    compiled_queries = [q.compile() for q in self.queries]
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/compiler/base.py", line 41, in <listcomp>
    compiled_queries = [q.compile() for q in self.queries]
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/alchemy/query_builder.py", line 160, in compile
    frag = step(frag)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/alchemy/query_builder.py", line 192, in _add_select
    arg = self._translate(expr, named=True)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/compiler/query_builder.py", line 237, in _translate
    return translator.get_result()
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/compiler/translator.py", line 223, in get_result
    translated = self.translate(self.expr)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/compiler/translator.py", line 278, in translate
    return formatter(self, expr)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/registry/main.py", line 16, in formatter
    return helpers.format_call(translator, func_name, *op.args)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/registry/helpers.py", line 15, in format_call
    return '{}({})'.format(func, ', '.join(formatted_args))
TypeError: sequence item 0: expected str instance, Column found
```

**Comment by kesmit13** [comment]
@cpcloud I'm looking at this issue again, but I'm still not quite sure about everything that's going on to make a fix. For this particular error, it appears as though you could just change the offending line to the following:
```
    return '{}({})'.format(func, ', '.join([str(x) for x in formatted_args]))
```

This gets the string representation of the `Column` objects in `formatted_args` and the code continues to run. However, that only gets me down the road a bit further. Once the function is created and registered, it still doesn't execute properly. I'm modeling my code after the Impala UDF implementation, so my test case looks like this:
```
library = 'multivalue.wasm'
inputs = ['int64', 'int64']
output = 'int64'
symbol = 'opt_plus'
udf_db = 'x_db'

opt_plus = wrap_udf(library, inputs, output, symbol)
con.create_function(opt_plus, database=udf_db)
opt_plus.register(opt_plus.name, udf_db)
countries = con.table('countries')

print(opt_plus(countries.iso_numeric, countries.population).execute())
```

In the `execute()` call, I run into another error.
```
Traceback (most recent call last):
  File "/Users/ksmith/src/ibis-test/ibis-singlestore.py", line 22, in <module>
    print(opt_plus(countries.iso_numeric, countries.population).execute())
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/expr/types.py", line 273, in execute
    return self._find_backend().execute(
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/__init__.py", line 122, in execute
    sql = query_ast.compile()
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/compiler/base.py", line 41, in compile
    compiled_queries = [q.compile() for q in self.queries]
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/compiler/base.py", line 41, in <listcomp>
    compiled_queries = [q.compile() for q in self.queries]
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/alchemy/query_builder.py", line 160, in compile
    frag = step(frag)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/ibis/backends/base/sql/alchemy/query_builder.py", line 220, in _add_select
    result = sa.select(clauses)
  File "<string>", line 2, in select
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 4893, in _create
    return cls.create_legacy_select(*args, **kw)
  File "<string>", line 2, in create_legacy_select
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 4771, in create_legacy_select
    self._raw_columns = [
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 4772, in <listcomp>
    coercions.expect(
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 175, in expect
    resolved = impl._literal_coercion(
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 375, in _literal_coercion
    return self._text_coercion(element, argname, **kw)
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 808, in _text_coercion
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Textual column expression 'x_db.opt_plus(t0.iso_nume...' should be explicitly declared with text('x_db.opt_plus(t0.iso_nume...'), or use literal_column('x_db.opt_plus(t0.iso_nume...') for more specificity
```

The syntax generated for the function appears to be correct, but it's getting down into some SQLAlchemy code that seems to think that it is a literal. I'm just not familiar enough with the codebase to discern how it's getting there or what the solution might be.

**Comment by kesmit13** [comment]
Here's where I'm at now, but I'm still wondering if I'm just going about this the wrong way. When I debug into the `execute()` call, I eventually get to `AlchemySelect._add_select` which calls `translate` on the expression which calls a formatter and returns a string `x_db.opt_plus(t0.iso_numeric, t0.population)` which so far seems correct. However, that string is added to the select clauses that get sent to `sa.select(clauses)`. When this happens, SQLAlchemy thinks the string is a text literal rather than a function call that returns a value. I just have a gut feeling that I'm on the wrong path, but I don't know what the right path might be.

**Comment by kesmit13** [comment]
Here is one thing that I've attempted which does get me down the road a ways. The `_translate` method for the MySQL backend will return a string that contains the UDF syntax: `db.func(x, y, ...)`. I added the following code to convert the string to a text literal including an `AS` clause to assign a name to it. This does work in column selections (e.g., `tbl[['column', expr]]`, but it fails when using the expression in other contexts such as filtering: `tbl[expr]`. In this context, it appears as though the expression needs to be a `TableExpr` object. So it feels like converting the output of `_translate` to some other object might be the right way to go, I'm just not sure what it should be. Using a text literal doesn't seem right. It's like it needs to be a pseudo-column expression. If anyone has any tips, I'd love to hear them.

```
  190 ⋮194 │        for expr in self.select_set:
  191 ⋮195 │            if isinstance(expr, ir.ValueExpr):
  192 ⋮196 │                arg = self._translate(expr, named=True)
+     ⋮197 │                if isinstance(arg, (str, bytes)):
+     ⋮198 │                    if expr.get_name():
+     ⋮199 │                        arg = '{} AS {}'.format(parenthesize(arg),
+     ⋮200 │                                                quote_identifier(expr.get_name()))
+     ⋮201 │                    arg = sa.text(arg)
  193 ⋮202 │            elif isinstance(expr, ir.TableExpr):
  194 ⋮203 │                if expr.equals(self.table_set):
  195 ⋮204 │                    cached_table = self.context.get_table(expr)
```

**Comment by kesmit13** [comment]
It turns out my primary issue was this line:
```
from ibis.backends.base.sql.registry import fixed_arity
```
I changed it to this and that solved most of the problems:
```
from ibis.backends.base.alchemy import fixed_arity
```

I do still have an issue with applying multiple operations though. I have a UDF to compute greatest common divisor and set up an expression as follows:
```
gcd_expr = con.funcs.gcd(countries.population, countries.iso_numeric).name('gcd')
```
This works fine with a single operation:
```
>>> countries[['name', gcd_expr]]
SELECT t0.name, x_db.gcd(t0.population, t0.iso_numeric) AS gcd 
FROM countries AS t0 
```
However, if I try to do multiple operations, it creates table joins rather than applying the next operation to the existing result. It appears as though the table name is not getting remapped in the subsequent operations. I'm going to close this issues for now though and open a different one down the road if needed.

**Comment by cpcloud** [comment]
> However, if I try to do multiple operations, it creates table joins rather than applying the next operation to the existing result.

This *might* be the same issue as #3163
