### ISSUE TITLE
Error when trying to join tables with Pandas backend

### ISSUE THREAD

**Issue by tengznaim** [ibis-project/ibis#3082]
Hello, I'm trying to perform an outer join on two tables with the Pandas backend and am unable to do so due to a signature error. Here is an example code of what I'm trying to do:

```
import ibis
import pandas as pd
from ibis.backends.pandas import udf
from ibis.expr.api import NumericValue
import ibis.expr.datatypes as dt

df = pd.DataFrame({"test": [1, 2, 3], "name": ["a", "b", "c"]})
df_2 = pd.DataFrame({"test_2": [1, 5, 6], "name_2": ["d", "e", "f"]})

conn = ibis.pandas.connect({"df": df, "df_2": df_2})

ibis_table_1 = conn.table("df")
ibis_table_2 = conn.table("df_2")

joined = ibis_table_1.outer_join(
    ibis_table_2, predicates=ibis_table_1["test"] == ibis_table_2["test_2"])
joined = joined.materialize()
result = joined.execute()
print(result)
```

The error I get from the above is:

```
Traceback (most recent call last):
  File "pandas_test.py", line 22, in <module>
    result = joined.execute()
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\expr\types.py", line 273, in execute
    return self._find_backend().execute(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\__init__.py", line 121, in execute
    return execute_and_reset(query, params=params, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 487, in execute_and_reset
    result = execute(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\multipledispatch\dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\trace.py", line 138, in traced_func
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 432, in main_execute
    return execute_with_scope(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 218, in execute_with_scope
    result = execute_until_in_scope(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\trace.py", line 138, in traced_func
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 359, in execute_until_in_scope
    result = execute_node(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\multipledispatch\dispatcher.py", line 273, in __call__
    raise NotImplementedError(
NotImplementedError: Could not find signature for execute_node: <MaterializedJoin, DataFrame>
```

I've tried this on both Ibis 1.4.0 and 2.0.0 and face the same error using both. However, I do notice that it seems like joins have already been implemented for the Pandas backend so is this a mistake of implementation on my end and/or is there a workaround? Many thanks in advance for any help!

**Comment by cpcloud** [comment]
This is an honest-to-goodness bug. Thanks for the report @tengznaim! I'll have a PR up shortly to fix this.
