### ISSUE TITLE
bug: error in mutating joined tables using Pandas backend

### ISSUE THREAD

**Issue by tengznaim** [ibis-project/ibis#3090]
Hey again, thanks for the super quick help on the previous issue, #3082 . I think I may have found an additional bug as a follow up to that fix in that mutating the newly joined table doesn't seem to work. Here's an example code:

```
import ibis
import pandas as pd

df = pd.DataFrame(
    {"p_Order_Priority": ["C", "H", "L", "M"], "p_count": [9, 9, 15, 11], "p_density": [0.204545, 0.204545, 0.340909, 0.250000]})
df_2 = pd.DataFrame(
    {"q_Order_Priority": ["C", "H", "L", "M"], "q_count": [13, 21, 12, 10], "q_density": [0.232143, 0.375000, 0.214286, 0.178571]})

conn = ibis.pandas.connect({"df": df, "df_2": df_2})

ibis_table_1 = conn.table("df")
ibis_table_2 = conn.table("df_2")

joined = ibis_table_1.outer_join(
    ibis_table_2, predicates=ibis_table_1["p_Order_Priority"] == ibis_table_2["q_Order_Priority"])
joined = joined.materialize()

joined = joined.mutate(
    bins=joined["p_Order_Priority"].isnull().ifelse(
        joined["q_Order_Priority"], joined["p_Order_Priority"]),
    p_count=joined["p_count"].fillna(0),
    q_count=joined["q_count"].fillna(0),
    p_density=joined.p_density.fillna(1e-10),
    q_density=joined.q_density.fillna(1e-10),
    features="Order_Priority"
)

print(joined.execute())
```

The above results in the following error:
```
Traceback (most recent call last):
  File "C:\Users\tanaimn\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc    
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'p_count'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bug_test.py", line 28, in <module>
    print(joined.execute())
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\expr\types.py", line 273, in execute
    return self._find_backend().execute(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\__init__.py", line 121, in execute      
    return execute_and_reset(query, params=params, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 487, in execute_and_reset
    result = execute(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\multipledispatch\dispatcher.py", line 278, in __call__       
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\trace.py", line 138, in traced_func     
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 432, in main_execute
    return execute_with_scope(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 218, in execute_with_scope
    result = execute_until_in_scope(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\trace.py", line 138, in traced_func
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 359, in execute_until_in_scope
    result = execute_node(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\multipledispatch\dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\trace.py", line 138, in traced_func
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\execution\selection.py", line 328, in execute_selection_dataframe        
    pandas_object = compute_projection(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\multipledispatch\dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\execution\selection.py", line 144, in compute_projection_column_expr     
    execute(expr, scope=scope, timecontext=timecontext, **kwargs),
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\multipledispatch\dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\trace.py", line 138, in traced_func
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 432, in main_execute
    return execute_with_scope(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 218, in execute_with_scope
    result = execute_until_in_scope(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\trace.py", line 138, in traced_func
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 327, in execute_until_in_scope
    scopes = [
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 328, in <listcomp>
    execute_until_in_scope(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\trace.py", line 138, in traced_func
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\core.py", line 359, in execute_until_in_scope
    result = execute_node(
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\multipledispatch\dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\trace.py", line 138, in traced_func
    return func(*args, **kwargs)
  File "C:\Users\tanaimn\.conda\envs\ibis_test\lib\site-packages\ibis\backends\pandas\execution\generic.py", line 389, in execute_table_column_df_or_df_groupby    return data[op.name]
  File "C:\Users\tanaimn\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\tanaimn\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'p_count'
```

One workaround I found which solved this problem was to add an empty mutate after materializing the joined table, eg.

```
joined = joined.materialize().mutate()
```

but I do imagine that this wouldn't be the intended functionality. Thanks again for any help!

**Comment by cpcloud** [comment]
@tengznaim One workaround here is to change

```python
joined = joined.materialize()
```

to

```python
joined = joined[ibis_table_1, ibis_table_2]
```

`.materialize()` is supposed to have this behavior already, so it's a bug that it doesn't work that way.

On the other hand, we are trying to remove the `materialize()` API altogether because it's confusing, error prone, and doesn't really work like anyone expects it to.
