### ISSUE TITLE
"IndexError: pop from an empty deque" when connecting to hive 

### ISSUE THREAD

**Issue by jxfruit** [ibis-project/ibis#3094]
This issue has been solved? I still got the error:
`Traceback (most recent call last):
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/impala/client.py", line 129, in _get_cursor
    cursor = self.connection_pool.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/impala/api.py", line 121, in connect
    client = ImpalaClient(con, hdfs_client=hdfs_client)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/impala/client.py", line 789, in __init__
    self._ensure_temp_db_exists()
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/impala/client.py", line 1392, in _ensure_temp_db_exists
    if not self.exists_database(name):
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/impala/client.py", line 907, in exists_database
    return bool(self.list_databases(like=name))
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/impala/client.py", line 1002, in list_databases
    with self._execute(statement, results=True) as cur:
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/client.py", line 150, in _execute
    cur = self.con.execute(query)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/impala/client.py", line 100, in execute
    cursor = self._get_cursor()
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/impala/client.py", line 132, in _get_cursor
    return self._new_cursor()
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/impala/client.py", line 150, in _new_cursor
    cursor = con.cursor(user=params.get('user'), convert_types=True)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/impala/hiveserver2.py", line 124, in cursor
    session = self.service.open_session(user, configuration)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/impala/hiveserver2.py", line 1075, in open_session
    resp = self._rpc('OpenSession', req)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/impala/hiveserver2.py", line 993, in _rpc
    response = self._execute(func_name, request)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/impala/hiveserver2.py", line 1010, in _execute
    return func(request)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/thriftpy2/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/thriftpy2/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/thriftpy2/protocol/binary.py", line 372, in read_message_begin
    self.trans, strict=self.strict_read)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/thriftpy2/protocol/binary.py", line 178, in read_message_begin
    message='No protocol version header')
thriftpy2.protocol.exc.TProtocolException: TProtocolException(type=4)`
the dependencies:
`absl-py                   0.15.0
aiworks-plugins           4.3.1
APScheduler               3.8.1
astor                     0.8.1
backports.zoneinfo        0.2.1
bcrypt                    3.2.0
bitarray                  2.3.4
Bottleneck                1.3.2
brotlipy                  0.7.0
cached-property           1.5.2
certifi                   2021.10.8
cffi                      1.15.0
charset-normalizer        2.0.7
click                     8.0.3
cloudpickle               2.0.0
configparser              5.0.2
cryptography              35.0.0
dill                      0.3.4
docopt                    0.6.2
fastavro                  1.4.3
Flask                     2.0.2
Flask-APScheduler         1.12.2
Flask-Cors                3.0.10
Flask-SQLAlchemy          2.5.1
future                    0.18.2
gast                      0.2.2
google-pasta              0.2.0
graphviz                  0.16
greenlet                  1.1.2
grpcio                    1.41.0
h5py                      2.10.0
hdfs                      2.6.0
hyperopt                  0.2.5
ibis-framework            1.3.0
idna                      3.3
importlib-metadata        4.8.1
impyla                    0.16.3
itsdangerous              2.0.1
jieba                     0.42.1
Jinja2                    3.0.2
joblib                    1.1.0
kazoo                     2.8.0
Keras-Applications        1.0.8
Keras-Preprocessing       1.1.2
kerberos                  1.3.1
lz4                       3.1.3
Markdown                  3.3.4
MarkupSafe                2.0.1
mkl-fft                   1.3.1
mkl-random                1.2.2
mkl-service               2.4.0
mock                      4.0.3
multipledispatch          0.6.0
networkx                  2.6.3
numexpr                   2.7.3
numpy                     1.21.3
onnx                      1.10.1
opt-einsum                3.3.0
pandas                    1.3.4
paramiko                  2.8.0
parsy                     1.3.0
patsy                     0.5.2
Pillow                    8.4.0
pip                       21.2.2
ply                       3.11
protobuf                  3.19.0
psutil                    5.8.0
psycopg2                  2.8.6
pure-sasl                 0.6.2
py4j                      0.10.9.2
pyarrow                   3.0.0
pycparser                 2.20
PyHDFS                    0.3.1
PyHive                    0.6.4
pykerberos                1.2.1
PyMySQL                   1.0.2
PyNaCl                    1.4.0
pyOpenSSL                 20.0.1
PySocks                   1.7.1
pyspark                   3.2.0
python-dateutil           2.8.2
pytz                      2021.3
pytz-deprecation-shim     0.1.0.post0
PyYAML                    6.0
regex                     2021.10.23
requests                  2.26.0
requests-kerberos         0.12.0
sasl                      0.2.1
scikit-learn              1.0.1
scipy                     1.7.1
setuptools                58.0.4
simple-tensorflow-serving 0.8.2
simplejson                3.17.5
six                       1.16.0
sklearn                   0.0
SQLAlchemy                1.4.22
statsmodels               0.13.0
tables                    3.6.1
tensorboard               1.15.0
tensorflow                1.15.5
tensorflow-estimator      1.15.1
termcolor                 1.1.0
threadpoolctl             3.0.0
thrift                    0.15.0
thrift-sasl               0.2.1
thriftpy                  0.3.9
thriftpy2                 0.4.0
toolz                     0.11.1
torch                     1.8.1
tqdm                      4.62.3
typing-extensions         3.10.0.2
tzdata                    2021.5
tzlocal                   4.0.1
urllib3                   1.26.7
uWSGI                     2.0.20
Werkzeug                  2.0.2
wheel                     0.37.0
wrapt                     1.13.2
xgboost                   1.5.0
zipp                      3.6.0`
python version: 3.7.11 with anaconda
And I have tried ibis-1.3.0 and 2.0 version. Can u guys give some advices? tks a lot

**Comment by cpcloud** [comment]
Hive isn't a supported backend.
