### ISSUE TITLE
bug: Cannot subclass `_dt.Interval`

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#3735]
Not sure if this is intentional or we are doing something weird. The following works:

```python
_dt.Interval(unit="Y", value_type=_dt.int64)
```

This does not work but used to:

```python
import ibis.expr.datatypes as _dt
import ibis.expr.types as _ir

class SomeClass(_dt.Interval):
    def __init__(
        self,
        unit,
        value_type,
    ):
        """Create a temporal delta."""
        super().__init__(unit=unit, value_type=value_type)

blah = SomeClass(unit="Y", value_type = _dt.int64)
```

This raises a `ValueError`:

```python
Traceback (most recent call last):
  File "/home/gmanoim/tmp/tmp.py", line 28, in <module>
    blah = TemporalDelta(unit="Y", value_type = _dt.int64)
  File "...ibis/common/grounds.py", line 21, in __call__
    return cls.__create__(*args, **kwargs)
  File "...ibis/common/grounds.py", line 152, in __create__
    return super().__create__(**kwargs)
  File "...ibis/common/grounds.py", line 30, in __create__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'nullable'
```

If I throw a breakpoint there I see

```
-> return type.__call__(cls, *args, **kwargs)
(Pdb) cls
<class 'ibis.expr.datatypes.core.Int32'>
(Pdb) kwargs
{'nullable': True}
```

**Comment by cpcloud** [comment]
@gerrymanoim `DataType` is now a subclass of `Annotable`, so arguments are declared the same way as they are when defining operations. Does that help?

**Comment by cpcloud** [comment]
Alternatively, you can define your own constructor, but it needs to accept `**kwargs` and those need to be forwarded to the call to `super().__init__`.

**Comment by gerrymanoim** [comment]
Yep - makes sense, Thanks.
