### ISSUE TITLE
question: Ibis Dev Install Failure on Windows

### ISSUE THREAD

**Issue by Alex-Monahan** [ibis-project/ibis#3799]
Hi Folks!

I'm the docs / tutorials guy on the DuckDB Labs team and I was trying to create an Ibis tutorial for DuckDB's docs site. However, it looks like DuckDB isn't in the latest release. So I tried to build a development version of Ibis to test things out and ran into an error. I'm on Windows 10 and using Anaconda and Python 3.9. I'm following your instructions here: https://ibis-project.org/docs/dev/contribute/01_environment/#support-matrix_1. The only difference is that I did not install MiniConda as I already have Anaconda installed.

If the DuckDB backend will be released soon, then I can skip this step, but I wanted to report the bug here in case it is helpful!

After running this command:
```python
 pip install -e .
```

I get this error:
```python
(ibis-dev) PS C:\Users\Alex\Documents\DuckDB\ibis> pip install -e .
Obtaining file:///C:/Users/Alex/Documents/DuckDB/ibis
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' 'C:\ProgramData\Anaconda3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Alex\AppData\Local\Temp\pip-build-env-nqpt8aeg\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry-core>=1' poetry-dynamic-versioning setuptools wheel
  Complete output (14 lines):
  Traceback (most recent call last):
    File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "C:\ProgramData\Anaconda3\lib\site-packages\pip\__main__.py", line 21, in <module>
      from pip._internal.cli.main import main as _main
    File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\cli\main.py", line 3, in <module>
      import locale
    File "C:\ProgramData\Anaconda3\lib\locale.py", line 16, in <module>
      import re
    File "C:\ProgramData\Anaconda3\lib\re.py", line 145, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
WARNING: Discarding file:///C:/Users/Alex/Documents/DuckDB/ibis. Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' 'C:\ProgramData\Anaconda3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Alex\AppData\Local\Temp\pip-build-env-nqpt8aeg\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry-core>=1' poetry-dynamic-versioning setuptools wheel Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' 'C:\ProgramData\Anaconda3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Alex\AppData\Local\Temp\pip-build-env-nqpt8aeg\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry-core>=1' poetry-dynamic-versioning setuptools wheel Check the logs for full command output.
```

**Comment by gforsyth** [comment]
Hey @Alex-Monahan -- the `duckdb` backend was released yesterday -- you can install it using either `pip install ibis-framework[duckdb]` or `conda install -c conda-forge ibis-duckdb`
