### ISSUE TITLE
question: can't connect to impala with LDAP auth

### ISSUE THREAD

**Issue by dijeasakura** [ibis-project/ibis#4560]
I cant connect to database Impala, i already success connecting via ODBC but when i want to try using Ibis-framework
It failed, this is the code

```
import ibis
import os
import pandas as pd
impala_host = 'xx.xx.xx.xx'
impala_port = 12345

ibis.impala.connect(impala_host, port= impala_port, database="default",  auth_mechanism = "LDAP", use_ssl = True, ca_cert = 'cacerts.pem', user = user, password = pass)
```

```
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\impala\client.py", line 113, in _get_cursor
    cursor = self.connection_pool.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\base\__init__.py", line 281, in connect
    new_backend.reconnect()
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\base\__init__.py", line 296, in reconnect
    self.do_connect(*self._con_args, **self._con_kwargs)
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\impala\__init__.py", line 280, in do_connect
    self._ensure_temp_db_exists()
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\impala\__init__.py", line 847, in _ensure_temp_db_exists
    if name not in self.list_databases():
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\impala\__init__.py", line 290, in list_databases
    cur = self.raw_sql('SHOW DATABASES')
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\base\sql\__init__.py", line 132, in raw_sql
    cursor = self.con.execute(query)  # type: ignore
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\impala\client.py", line 90, in execute
    cursor = self._get_cursor()
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\impala\client.py", line 122, in _get_cursor
    return self._new_cursor()
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\ibis\backends\impala\client.py", line 140, in _new_cursor
    cursor = con.cursor(user=params.get('user'), convert_types=True)
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\impala\hiveserver2.py", line 129, in cursor
    session = self.service.open_session(user, configuration)
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\impala\hiveserver2.py", line 1187, in open_session
    resp = self._rpc('OpenSession', req, True)
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\impala\hiveserver2.py", line 1080, in _rpc
    response = self._execute(func_name, request, retry_on_http_error)
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\impala\hiveserver2.py", line 1095, in _execute
    open_transport(transport)
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\impala\hiveserver2.py", line 1159, in open_transport
    if not transport.isOpen():
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\thrift\transport\TTransport.py", line 152, in isOpen
    return self.__trans.isOpen()
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\site-packages\thrift\transport\TSocket.py", line 92, in isOpen
    peeked_bytes = self.handle.recv(1, socket.MSG_PEEK)
  File "C:\Users\XXX\Anaconda3\envs\ibis_test\lib\ssl.py", line 1224, in recv
    raise ValueError(
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
```

**Comment by cpcloud** [comment]
@dijeasakura Any chance you can give a try against the `master` branch? Connection pooling for impala was recently refactoring to address issues like this, by using SQLAlchemy's connection pooling.

**Comment by cpcloud** [comment]
Please try with the latest release!
