### ISSUE TITLE
Unable to  transform python value of type '<class 'numpy.datetime64'>' to DuckDB LogicalTypebug: 

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ibis-project/ibis#4997]
### What happened?

When using a `numpy.datetime64` to filter I get an error.

### What version of ibis are you using?

3.2.0

### What backend(s) are you using, if any?

duckdb==0.6.0

### Reproducible Example

```python
from pathlib import Path

import duckdb
import ibis
import numpy as np
import pandas as pd
import requests

TRIP_DATA_PATH = "yellow_tripdata_2022-02.parquet"

if not Path(TRIP_DATA_PATH).exists():
    url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet"
    response = requests.get(url, verify=False)
    with open(TRIP_DATA_PATH, "wb") as f:
        f.write(response.content)

DUCKDB_PATH = "DuckDB.db"

if not Path(DUCKDB_PATH).exists():
    duckdb_con = duckdb.connect(DUCKDB_PATH)
    duckdb_con.execute(f"CREATE TABLE big_df AS SELECT * FROM '{TRIP_DATA_PATH}'")
    duckdb_con.close()

ibis.options.sql.default_limit = None

db = ibis.duckdb.connect(DUCKDB_PATH)

big_table = db.table("big_df")

data = big_table[big_table.tpep_pickup_datetime >= np.datetime64('2022-02-08T06:01:38.761310')]
data.execute()
```

### Relevant log output

```sh
$ python script2.py
C:\repos\private\hvplot\.venv\lib\site-packages\ibis\backends\postgres\registry.py:164: UserWarning: locale specific date formats (%c, %x, %X) are not yet implemented for Windows
  warnings.warn(
C:\repos\private\hvplot\.venv\lib\site-packages\duckdb_engine\__init__.py:229: DuckDBEngineWarning: 
duckdb-engine doesn't yet support reflection on indices
  warnings.warn(
Traceback (most recent call last):
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in 
do_execute
    cursor.execute(statement, parameters)
  File "C:\repos\private\hvplot\.venv\lib\site-packages\duckdb_engine\__init__.py", line 120, in execute
    self.c.execute(statement, parameters)
duckdb.NotImplementedException: Not implemented Error: Unable to transform python value of type '<class 'numpy.datetime64'>' to DuckDB LogicalType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\repos\private\hvplot\script2.py", line 31, in <module>
    data.execute()
  File "C:\repos\private\hvplot\.venv\lib\site-packages\ibis\expr\types\core.py", line 291, in execute
    return self._find_backend(use_default=True).execute(
  File "C:\repos\private\hvplot\.venv\lib\site-packages\ibis\backends\base\sql\__init__.py", line 191, in execute
    with self._safe_raw_sql(sql, **kwargs) as cursor:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\repos\private\hvplot\.venv\lib\site-packages\ibis\backends\base\sql\alchemy\__init__.py", line 124, in _safe_raw_sql
    yield con.execute(*args, **kwargs)
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 210, in raise_
    raise exception
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\repos\private\hvplot\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in 
do_execute
    cursor.execute(statement, parameters)
  File "C:\repos\private\hvplot\.venv\lib\site-packages\duckdb_engine\__init__.py", line 120, in execute
    self.c.execute(statement, parameters)
sqlalchemy.exc.NotSupportedError: (duckdb.NotImplementedException) Not implemented Error: Unable to 
transform python value of type '<class 'numpy.datetime64'>' to DuckDB LogicalType
[SQL: SELECT t0."VendorID", t0.tpep_pickup_datetime, t0.tpep_dropoff_datetime, t0.passenger_count, t0.trip_distance, t0."RatecodeID", t0.store_and_fwd_flag, t0."PULocationID", t0."DOLocationID", t0.payment_type, t0.fare_amount, t0.extra, t0.mta_tax, t0.tip_amount, t0.tolls_amount, t0.improvement_surcharge, t0.total_amount, t0.congestion_surcharge, t0.airport_fee
FROM big_df AS t0
WHERE t0.tpep_pickup_datetime >= CAST(? AS TIMESTAMP WITHOUT TIME ZONE)]
[parameters: (numpy.datetime64('2022-02-08T06:01:38.761310'),)]
(Background on this error at: https://sqlalche.me/e/14/tw8g)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional Context

I'm trying to get ibis with the duckdb backend working with hvPlot/ HoloViews. See https://github.com/holoviz/holoviews/issues/5557#issuecomment-1345157033.

I don't know if this is as expected (its not for me :-)), an issue for ibis or an issue for duckdb

**Comment by gforsyth** [comment]
Hey @MarcSkovMadsen -- thanks for the report.

For your reproducer, you can make use of the `register` command to simplify your setup,e .g.

```python
import ibis

con = ibis.duckdb.connect()
big_table = con.register("https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet", table_name="big_df")
...
```

It looks like this is an Ibis issue -- I don't remember if we used to support this, but I don't see a reason why we shouldn't.  You can work around this by providing only the string of the timestamp and Ibis will handle the translation for you:

```python
data = big_table[big_table.tpep_pickup_datetime >= "2022-02-08T06:01:38.761310"]
```

(This may require being on `master` as we've made several changes since 3.2.0 was released)

**Comment by cpcloud** [comment]
Glad to see the duckdb issue was fixed upstream!

It turns out there's an ibis issue as well, which is that we don't know how to infer `np.datetime64` values with units other than no units or nanoseconds.

I have a fix locally that I've tested interactively with ipython, and (other than the funky progress bar stuff that I've removed here) the results look correct:

```
In [3]: import ibis, numpy as np

In [4]: ibis.options.interactive = True

In [5]: con = ibis.duckdb.connect()

In [6]: t = con.register("https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet")

In [7]: data = t[t.tpep_pickup_datetime >= np.datetime64('2022-02-08T06:01:38.761310')]

In [8]: data

┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┳━━┓
┃ VendorID ┃ tpep_pickup_datetime ┃ tpep_dropoff_datetime ┃ passenger_count ┃ trip_distance ┃ RatecodeID ┃ store_and_fwd_flag ┃ PULocationID ┃ DOLocationID ┃ payment_type ┃ fare_amou… ┃ extra   ┃  ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━╇━━┩
│ int64    │ timestamp            │ timestamp             │ float64         │ float64       │ float64    │ string             │ int64        │ int64        │ int64        │ float64    │ float64 │  │
├──────────┼──────────────────────┼───────────────────────┼─────────────────┼───────────────┼────────────┼────────────────────┼──────────────┼──────────────┼──────────────┼────────────┼─────────┼──┤
│        2 │ 2022-02-08 07:59:01  │ 2022-02-08 08:45:33   │             1.0 │         12.88 │        1.0 │ N                  │          138 │           90 │            1 │       42.0 │     0.5 │  │
│        2 │ 2022-02-08 08:57:45  │ 2022-02-08 09:04:48   │             1.0 │          0.87 │        1.0 │ N                  │          164 │          100 │            1 │        6.5 │     0.5 │  │
│        2 │ 2022-02-08 09:07:50  │ 2022-02-08 09:25:37   │             1.0 │          1.90 │        1.0 │ N                  │          186 │          161 │            2 │       12.0 │     0.5 │  │
│        2 │ 2022-02-08 09:39:00  │ 2022-02-08 09:46:52   │             1.0 │          1.15 │        1.0 │ N                  │          164 │          162 │            1 │        7.0 │     0.5 │  │
│        2 │ 2022-02-08 09:47:34  │ 2022-02-08 09:53:56   │             1.0 │          0.74 │        1.0 │ N                  │          161 │          161 │            1 │        6.0 │     0.5 │  │
│        2 │ 2022-02-08 10:01:56  │ 2022-02-08 10:25:02   │             1.0 │          2.81 │        1.0 │ N                  │          162 │          262 │            1 │       16.0 │     0.5 │  │
│        2 │ 2022-02-08 11:49:13  │ 2022-02-08 12:37:14   │             1.0 │         10.43 │        1.0 │ N                  │          138 │          161 │            1 │       39.5 │     0.5 │  │
│        2 │ 2022-02-08 14:40:47  │ 2022-02-08 15:14:17   │             1.0 │          9.08 │        1.0 │ N                  │          138 │           79 │            1 │       31.0 │     0.5 │  │
│        2 │ 2022-02-08 15:17:49  │ 2022-02-08 15:36:50   │             1.0 │          3.84 │        1.0 │ N                  │           79 │          140 │            1 │       15.5 │     0.5 │  │
│        2 │ 2022-02-08 17:15:29  │ 2022-02-08 17:45:34   │             1.0 │          9.12 │        1.0 │ N                  │          138 │          141 │            1 │       29.5 │     0.0 │  │
│        … │ …                    │ …                     │               … │             … │          … │ …                  │            … │            … │            … │          … │       … │  │
└──────────┴──────────────────────┴───────────────────────┴─────────────────┴───────────────┴────────────┴────────────────────┴──────────────┴──────────────┴──────────────┴────────────┴─────────┴──┘
```

**Comment by cpcloud** [comment]
We may actually be able to workaround duckdb and have this work in 4.0.0 by normalizing all timestamp-like literals to `datetime.datetime` values!
