### ISSUE TITLE
bug: Cannot create table with column type timestamp(6) or cast timestamp to timestamp(6) while using Trino backend with iceberg connector

### ISSUE THREAD

**Issue by arun-k-bharathan** [ibis-project/ibis#5143]
### What happened?

When I tried to create a table with column type timestamp in iceberg using Trino backend, 
```python

    connection = ibis.trino.connect(host="localhost",port=8080,user="test",password="",database="iceberg",schema="dev")

    with connection.con.engine.connect() as conn:
        conn.execute(text("CREATE SCHEMA iceberg.dev WITH (location = 's3a://dev/')"))
   
    first = ibis.schema({"a": "timestamp"})
    connection.create_table("iceberg_table", schema=first)

```

above code gave this error

`sqlalchemy.exc.ProgrammingError: (trino.exceptions.TrinoUserError) TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Timestamp precision (3) not supported for Iceberg. Use "timestamp(6)" instead.", query_id=20230105_100009_00146_txmuh)`

then I tried to use timestamp(6) as column type instead of timestamp, then I got the below error

`
raise ParseError(result.expected, stream, result.furthest)
parsy.ParseError: expected '(\'[^\n\'\\\\]*(?:\\\\.[^\n\'\\\\]*)*\'|"[^\n"\\\\"]*(?:\\\\.[^\n"\\\\]*)*")' at 0:10
`

Is there a way I can use timestamp(6) as the column type? Please help.

[Here](https://github.com/arun-k-bharathan/ibis_issue) I have attached the python code and my docker-compose setup.

### What version of ibis are you using?

Was using the master with commit ID [4faef5a](https://github.com/ibis-project/ibis/commit/4faef5adde48b34e34bbd2f8734cba9abe382edd)

### What backend(s) are you using, if any?

Trino backend with iceberg connector.

### Relevant log output

```sh
**Error Output when I tried to use timestamp as column type:**

Traceback (most recent call last):
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/sqlalchemy/dialect.py", line 365, in do_execute
    cursor.execute(statement, parameters)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/dbapi.py", line 439, in execute
    result = self._query.execute()
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 765, in execute
    self._result.rows += self.fetch()
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 780, in fetch
    status = self._request.process(response)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 581, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Timestamp precision (3) not supported for Iceberg. Use "timestamp(6)" instead.", query_id=20230105_101902_00353_txmuh)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arun/Documents/python/ibis_trino_iceberg_issue/runme.py", line 12, in <module>
    connection.create_table("iceberg_table", schema=first)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/backends/base/sql/alchemy/__init__.py", line 218, in create_table
    table.create(bind=bind, checkfirst=force)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 962, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 895, in visit_table
    self.connection.execute(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
    ret = self._execute_context(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/sqlalchemy/dialect.py", line 365, in do_execute
    cursor.execute(statement, parameters)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/dbapi.py", line 439, in execute
    result = self._query.execute()
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 765, in execute
    self._result.rows += self.fetch()
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 780, in fetch
    status = self._request.process(response)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 581, in process
    raise self._process_error(response["error"], response.get("id"))
sqlalchemy.exc.ProgrammingError: (trino.exceptions.TrinoUserError) TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Timestamp precision (3) not supported for Iceberg. Use "timestamp(6)" instead.", query_id=20230105_101902_00353_txmuh)
[SQL: 
CREATE TABLE iceberg_table (
        a TIMESTAMP
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)



**Error Output when I tried to use timestamp(6) as column type:**

Traceback (most recent call last):
  File "/home/arun/Documents/python/ibis_trino_iceberg_issue/runme.py", line 11, in <module>
    first = ibis.schema({"a": "timestamp(6)"})
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/expr/api.py", line 277, in schema
    return sch.schema(pairs)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/expr/schema.py", line 408, in schema_from_mapping
    return Schema.from_dict(d)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/expr/schema.py", line 204, in from_dict
    return cls(names, types)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/common/grounds.py", line 23, in __call__
    return cls.__create__(*args, **kwargs)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/common/grounds.py", line 99, in __create__
    kwargs = cls.__signature__.validate(*args, **kwargs)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/common/annotations.py", line 261, in validate
    this[name] = param.validate(value, this=this)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/common/annotations.py", line 115, in validate
    return self.annotation(arg, this=this)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/common/validators.py", line 193, in container_of
    return type(inner(item, **kwargs) for item in arg)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/common/validators.py", line 193, in <genexpr>
    return type(inner(item, **kwargs) for item in arg)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/expr/schema.py", line 43, in datatype
    return dt.dtype(arg)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/expr/datatypes/parse.py", line 249, in from_string
    return parse(value)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/expr/datatypes/parse.py", line 243, in parse
    return ty.parse(text)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/parsy/__init__.py", line 87, in parse
    (result, _) = (self << eof).parse_partial(stream)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/parsy/__init__.py", line 101, in parse_partial
    raise ParseError(result.expected, stream, result.furthest)
parsy.ParseError: expected '(\'[^\n\'\\\\]*(?:\\\\.[^\n\'\\\\]*)*\'|"[^\n"\\\\"]*(?:\\\\.[^\n"\\\\]*)*")' at 0:10
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@arun-k-bharathan Can you try out PR #5146 against your setup?

**Comment by arun-k-bharathan** [comment]
> @arun-k-bharathan Can you try out PR #5146 against your setup?

Hi, Thank you @cpcloud.

```python
    connection = ibis.trino.connect(host="localhost",port=8080,user="test",password="",database="iceberg",schema="dev")

    with connection.con.engine.connect() as conn:
        conn.execute(text("CREATE SCHEMA iceberg.dev WITH (location = 's3a://dev/')"))
   
    first = ibis.schema({"a": "timestamp(6)"})
    connection.create_table("iceberg_table", schema=first)
```

I tried running above code with fix #5146 branch, together with below change in poetry dependencies (also ran  _poetry lock_ and _poetry install_ commands before running.)
```toml
ibis-framework = {git = "https://github.com/cpcloud/ibis.git", branch="optional-timestamp-scale"}
```

but from trino UI I can see still a query without _timestamp(6)_ is logged.
```sql
CREATE TABLE iceberg_table (
	a TIMESTAMP
)
```

This is the error log when I ran above code.

> Traceback (most recent call last):
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/sqlalchemy/dialect.py", line 365, in do_execute
    cursor.execute(statement, parameters)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/dbapi.py", line 439, in execute
    result = self._query.execute()
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 765, in execute
    self._result.rows += self.fetch()
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 780, in fetch
    status = self._request.process(response)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 581, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Timestamp precision (3) not supported for Iceberg. Use "timestamp(6)" instead.", query_id=20230109_071639_00008_fuyhn)

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/home/arun/Documents/python/ibis_trino_iceberg_issue/runme.py", line 23, in <module>
    connection.create_table("iceberg_table", schema=first)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/src/ibis/ibis/backends/base/sql/alchemy/__init__.py", line 218, in create_table
    table.create(bind=bind, checkfirst=force)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 962, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 895, in visit_table
    self.connection.execute(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
    ret = self._execute_context(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/sqlalchemy/dialect.py", line 365, in do_execute
    cursor.execute(statement, parameters)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/dbapi.py", line 439, in execute
    result = self._query.execute()
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 765, in execute
    self._result.rows += self.fetch()
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 780, in fetch
    status = self._request.process(response)
  File "/home/arun/.cache/pypoetry/virtualenvs/ibis-trino-iceberg-issue-f4L1yFwb-py3.10/lib/python3.10/site-packages/trino/client.py", line 581, in process
    raise self._process_error(response["error"], response.get("id"))
sqlalchemy.exc.ProgrammingError: (trino.exceptions.TrinoUserError) TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Timestamp precision (3) not supported for Iceberg. Use "timestamp(6)" instead.", query_id=20230109_071639_00008_fuyhn)
[SQL: 
CREATE TABLE iceberg_table (
        a TIMESTAMP
)

> ]
> (Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by cpcloud** [comment]
@arun-k-bharathan I am unable to reproduce your error using the `memory` connector with this test:

```
def test_create_table_timestamp(con):
    schema = ibis.schema({"a": "timestamp(6)"})
    con.create_table("ts_table", schema=schema, force=True)
    try:
        assert "ts_table" in con.list_tables()
    finally:
        con.drop_table("ts_table", force=True)
```

Does your `poetry.lock` file show that `ibis` is in fact the right one (my branch)?

**Comment by cpcloud** [comment]
@arun-k-bharathan Can you try using `git = "...", ref = "optional-timestamp-scale", branch = "optional-timestamp-scale"` instead? I know it's kind of gross, but I remember having issues with this in the past.

**Comment by arun-k-bharathan** [comment]
Hi @cpcloud, my poetry lock is pointing to below branch and commit
```
[package.source]
type = "git"
url = "https://github.com/cpcloud/ibis.git"
reference = "optional-timestamp-scale"
resolved_reference = "a6fc5fc301f4d216a9ad9336e6c55014ca364e32"
```
Also while I step into ibis code using debug feature in vscode it shows changes in this branch.

I just now tried with memory connector where I tried with both
```
ibis.schema({"a": "timestamp(6)"})
ibis.schema({"a": "timestamp"})
```

And both worked for me too,  but when I checked in trino UI available in localhost:8080 I can see both generating same sql query
```sql
CREATE TABLE memory_table (
	a TIMESTAMP
)
```

And I did a describe table from trino-cli where I got same table describe for both type of schemas.

```
trino> describe memory.dev.memory_table;
 Column |     Type     | Extra | Comment 
--------+--------------+-------+---------
 a      | timestamp(3) |       |         
(1 row)

Query 20230109_190910_00091_accbh, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.07 [1 rows, 67B] [14 rows/s, 971B/s]
```

**Comment by cpcloud** [comment]
> Hi @cpcloud, my poetry lock is pointing to below branch and commit
> 
> ```
> [package.source]
> type = "git"
> url = "https://github.com/cpcloud/ibis.git"
> reference = "optional-timestamp-scale"
> resolved_reference = "a6fc5fc301f4d216a9ad9336e6c55014ca364e32"
> ```
> 
> Also while I step into ibis code using debug feature in vscode it shows changes in this branch.
> 
> I just now tried with memory connector where I tried with both
> 
> ```
> ibis.schema({"a": "timestamp(6)"})
> ibis.schema({"a": "timestamp"})
> ```
> 
> And both worked for me too, but when I checked in trino UI available in localhost:8080 I can see both generating same sql query
> 
> ```sql
> CREATE TABLE memory_table (
> 	a TIMESTAMP
> )
> ```
> 
> And I did a describe table from trino-cli where I got same table describe for both type of schemas.
> 
> ```
> trino> describe memory.dev.memory_table;
>  Column |     Type     | Extra | Comment 
> --------+--------------+-------+---------
>  a      | timestamp(3) |       |         
> (1 row)
> 
> Query 20230109_190910_00091_accbh, FINISHED, 1 node
> Splits: 19 total, 19 done (100.00%)
> 0.07 [1 rows, 67B] [14 rows/s, 971B/s]
> ```

Thanks for digging in. Let me poke around the trino logs and see what my test's query looks like.

**Comment by cpcloud** [comment]
@arun-k-bharathan Can you give that PR a try again? I think I got to the bottom of it.

**Comment by arun-k-bharathan** [comment]
Hi, now this works without any issue for me :heart_eyes_cat: , verified the generated queries also.
Thanks @cpcloud .
