### ISSUE TITLE
feat(pandas): unnest support

### ISSUE THREAD

**Issue by dakoop** [ibis-project/ibis#5478]
### Is your feature request related to a problem?

The pandas backend does not currently support unnest.

### Describe the solution you'd like

Would [pd.Series.explode](https://pandas.pydata.org/docs/reference/api/pandas.Series.explode.html#pandas.Series.explode) work here? It looks like the problem with such a solution is the cardinality change which means the original data index cannot be assigned here (assertion fails):
https://github.com/ibis-project/ibis/blob/0e8b06643bfe81fd8694c5578324f263e49b9890/ibis/backends/pandas/execution/selection.py#L261-L267
If the check fails, perhaps you could just skip the assignment of the original `data.index`? This seems to work for a very simple test case... Thanks for this project!

### What version of ibis are you running?

4.1.0

### What backend(s) are you using, if any?

pandas

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@dakoop Thanks for the issue! Care to try your hand at a PR for this? Happy to help review it!

**Comment by dakoop** [comment]
Ok, thought I would dump the code I had in PR, but I cannot run the basic unnest test because it looks like the `array_types` [test data](https://github.com/ibis-project/ibis/blob/da105eb76ab01ad53381da272a908351d7cf47eb/ibis/backends/tests/data.py#L6-L65) won't load in the pandas backend despite being constructed in pandas...

```python
import ibis
from ibis.backends.tests.data import array_types
t = ibis.pandas.connect({'array_types': array_types}).table('array_types')
t.execute()
```
produces
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/ibis/expr/types/core.py", line 300, in execute
    return self._find_backend(use_default=True).execute(
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/ibis/backends/pandas/__init__.py", line 238, in execute
    return execute_and_reset(node, params=params, **kwargs)
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/ibis/backends/pandas/core.py", line 498, in execute_and_reset
    return _apply_schema(node, result)
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/ibis/backends/pandas/core.py", line 506, in _apply_schema
    return schema.apply_to(df.loc[:, list(schema.names)])
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/ibis/expr/schema.py", line 416, in apply_to
    new_col = convert(col_dtype, dtype, col)
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/ibis/backends/pandas/client.py", line 173, in convert_array_to_series
    return column.map(lambda x: x if x is None else list(x))
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/pandas/core/series.py", line 4539, in map
    new_values = self._map_values(arg, na_action=na_action)
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/pandas/core/base.py", line 890, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "/opt/mamba/envs/ibis/lib/python3.10/site-packages/ibis/backends/pandas/client.py", line 173, in <lambda>
    return column.map(lambda x: x if x is None else list(x))
TypeError: 'float' object is not iterable
```
There's a lot going on here due, I believe, to the representation of null arrays (a value that is `np.nan`, so there is no array, see column z of `array_types`). Looking at https://github.com/ibis-project/ibis/blob/da105eb76ab01ad53381da272a908351d7cf47eb/ibis/backends/pandas/client.py#L196-L198
`np.nan` will not be flagged and gets transformed into a `list(np.nan)`? Inserting other checks into that method allows the `array_types` data to execute and the basic unnest test to get further but leads to an issue with `execute_cast_series_array` (`AttributeError: 'list' object has no attribute 'astype'`). I haven't been able to push through that.
