### ISSUE TITLE
bug: Timestamp.time() errors on translation to SQL

### ISSUE THREAD

**Issue by Tishj** [ibis-project/ibis#5649]
### What happened?

It seems that getting a `TimeColumn` from a `TimestampColumn` fails on translation to SQL

Setup
```py
import ibis
import ibis.expr.datatypes as dt

t = ibis.table([("d", dt.timestamp)], "tbl")
expr = t[getattr(t.d.time(), "minute")()]
```

Problematic command:
```py
ibis.to_sql(expr)
```

### What version of ibis are you using?

4.1.0

### What backend(s) are you using, if any?

default

### Relevant log output

```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/expr/sql.py", line 385, in to_sql
    compiled = backend.compile(expr)
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/__init__.py", line 331, in compile
    return self.compiler.to_ast_ensure_limit(expr, limit, params=params).compile()
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/compiler/base.py", line 40, in compile
    compiled_queries = [q.compile() for q in self.queries]
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/compiler/base.py", line 40, in <listcomp>
    compiled_queries = [q.compile() for q in self.queries]
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/query_builder.py", line 169, in compile
    frag = step(frag)
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/query_builder.py", line 199, in _add_select
    arg = self._translate(op, named=True)
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/compiler/query_builder.py", line 214, in _translate
    return translator.get_result()
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/compiler/translator.py", line 211, in get_result
    translated = self.translate(self.node)
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/compiler/translator.py", line 243, in translate
    return formatter(self, op)
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/registry.py", line 489, in translator
    return sa.cast(sa.extract(fmt, t.translate(op.arg)), sa.SMALLINT)
  File "/opt/homebrew/lib/python3.10/site-packages/ibis/backends/base/sql/compiler/translator.py", line 245, in translate
    raise com.OperationNotDefinedError(f'No translation rule for {type(op)}')
ibis.common.exceptions.OperationNotDefinedError: No translation rule for <class 'ibis.expr.operations.temporal.Time'>
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tishj** [comment]
Please tell me if I'm just holding it wrong, could very well be the case :)

**Comment by cpcloud** [comment]
@Tishj Thanks for the report!

The default backend used to compile an expression is DuckDB, and in this case it looks like the `Time` operation may not be implemented.

We'll look at getting this into 5.0.

**Comment by cpcloud** [comment]
@Tishj For your exact example here, you can just call `.minute()` directly on a `timestamp` column. There's no need to first extract the `time` component.

**Comment by Tishj** [comment]
Awesome, so I was definitely just holding it wrong :P
Thanks for the quick reply!
