### ISSUE TITLE
ibis.memtable somehow mostly crashes with the below error in pycharm/ipython

### ISSUE THREAD

**Issue by ededovic** [ibis-project/ibis#5835]
```
import io
import pandas as pd
import ibis
from ibis.interactive import *
```
Reproducable example:
```
sample = io.StringIO('''
         col_0 col_1 col_2  col_3
2021-02-05   USA    AL    136
2021-02-07   USA    AL    -57
2021-02-10   USA    AL    182
2021-02-19   USA    AL     96
2021-02-24   USA    AL   -310
    ''')
sample = pd.read_csv(sample, sep='\s+', engine='python')
tbl = ibis.memtable(sample)
```
when I type `tbl` to show it in  ipython (under pycharm), I get the below error. If I type `sample.head()`, the whole console crashes. 
I noticed that it works ok in jupyter lab though. 

```
Traceback (most recent call last):
  File "path\envs\ml310\lib\site-packages\IPython\core\formatters.py", line 221, in catch_format_error
    r = method(self, *args, **kwargs)
  File "path\envs\ml310\lib\site-packages\IPython\core\formatters.py", line 706, in __call__
    printer.pretty(obj)
  File "path\envs\ml310\lib\site-packages\IPython\lib\pretty.py", line 410, in pretty
    return _repr_pprint(obj, self, cycle)
  File "path\envs\ml310\lib\site-packages\IPython\lib\pretty.py", line 778, in _repr_pprint
    output = repr(obj)
  File "path\envs\ml310\lib\site-packages\ibis\expr\types\core.py", line 56, in __repr__
    simple_console.print(self)
  File "path\envs\ml310\lib\site-packages\rich\console.py", line 1698, in print
    extend(render(renderable, render_options))
  File "path\envs\ml310\lib\site-packages\rich\console.py", line 1310, in render
    render_iterable = renderable.__rich_console__(self, _options)  # type: ignore[union-attr]
  File "path\envs\ml310\lib\site-packages\ibis\expr\types\relations.py", line 259, in __rich_console__
    table = to_rich_table(self, width)
  File "path\envs\ml310\lib\site-packages\ibis\expr\types\pretty.py", line 230, in to_rich_table
    result = table.limit(nrows + 1).execute()
  File "path\envs\ml310\lib\site-packages\ibis\expr\types\core.py", line 303, in execute
    return self._find_backend(use_default=True).execute(
  File "path\envs\ml310\lib\site-packages\ibis\backends\base\sql\__init__.py", line 246, in execute
    self._register_in_memory_tables(expr)
  File "path\envs\ml310\lib\site-packages\ibis\backends\base\sql\__init__.py", line 262, in _register_in_memory_tables
    self._register_in_memory_table(memtable)
  File "path\envs\ml310\lib\site-packages\ibis\backends\duckdb\__init__.py", line 697, in _register_in_memory_table
    con.connection.register(name, table)
duckdb.InvalidInputException: Invalid Input Error: Optional module 'pyarrow.dataset' is required to perform this action
```

List of relevant packages: 
```
# Name                    Version
arrow-cpp                 11.0.0
duckdb-engine             0.6.8
ibis-framework            5.0.0
libarrow                  11.0.0
pandas                    1.5.3
pyarrow                   11.0.0
python-duckdb             0.7.1
```

**Comment by gforsyth** [comment]
Thanks for the report @ededovic !

How did you install `pyarrow`? 

And can you confirm that `pyarrow.__version__` matches what you have listed when you run in the pycharm console?

**Comment by ededovic** [comment]
Thank you. It matches: 
```
import pyarrow
pyarrow.__version__
Out[6]: '11.0.0'
```
I installed it via conda: `conda install pyarrow`. It seems to be coming from conda-forge .

**Comment by gforsyth** [comment]
Great.  And can you successfully `import pyarrow.dataset`?

**Comment by ededovic** [comment]
Thank you. Interestingly. I can not in pycharm, but no problem in jupyter notebook. I'll open a ticket with pycharm. 
in **pycharm ipython** even when I import `pyarrow` there is no dataset

```
import pyarrow
[f for f in dir(pyarrow) if 'dataset' in f]
Out[7]: []
```
while it shows up in **jupyter notebook**. 
`['_dataset', '_dataset_parquet', 'dataset']`

**Comment by cpcloud** [comment]
Should we close this?
