### ISSUE TITLE
bug: `BooleanColumn().notany()` does not support `where`

### ISSUE THREAD

**Issue by anjakefala** [ibis-project/ibis#5988]
### What happened?

`BooleanColumn().notany()` [allows the passing of a `where` argument](https://github.com/ibis-project/ibis/blob/4b286bdf52d0e6f899c51dcfff994ea35c6cd96b/ibis/expr/types/logical.py#L92).

But in practice, this seems to happen:

```                                                                                    
 >>> import ibis                                                                              
>>> ibis.options.interactive = True                                                          
>>> t = ibis.memtable({"arr": [1, 2, 3, 4]})                                              
 >>> (t.arr > 2).notany(where=(t.arr != 3))
 ```
```
AttributeError: Neither 'UnaryExpression' object nor 'Comparator' object has an attribute 'filter'
```

The same expression works with `any`:

```
 >>> import ibis                                                                              
>>> ibis.options.interactive = True                                                          
>>> t = ibis.memtable({"arr": [1, 2, 3, 4]})                                              
 >>> (t.arr > 2).any(where=(t.arr != 3))
 True
```

### What version of ibis are you using?

`master` branch

### What backend(s) are you using, if any?

Default backend

### Relevant log output

```sh
287             Examples
288             --------
289             >>> import ibis
290             >>> ibis.options.interactive = True
291             >>> t = ibis.memtable({"arr": [1, 2, 3, 4]})
292             >>> (t.arr > 1).notany()
293             False
294             >>> (t.arr > 4).notany()
295             True
296             >>> (t.arr > 2).notany(where=(t.arr != 3))
UNEXPECTED EXCEPTION: AttributeError("Neither 'UnaryExpression' object nor 'Comparator' object has an attribute 'filter'")
Traceback (most recent call last):
  File "/home/anja/miniconda3/envs/ibis-dev/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 855, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'filter'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/anja/miniconda3/envs/ibis-dev/lib/python3.10/doctest.py", line 1350, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest ibis.expr.types.logical.BooleanColumn.notany[5]>", line 1, in <module>
  File "/home/anja/git/ibis/ibis/expr/types/core.py", line 56, in __repr__
    simple_console.print(self)
  File "/home/anja/miniconda3/envs/ibis-dev/lib/python3.10/site-packages/rich/console.py", line 1698, in print
    extend(render(renderable, render_options))
  File "/home/anja/miniconda3/envs/ibis-dev/lib/python3.10/site-packages/rich/console.py", line 1310, in render
    render_iterable = renderable.__rich_console__(self, _options)  # type: ignore[union-attr]
  File "/home/anja/git/ibis/ibis/expr/types/generic.py", line 654, in __rich_console__
    return console.render(repr(self.execute()), options=options)
  File "/home/anja/git/ibis/ibis/expr/types/core.py", line 303, in execute
    return self._find_backend(use_default=True).execute(
  File "/home/anja/git/ibis/ibis/backends/base/sql/__init__.py", line 244, in execute
    sql = query_ast.compile()
  File "/home/anja/git/ibis/ibis/backends/base/sql/compiler/base.py", line 40, in compile
    compiled_queries = [q.compile() for q in self.queries]
  File "/home/anja/git/ibis/ibis/backends/base/sql/compiler/base.py", line 40, in <listcomp>
    compiled_queries = [q.compile() for q in self.queries]
  File "/home/anja/git/ibis/ibis/backends/base/sql/alchemy/query_builder.py", line 194, in compile
    frag = step(frag)
  File "/home/anja/git/ibis/ibis/backends/base/sql/alchemy/query_builder.py", line 227, in _add_select
    arg = self._translate(op, named=True)
  File "/home/anja/git/ibis/ibis/backends/base/sql/compiler/query_builder.py", line 221, in _translate
    return translator.get_result()
  File "/home/anja/git/ibis/ibis/backends/base/sql/compiler/translator.py", line 206, in get_result
    translated = self.translate(self.node)
  File "/home/anja/git/ibis/ibis/backends/base/sql/compiler/translator.py", line 238, in translate
    return formatter(self, op)
  File "/home/anja/git/ibis/ibis/backends/base/sql/alchemy/registry.py", line 216, in _alias
    return t.translate(op.arg)
  File "/home/anja/git/ibis/ibis/backends/base/sql/compiler/translator.py", line 238, in translate
    return formatter(self, op)
  File "/home/anja/git/ibis/ibis/backends/base/sql/alchemy/registry.py", line 414, in compile_expr
    return t._reduction(sa_func, expr)
  File "/home/anja/git/ibis/ibis/backends/base/sql/alchemy/translator.py", line 111, in _reduction
    return sa_func(*sa_args).filter(self.translate(where))
  File "/home/anja/miniconda3/envs/ibis-dev/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 857, in __getattr__
    util.raise_(
  File "/home/anja/miniconda3/envs/ibis-dev/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
AttributeError: Neither 'UnaryExpression' object nor 'Comparator' object has an attribute 'filter'
/home/anja/git/ibis/ibis/expr/types/logical.py:296: UnexpectedException
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anjakefala** [comment]
I ran into the same thing with `BinaryColumn().notall()`!

**Comment by cpcloud** [comment]
Do you mean `BooleanColumn` 😅?

**Comment by anjakefala** [comment]
@cpcloud :sleepy:
