### ISSUE TITLE
bug: .first and .last raise "IbisTypeError: argument passes none of the following rules" under group_by/aggregate

### ISSUE THREAD

**Issue by ogrisel** [ibis-project/ibis#6192]
### What happened?

Since #6047 was merged, I tried the minimal snippet from #4149 and it fails as follows (using the default DuckDB backend):

```python
import ibis

tbl = ibis.table(name='A', schema=[('a', 'int32'), ('b', 'string')])
group_by_expression = tbl.aggregate(
    [tbl['a'].first().name('BB')],
    by=['b']
)
```

```python-traceback
Traceback (most recent call last):
  File "/Users/ogrisel/tmp/ibis_first_bug.py", line 4, in <module>
    group_by_expression = tbl.aggregate(
                          ^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/expr/types/relations.py", line 914, in aggregate
    agg = ops.Aggregation(
          ^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/common/grounds.py", line 25, in __call__
    return cls.__create__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/common/grounds.py", line 98, in __create__
    kwargs = cls.__signature__.validate(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/common/annotations.py", line 357, in validate
    this[name] = param.annotation.validate(value, this=this)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/common/annotations.py", line 58, in validate
    return self._validator(arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/common/validators.py", line 197, in option
    return inner(arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/common/validators.py", line 509, in tuple_of
    return sequence_of(inner, arg, type=type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/common/validators.py", line 474, in sequence_of
    return type(inner(item, **kwargs) for item in arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/common/validators.py", line 474, in <genexpr>
    return type(inner(item, **kwargs) for item in arg)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/sksurv/lib/python3.11/site-packages/ibis/common/validators.py", line 312, in any_of
    raise IbisTypeError(
ibis.common.exceptions.IbisTypeError: argument passes none of the following rules: function_of(ref('table',),output_rule=any_of((reduction(), scalar(value(None,),)),)), reduction(), scalar(value(None,),), tuple_of(scalar(value(None,),),)
```

The following works, though:

```python
tbl = ibis.table(name='A', schema=[('a', 'int32'), ('b', 'string')])
tbl.mutate(
    BB=tbl.a.first().over(ibis.window(group_by=['b'], order_by=["a"]))
)
```

replacing `mutate` by `aggregate` make it fail again with a similar error message as in the previous traceback:

```python
import ibis


tbl = ibis.table(name='A', schema=[('a', 'int32'), ('b', 'string')])
tbl.aggregate(
    BB=tbl.a.first().over(ibis.window(group_by=['b'], order_by=["a"]))
)
```

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ogrisel** [comment]
I did not noticed that #6047 was merged only recently. Let me try again with the dev version and close if it has been fixed.

**Comment by ogrisel** [comment]
I confirm that the first `aggregate` (without window) now works but the last snippet "aggregate over window" raises:

```python-tracebackTraceback (most recent call last):
  File "/Users/ogrisel/tmp/ibis_first_bug.py", line 5, in <module>
    tbl.aggregate(
  File "/Users/ogrisel/code/ibis/ibis/expr/types/relations.py", line 901, in aggregate
    agg = ops.Aggregation(
          ^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/common/grounds.py", line 25, in __call__
    return cls.__create__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/common/grounds.py", line 95, in __create__
    kwargs = cls.__signature__.validate(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/common/annotations.py", line 356, in validate
    this[name] = param.annotation.validate(value, this=this)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/common/annotations.py", line 58, in validate
    return self._validator(arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/ibisdev/lib/python3.11/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/common/validators.py", line 192, in option
    return inner(arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/ibisdev/lib/python3.11/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/common/validators.py", line 504, in tuple_of
    return sequence_of(inner, arg, type=type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/ibisdev/lib/python3.11/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/common/validators.py", line 469, in sequence_of
    return type(inner(item, **kwargs) for item in arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/common/validators.py", line 469, in <genexpr>
    return type(inner(item, **kwargs) for item in arg)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/expr/rules.py", line 97, in __call__
    result = super().__call__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/ibisdev/lib/python3.11/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/ibis/ibis/expr/rules.py", line 270, in scalar
    raise com.IbisTypeError(f"{arg} it not a scalar")
ibis.common.exceptions.IbisTypeError: <ibis.expr.operations.core.Alias object at 0x13e1a0340> it not a scalar
```

not sure if it's legit or not. But the `group_by/aggregate` case is the most natural expression for what I want to accomplish so let's close.
