### ISSUE TITLE
bug(postgres): `list_tables` fails

### ISSUE THREAD

**Issue by kenneth-copeland** [ibis-project/ibis#6309]
### What happened?

list_tables fails when connected to postges11.

```
import ibis
pgurl = "postgres://core:core@127.0.0.1:32768/core"
pgcon = ibis.connect(pgurl)

print("databases = ", pgcon.list_databases())                  # works
print("current database = ", pgcon.current_database)    # works
print("tables = ", pgcon.list_tables())                               # fails
```

See output below:

In particular, the WHERE clause SQL statement at the bottom looks suspect to me:

`[SQL: SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %(schema)s AND c.relkind in ('r', 'p')]`
[postgres_err.zip](https://github.com/ibis-project/ibis/files/11568815/postgres_err.zip)

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

Postgres

### Relevant log output

```sh
(dag3.8) ken::~/dev/dag/dagster/tests$ python pg.py
databases =  ['postgres', 'core', 'nats', 'keycloak']
current database =  core
/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/ibis/backends/postgres/__init__.py:162: UserWarning: Unable to create first/last aggregates: syntax error at or near "AGGREGATE"
LINE 6: CREATE OR REPLACE AGGREGATE public._ibis_first (anyelement) ...
                          ^

  warnings.warn(f"Unable to create first/last aggregates: {e}")
Traceback (most recent call last):
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pg.py", line 7, in <module>
    print("tables = ", pgcon.list_tables())
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 102, in list_tables
    tables = self.inspector.get_table_names(schema=database)
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 266, in get_table_names
    return self.dialect.get_table_names(
  File "<string>", line 2, in get_table_names
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3755, in get_table_names
    result = connection.execute(
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/ken/mambaforge/envs/dag3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block

[SQL: SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %(schema)s AND c.relkind in ('r', 'p')]
[parameters: {'schema': 'public'}]
(Background on this error at: https://sqlalche.me/e/14/2j85)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenneth-copeland** [comment]
I should have been more specific about what I think looks wrong in the SQL statement at the end of the log.


[SQL: SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname =
 **%(schema)s** 
AND c.relkind in ('r', 'p')]
[parameters: {'schema': 'public'}]

The schema paramater "$(schema)" is concatonated with a single "s" character.  When I try to run that statement separately it fails when the "s" is included in the SQL statement.  If I remove the "s" the SELECT works fine.  

I tried to look in the ibis codebase to see if I could identify where that might be happening, but could not find it.  

I suspect it coud be in SqlAlchemy code. 

Thanks
ken

**Comment by kenneth-copeland** [comment]
So I found what appears to be the "template" for the SQL in the SqlAlchemy 1.4.46 codebase.  (1.4.6 is the specific version that conda has pulled in my environemt)

From  lib/sqlalchemy/dialects/postgres/base.py:3753:

```
    @reflection.cache
    def get_table_names(self, connection, schema=None, **kw):
        result = connection.execute(
            sql.text(
                "SELECT c.relname FROM pg_class c "
                "JOIN pg_namespace n ON n.oid = c.relnamespace "
                "WHERE n.nspname = :schema AND c.relkind in ('r', 'p')"
            ).columns(relname=sqltypes.Unicode),
            dict(
                schema=schema
                if schema is not None
                else self.default_schema_name
            ),
        )
        return [name for name, in result]
```

Not sure what is transforming the ":schema" in that remplate into "%(schema)s" in the final SQL though.

ken

**Comment by kenneth-copeland** [comment]
I have no idea if any of my previous musings into the problem are on the right track.

I just tried rolling back to previous Ibis versions, and version 5.0.0, and 4.1.0 work fine.  Only seems to be a problem if ibis-framework-core 5.1.0 is being used.

Thanks
ken

**Comment by cpcloud** [comment]
Thanks for the issue @kenneth-copeland!

I believe this may be the same problem as described in https://github.com/ibis-project/ibis/issues/6271.

We're working on a fix, stay tuned!
