### ISSUE TITLE
bug: utf decode error for parquet file during pandas conversion

### ISSUE THREAD

**Issue by caleboverman** [ibis-project/ibis#6631]
### What happened?

I've got a parquet file on S3 that I'm operating against with ibis. It gets loaded first as a pyarrow dataset, registered as a table with the duckdb backend, and then loaded to pandas.
```
dataset = ds.dataset(
    source=s3_file,
    format="parquet",
    filesystem=s3_filesystem,
    partitioning="hive",
)
con = ibis.duckdb.connect()
ibis_table = con.register(dataset)
df = ibis_table.to_pandas()
```
This raises:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 1: invalid continuation byte`

However if I try to read each column individually they all load correctly:
```
for col in ibis_table.schema():
    df = ibis_table.select(col).to_pandas()
```

Both pyarrow and duckdb can read the parquet file without issue.

### What version of ibis are you using?

ibis==6.0.0
pandas==2.0.1
pyarrow==12.0.1
duckdb==0.8.1

### What backend(s) are you using, if any?

DuckDB

### Relevant log output

```sh
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[35], line 1
----> 1 df = ibis_table.to_pandas()
File ~/opt/anaconda3/envs/fts/lib/python3.10/site-packages/ibis/expr/types/relations.py:2693, in Table.to_pandas(self=r0 := DatabaseTable: _ibis_read_in_memory_uc4anu...ion[r0]
   2685 def to_pandas(self, **kwargs) -> pd.DataFrame:
   2686     """Convert a table expression to a pandas DataFrame.
   2687
   2688     Parameters
   (...)
   2691         Same as keyword arguments to [`execute`][ibis.expr.types.core.Expr.execute]
   2692     """
-> 2693     return self.execute(**kwargs)

File ~/opt/anaconda3/envs/fts/lib/python3.10/site-packages/ibis/expr/types/core.py:296, in Expr.execute(self=r0 := DatabaseTable: _ibis_read_in_memory_uc4anu...ion[r0]
    269 def execute(
    270     self,
    271     limit: int | str | None = 'default',
   (...)
    274     **kwargs: Any,
    275 ):
    276     """Execute an expression against its backend if one exists.
    277
    278     Parameters
   (...)
    294         Keyword arguments
    295     """
--> 296     return self._find_backend(use_default=True).execute(
    297         self, limit=limit, timecontext=timecontext, params=params, **kwargs
    298     )

File ~/opt/anaconda3/envs/fts/lib/python3.10/site-packages/ibis/backends/base/sql/__init__.py:263, in BaseSQLBackend.execute(self=<ibis.backends.duckdb.Backend object>, expr=r0 := DatabaseTable: _ibis_read_in_memory_uc4anu...ion[r0]
    260 schema = expr.as_table().schema()
    262 with self._safe_raw_sql(sql, **kwargs) as cursor:
--> 263     result = self.fetch_from_cursor(cursor, schema)
    265 if hasattr(getattr(query_ast, 'dml', query_ast), 'result_handler'):
    266     result = query_ast.dml.result_handler(result)

File ~/opt/anaconda3/envs/fts/lib/python3.10/site-packages/ibis/backends/duckdb/__init__.py:881, in Backend.fetch_from_cursor(self=<ibis.backends.duckdb.Backend object>, cursor=<sqlalchemy.engine.cursor.LegacyCursorResult object>, schema=ibis.Schema {
    876 import pyarrow.types as pat
    878 table = cursor.cursor.fetch_arrow_table()
    880 df = pd.DataFrame(
--> 881     {
    882         name: (
    883             col.to_pylist()
    884             if (
    885                 pat.is_nested(col.type)
    886                 or
    887                 # pyarrow / duckdb type null literals columns as int32?
    888                 # but calling `to_pylist()` will render it as None
    889                 col.null_count
    890             )
    891             else col.to_pandas(timestamp_as_object=True)
    892         )
    893         for name, col in zip(table.column_names, table.columns)
    894     }
    895 )
    896 return PandasData.convert_table(df, schema)

File ~/opt/anaconda3/envs/fts/lib/python3.10/site-packages/ibis/backends/duckdb/__init__.py:883, in <dictcomp>(.0=<zip object>)
    876 import pyarrow.types as pat
    878 table = cursor.cursor.fetch_arrow_table()
    880 df = pd.DataFrame(
    881     {
    882         name: (
--> 883             col.to_pylist()
    884             if (
    885                 pat.is_nested(col.type)
    886                 or
    887                 # pyarrow / duckdb type null literals columns as int32?
    888                 # but calling `to_pylist()` will render it as None
    889                 col.null_count
    890             )
    891             else col.to_pandas(timestamp_as_object=True)
    892         )
    893         for name, col in zip(table.column_names, table.columns)
    894     }
    895 )
    896 return PandasData.convert_table(df, schema)

File ~/opt/anaconda3/envs/fts/lib/python3.10/site-packages/pyarrow/table.pxi:1312, in pyarrow.lib.ChunkedArray.to_pylist()

File ~/opt/anaconda3/envs/fts/lib/python3.10/site-packages/pyarrow/array.pxi:1521, in pyarrow.lib.Array.to_pylist()

File ~/opt/anaconda3/envs/fts/lib/python3.10/site-packages/pyarrow/scalar.pxi:632, in pyarrow.lib.StringScalar.as_py()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 0: invalid continuation byte
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caleboverman** [comment]
@gforsyth 
1. I can't share the exact file unfortunately. It's rather complex so I'm trying to narrow it down to a smaller example that I'm able to share.
2. `pandas.read_parquet` is able to read the file without issue.

**Comment by caleboverman** [comment]
@gforsyth I have a file I'm able to share but would still prefer to not post publicly. Is there a way I can send it to you besides posting it here?

**Comment by gforsyth** [comment]
Hey @caleboverman -- sorry for the delay -- most of the maintainers were at SciPy this last week and a bit disconnected.
If you can join the Matrix channel (https://matrix.to/#/#ibis-dev_Lobby:gitter.im) then we can coordinate a file transfer there.

**Comment by lostmygithubaccount** [comment]
hello, if you're not comfortable sharing the file on GitHub or the Matrix channel feel free to email me at cody@voltrondata.com and I'll share it with the rest of the team! have a reproduction will helps us debug and hopefully fix this issue much quicker than without

**Comment by gforsyth** [comment]
Hey @caleboverman -- thanks for sharing the file.

Can you provide a code snippet using that file that errors?  Is this only an issue when the file is being pulled from S3?

**Comment by gforsyth** [comment]
Hey @caleboverman -- just wanted to update here -- I put the file in a (private) bucket and was able to load it into DuckDB via `pyarrow.dataset` using Ibis and then dumping it to a dataframe without issue.

Not sure what else there is for us to try on our end, but if you have a failing code sample that uses that file (or another file) we are happy to take a look.

**Comment by caleboverman** [comment]
@gforsyth sorry for the delay

Thought this might be environment related so I created a clean conda environment. Interestingly, this worked against the file I sent you. I went through my old environment and updated packages but continued to see the same issue.

Flipping back to the clean environment I ran the code sample in a shell to read the file and it failed this time. Immediately following that, in the same shell, I ran it again and it worked. I'm kinda at a loss as to what might be going on here.

I've attached a conda environment file and a screen shot of my shell session showing the read fail and then succeed upon running again.
![image](https://github.com/ibis-project/ibis/assets/6807872/890d32c2-c655-4cbf-967c-e2dfef401f2a)
[ibis_env.yml.txt](https://github.com/ibis-project/ibis/files/12187751/ibis_env.yml.txt)

**Comment by gforsyth** [comment]
Hey @caleboverman -- what a horrible bug!

I have reproduced this just now -- but it is highly inconsistent and has only failed the one time during about 20 runs:

```
Traceback (most recent call last):
  File "/home/gil/github.com/ibis-project/ibis/s3_dataset_to_pandas.py", line 20, in <module>
    df = t.to_pandas()
         ^^^^^^^^^^^^^
  File "/home/gil/github.com/ibis-project/ibis/ibis/expr/types/relations.py", line 2753, in to_pandas
    return self.execute(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gil/github.com/ibis-project/ibis/ibis/expr/types/core.py", line 294, in execute
    return self._find_backend(use_default=True).execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gil/github.com/ibis-project/ibis/ibis/backends/base/sql/__init__.py", line 263, in execute
    result = self.fetch_from_cursor(cursor, schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gil/github.com/ibis-project/ibis/ibis/backends/duckdb/__init__.py", line 872, in fetch_from_cursor
    {
  File "/home/gil/github.com/ibis-project/ibis/ibis/backends/duckdb/__init__.py", line 882, in <dictcomp>
    else col.to_pandas(timestamp_as_object=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/array.pxi", line 837, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/table.pxi", line 472, in pyarrow.lib.ChunkedArray._to_pandas
  File "pyarrow/array.pxi", line 1655, in pyarrow.lib._array_like_to_pandas
  File "pyarrow/error.pxi", line 138, in pyarrow.lib.check_status
i$s��w�`�^�P failedception: Unknown error: Wrapping 
```

The last line gets mangled by my shell, but it is also a `ArrowException`

**Comment by gforsyth** [comment]
Ok, I've got in in a debugger -- this _does_ look pretty funky.  

```
ipdb> p col
<pyarrow.lib.ChunkedArray object at 0x7f05878593a0>
[
  [
    "cc3259aa-89ee-441d-b0ac-e9e570bbd0c2",
    "dcb37e18-b2d9-4294-8dd9-2164298e01a5",
    "dcb37e18-b2d9-4294-8dd9-2164298e01a5",
    "56c5bf05-2ac4-4fd7-90a5-08d07f1f5c9b",
    "2238e751-a3f7-40e5-adcd-d7023cf635b5",
    ...
    "��Ά���$e",
    "0�����t:1�<",
    "0�����t:1�<",
    "��Ά���$e",
    "��Ά���$e"
  ]
]
```

And I've confirmed that the Arrow table that we get from the DuckDB cursor is corrupted (or whatever this is)

```
ipdb> p table
pyarrow.Table
field1: string
field2: string
----
field1: [["cc3259aa-89ee-441d-b0ac-e9e570bbd0c2","dcb37e18-b2d9-4294-8dd9-2164298e01a5","dcb37e18-b2d9-4294-8dd9-2164298e01a5","56c5bf05-2ac4-4fd7-90a5-08d07f1f5c9b","2238e751-a3f7-40e5-adcd-d7023cf635b5",...,"��Ά���$e","0�����t:1�<","0�����t:1�<","��Ά���$e","��Ά���$e"]]
field2: [["301727","547656","547656","646033","857526",...,"144279","110775","110775","144279","144279"]]
```

**Comment by gforsyth** [comment]
Hey @caleboverman -- I can reproduce your failure using only DuckDB and PyArrow, so I think this is outside of our purview

Note that this script failed for me with the following versions and with pyarrow 10, 11, and 12

python 3.10
duckdb 0.8.1
duckdb_engine 0.9.2



```python
import pyarrow.dataset as ds
from pyarrow.fs import S3FileSystem
import duckdb

s3filesystem = S3FileSystem(
    access_key="...",
    secret_key="...",
    session_token="...",
)

d = ds.dataset(
    source="ibis-testing/ibis_test.parquet",
    format="parquet",
    partitioning="hive",
    filesystem=s3filesystem,
)

con = duckdb.connect()
con.register(d, table_name="dataset")
con.register("dataset", d)
cursor = con.execute("SELECT * FROM dataset;")
arrow_table = cursor.fetch_arrow_table()
arrow_table
arrow_table.to_pandas()
```

```sh
Traceback (most recent call last):
  File "/home/gil/github.com/ibis-project/ibis/s3_dataset_to_pandas.py", line 21, in <module>
    df = arrow_table.to_pandas()
  File "pyarrow/array.pxi", line 837, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/table.pxi", line 4114, in pyarrow.lib.Table._to_pandas
  File "/home/gil/mambaforge/envs/ibis6pyarrow12/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 820, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "/home/gil/mambaforge/envs/ibis6pyarrow12/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 1168, in _table_to_blocks
    result = pa.lib.table_to_blocks(options, block_table, categories,
  File "pyarrow/table.pxi", line 2771, in pyarrow.lib.table_to_blocks
  File "pyarrow/error.pxi", line 138, in pyarrow.lib.check_status
pyarrow.lib.ArrowException: Unknown error: Wrapping �c��ͳ� failed
Failed on 0th iteration
```

**Comment by caleboverman** [comment]
@gforsyth appreciate the work to investigate this. Confirming that I can replicate the error with your code.

Am I correct in thinking this looks to be a `pyarrow` issue? Do you need me to log a bug with there or have you already done that?

**Comment by gforsyth** [comment]
I suspect it's actually a DuckDB issue -- I haven't opened an upstream issue yet -- I want to try to confirm which project is the main culprit here.

**Comment by gforsyth** [comment]
Hey @caleboverman -- I cannot reproduce this using only `pyarrow`, so I think it's probably DuckDB that's at the root of this issue.

I suspect it has something to do with the parquet files having a lot of row groups (the file you sent over has 51 row groups) and so allows for more parallel reads of the individual row groups.  There seems to be some part of that parallel read that gets screwed up every once in a while.

**Comment by gforsyth** [comment]
I think you should open an issue upstream with DuckDB and link back to this issue.  Feel free to ping me in that issue, too, and I can provide additional context as needed.

**Comment by cpcloud** [comment]
Thanks for powering through this @caleboverman and @gforsyth!

**Comment by caleboverman** [comment]
@cpcloud @gforsyth I've confirmed the fix upstream https://github.com/duckdb/duckdb/issues/8440

**Comment by cpcloud** [comment]
Thank you!
