### ISSUE TITLE
fillna error when passing a DoubleScalar expression (with SQLite)

### ISSUE THREAD

**Issue by ogrisel** [ibis-project/ibis#685]
``` python
import ibis

con = ibis.sqlite.connect('crunchbase.db')
c = con.table('companies')
age = 2015 - c.founded_at.cast('timestamp').year()
age.fillna(age.mean()).execute()
```

yields:

```
Traceback (most recent call last):
  File "<ipython-input-137-9ab0f904ee16>", line 6, in <module>
    age.fillna(age.mean()).execute()
  File "/Users/ogrisel/code/ibis/ibis/expr/types.py", line 132, in execute
    return execute(self, limit=limit, async=async)
  File "/Users/ogrisel/code/ibis/ibis/client.py", line 311, in execute
    return backend.execute(expr, limit=limit, async=async)
  File "/Users/ogrisel/code/ibis/ibis/client.py", line 230, in execute
    return self._execute_query(ast.queries[0], async=async)
  File "/Users/ogrisel/code/ibis/ibis/client.py", line 234, in _execute_query
    return klass(self, ddl).execute()
  File "/Users/ogrisel/code/ibis/ibis/client.py", line 41, in __init__
    self.compiled_ddl = ddl.compile()
  File "/Users/ogrisel/code/ibis/ibis/sql/alchemy.py", line 574, in compile
    frag = step(frag)
  File "/Users/ogrisel/code/ibis/ibis/sql/alchemy.py", line 599, in _add_select
    arg = self._translate(expr, named=True)
  File "/Users/ogrisel/code/ibis/ibis/sql/compiler.py", line 1320, in _translate
    return translator.get_result()
  File "/Users/ogrisel/code/ibis/ibis/sql/compiler.py", line 1120, in get_result
    translated = self.translate(self.expr)
  File "/Users/ogrisel/code/ibis/ibis/sql/compiler.py", line 1159, in translate
    return formatter(self, expr)
  File "/Users/ogrisel/code/ibis/ibis/sql/alchemy.py", line 123, in formatter
    return _varargs_call(sa_func, t, expr)
  File "/Users/ogrisel/code/ibis/ibis/sql/alchemy.py", line 138, in _varargs_call
    trans_args = [t.translate(arg) for arg in op.args]
  File "/Users/ogrisel/code/ibis/ibis/sql/alchemy.py", line 138, in <listcomp>
    trans_args = [t.translate(arg) for arg in op.args]
  File "/Users/ogrisel/code/ibis/ibis/sql/compiler.py", line 1162, in translate
    .format(type(op)))
TranslationError: No translator rule for <class 'ibis.expr.operations.WindowOp'>
```

while computing the mean eagerly works:

``` python
>>> age.fillna(age.mean().execute()).execute().head(5)
0    7.81548
1    1.00000
2    3.00000
3    7.81548
4    3.00000
Name: tmp, dtype: float64
```

**Comment by wesm** [comment]
Yes — the SQLite backend needs to workaround the lack of window functions using joins on inline views containing the aggregations. It's a bit complicated because aggregates are being converted to window operations at the DSL stage, which is not correct. The window function conversion should happen during the Ibis AST -> SQL AST translation step (see `ibis/sql/compiler.py`).

**Comment by cpcloud** [comment]
Just to expand a bit here: this operation is tricky because the way you combine reduction operations and scalar (column) operations in SQL is not intuitive if you're used to operating with DataFrames or numpy arrays.

To do something as simple as subtract the mean of a column from itself actually requires a window function, or some equivalent.

In pandas it's trivial:

```python
t.column - t.column.mean()
```

In SQL you often use a window function:

```sql
SELECT column - AVG(column) OVER ()
FROM t
```
But not all flavors of SQL support window functions, so you actually need to perform a join to achieve parity:

```
WITH mean AS (
  SELECT AVG(column) AS mean
  FROM t
)
SELECT
  column - mean.mean
FROM t, mean
```
As luck would have it, SQLite doesn't support window functions and while this particular case may seem pretty easy to implement, we would have to support window functions in a very generic way including support for partitioning, ordering, and window size specification. All of these factor make it much more time consuming to fix without adding lots of hacks.

**Comment by cpcloud** [comment]
Window functions in SQLite work out of the box:

```
In [18]: con = ibis.sqlite.connect("ci/ibis-testing-data/ibis_testing.db")

In [19]: t = con.table("diamonds")

In [20]: (t.price - t.price.mean()).execute()
Out[20]:
0      -3606.799722
1      -3606.799722
2      -3605.799722
3      -3598.799722
4      -3597.799722
           ...
9995     771.200278
9996     771.200278
9997     771.200278
9998     771.200278
9999     771.200278
Name: tmp, Length: 10000, dtype: float64
```
