### ISSUE TITLE
bug: ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#6972]
### What happened?

pandas 2.1.0 release breaks DuckDB and thus Ibis w/ the default backend:

```
In [1]: import duckdb

In [2]: duckdb.execute("select ? as a", (1,)).arrow()
---------------------------------------------------------------------------
InvalidInputException                     Traceback (most recent call last)
Cell In[2], line 1
----> 1 duckdb.execute("select ? as a", (1,)).arrow()

InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'
```

also seen in CI here: https://github.com/lostmygithubaccount/ibis-analytics/actions/runs/6026645436/job/16350066237

already reported upstream here: https://github.com/duckdb/duckdb/issues/8735

opening this for anyone running into it w/ Ibis. there's already a fix being worked on though overall this is something that needs an upstream fix 

### What version of ibis are you using?

latest

### What backend(s) are you using, if any?

duckdb

### Relevant log output

```sh
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/duckdb_engine/__init__.py", line 144, in execute
    self.__c.execute(statement, parameters)
duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/ibis-analytics/ibis-analytics/transform.py", line 39, in <module>
    stars = clean_data(con.read_json("data/github/ibis-project/ibis/stargazers.*.json"))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/duckdb/__init__.py", line 400, in read_json
    return self.table(table_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 614, in table
    sqla_table = self._get_sqla_table(name, schema=schema)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/duckdb/__init__.py", line 1008, in _get_sqla_table
    return super()._get_sqla_table(name, schema, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 482, in _get_sqla_table
    table = sa.Table(
            ^^^^^^^^^
  File "<string>", line 2, in __new__
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 437, in __new__
    return cls._new(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 491, in _new
    with util.safe_reraise():
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 487, in _new
    table.__init__(name, metadata, *args, _no_init=False, **kw)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 867, in __init__
    self._autoload(
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 899, in _autoload
    conn_insp.reflect_table(
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 1526, in reflect_table
    _reflect_info = self._get_reflection_info(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 2008, in _get_reflection_info
    columns=run(
            ^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 1994, in run
    res = meth(filter_names=_fn, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 922, in get_multi_columns
    self.dialect.get_multi_columns(
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/duckdb_engine/__init__.py", line 337, in get_multi_columns
    rows = list(connection.execute(query, params).mappings())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/duckdb_engine/__init__.py", line 144, in execute
    self.__c.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (duckdb.InvalidInputException) Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
`clickhouse_driver` is also using APIs that were removed in pandas 2.1.0.

I'm looking into working around that for the one place we're using that bit.

**Comment by cpcloud** [comment]
Closing, this has been fixed upstream in https://github.com/duckdb/duckdb/issues/8735
