### ISSUE TITLE
bug: maximum recursion depth with join operation

### ISSUE THREAD

**Issue by nehanene15** [ibis-project/ibis#7124]
### What happened?

We're seeing a `RecursionError: maximum recursion depth exceeded while calling a Python object` when running a JOIN: `source_difference = source.join(differences, join_keys, how="outer")`
Both 'source' and 'differences' are pandas.Table()s with many columns (~120).

We don't hit this error with smaller, less wide tables. I've provided a abridged version of the stack trace below - it does look like there is a cyclical portion of the code when testing if left and right tables have a common parent expr [here](https://github.com/ibis-project/ibis/blob/5.1.0/ibis/expr/operations/relations.py#L178).

Trying to understand if this is a Python limitation due to how wide the table is, or an Ibis bug. Appreciate the help! 

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

Pandas

### Relevant log output

```sh
Traceback (most recent call last):
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 210, in __cached_equals__
    result = self.__cache__[key]
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/caching.py", line 46, in __getitem__
    value, _ = self._data[identifiers]
KeyError: (139856786236240, 139856788868000)

During handling of the above exception, another exception occurred:
...
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 210, in __cached_equals__
    result = self.__cache__[key]
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/caching.py", line 46, in __getitem__
    value, _ = self._data[identifiers]
KeyError: (139856787188608, 139856789577136)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/x/home/user/new_fl/dvt4/bin/data-validation", line 11, in <module>
    load_entry_point('google-pso-data-validator==4.1.0', 'console_scripts', 'data-validation')()
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/data_validation/__main__.py", line 581, in main
    run_validation_configs(args)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/data_validation/__main__.py", line 551, in run_validation_configs
    config_runner(args)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/data_validation/__main__.py", line 304, in config_runner
    run_validations(args, config_managers)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/data_validation/__main__.py", line 478, in run_validations
    run_validation(
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/data_validation/__main__.py", line 461, in run_validation
    validator.execute()
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/data_validation/data_validation.py", line 96, in execute
    result_df = self._execute_validation(
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/data_validation/data_validation.py", line 314, in _execute_validation
    result_df = combiner.generate_report(
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/data_validation/combiner.py", line 83, in generate_report
    joined = _join_pivots(source_pivot, target_pivot, differences_pivot, join_on_fields)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/data_validation/combiner.py", line 317, in _join_pivots
    source_difference = source.join(differences, join_keys, how="outer")[
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/expr/types/relations.py", line 2497, in join
    expr = klass(left, right, predicates).to_expr()
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 25, in __call__
    return cls.__create__(*args, **kwargs)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 99, in __create__
    return super().__create__(**kwargs)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 33, in __create__
    return type.__call__(cls, *args, **kwargs)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/expr/operations/relations.py", line 178, in __init__
    if left.equals(right):
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/expr/operations/core.py", line 24, in equals
    return self.__cached_equals__(other)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 212, in __cached_equals__
    result = self.__equals__(other)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 239, in __equals__
    return self.__args__ == other.__args__
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 187, in __eq__
    return self.__cached_equals__(other)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 212, in __cached_equals__
    result = self.__equals__(other)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 239, in __equals__
    return self.__args__ == other.__args__
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 187, in __eq__
    return self.__cached_equals__(other)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 212, in __cached_equals__
    result = self.__equals__(other)
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 239, in __equals__
    return self.__args__ == other.__args__
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 187, in __eq__
    return self.__cached_equals__(other)
File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/grounds.py", line 210, in __cached_equals__
    result = self.__cache__[key]
  File "/x/home/user/new_fl/dvt4/lib/python3.8/site-packages/ibis/common/caching.py", line 45, in __getitem__
    identifiers = tuple(id(item) for item in key)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the report!

Can you show the code that produces the exception?

It'll be easier to write a regression test if we can get the exact case that raises the exception.

**Comment by nehanene15** [comment]
This is the line that generates the exception: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/47154b4139bf22358359c53fe25bbce44745589f/data_validation/combiner.py#L321

And this is where Pandas tables are instantiated before it gets to the combiner.py: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/47154b4139bf22358359c53fe25bbce44745589f/data_validation/data_validation.py#L339

For context, the source and target are SQL query results and the [combiner.generate_report()](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/47154b4139bf22358359c53fe25bbce44745589f/data_validation/combiner.py#L34) aims to find the differences between the two results, if any, for data validation.

**Comment by cpcloud** [comment]
Any chance you could dump a parquet file of the left and right tables somewhere?

**Comment by nehanene15** [comment]
GitHub won't allow me to upload Parquet, but I'll upload the CSVs of the source and differences. We're running `source_difference = source.join(differences, join_keys, how="outer")`

[source_pivot.csv](https://github.com/ibis-project/ibis/files/12580336/source_pivot.csv)
[differences_pivot.csv](https://github.com/ibis-project/ibis/files/12580340/differences_pivot.csv)

**Comment by kszucs** [comment]
Hi @nehanene15!

Could you please try out with the following patch applied (I assume you are using ibis 6.2):

```diff
diff --git a/ibis/common/grounds.py b/ibis/common/grounds.py
index 394bc4ccf..6f5bcd184 100644
--- a/ibis/common/grounds.py
+++ b/ibis/common/grounds.py
@@ -203,6 +203,8 @@ class Comparable(Base):
         if type(self) is not type(other):
             return False

+        return self.__equals__(other)
+
         # reduce space required for commutative operation
         if id(self) < id(other):
             key = (self, other)
```

This way we turn of an optimization which maintains a global cache for operation node equality checks. If it keeps failing we could get a clearer traceback.

**Comment by kszucs** [comment]
Another option would be to pickle the `left` and `right` arguments in case of a recursion error using the following snippet:

```diff
diff --git a/ibis/expr/operations/relations.py b/ibis/expr/operations/relations.py
index c444a7d88..a12ded3b0 100644
--- a/ibis/expr/operations/relations.py
+++ b/ibis/expr/operations/relations.py
@@ -220,6 +220,15 @@ class Join(TableNode):
             for pred in util.promote_list(predicates)
         ]

+        try:
+            left.equals(right)
+        except RecursionError:
+            import pickle
+            with open('left.pickle', 'wb') as fp:
+                pickle.dump(left, fp)
+            with open('right.pickle', 'wb') as fp:
+                pickle.dump(right, fp)
+
         if left.equals(right):
             # GH #667: If left and right table have a common parent expression,
             # e.g. they have different filters, we need to add a self-reference
```

Then I could try to load the two objects to reproduce the error.

**Comment by cpcloud** [comment]
@nehanene15 Can you show the value of `join_keys`?

**Comment by cpcloud** [comment]
I am not able to get the following test to fail:

```python
def test_large_join():
    source = pd.read_csv(
        "https://github.com/ibis-project/ibis/files/12580336/source_pivot.csv",
        index_col=0,
    )
    diffs = pd.read_csv(
        "https://github.com/ibis-project/ibis/files/12580340/differences_pivot.csv",
        index_col=0,
    )
    con = ibis.pandas.connect({"source": source, "diffs": diffs})
    source = con.tables.source
    diffs = con.tables.diffs

    join_keys = set(source.columns) & set(diffs.columns)
    join = source.join(diffs, join_keys, how="outer").select(
        [source[key] for key in join_keys]
        + [
            source["validation_type"],
            source["aggregation_type"],
            source["table_name"],
            source["column_name"],
            source["primary_keys"],
            source["num_random_rows"],
            source["agg_value"],
            diffs["difference"],
            diffs["pct_difference"],
            diffs["pct_threshold"],
            diffs["validation_status"],
        ],
    )
    df = join.execute()
    assert not df.empty
```

@nehanene15 Any ideas?

**Comment by nehanene15** [comment]
Hmm.. the join_keys value is `('validation_name',)`. 

@kszucs When I try the patch, I get a similar cyclical error:
```
  File "/Users/nehanene/Projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/common/grounds.py", line 203, in __cached_equals__
    return self.__equals__(other)
  File "/Users/nehanene/Projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/common/grounds.py", line 241, in __equals__
    return self.__args__ == other.__args__
  File "/Users/nehanene/Projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/common/grounds.py", line 187, in __eq__
    return self.__cached_equals__(other)
  File "/Users/nehanene/Projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/common/grounds.py", line 203, in __cached_equals__
    return self.__equals__(other)
  File "/Users/nehanene/Projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/common/grounds.py", line 241, in __equals__
    return self.__args__ == other.__args__
  File "/Users/nehanene/Projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/common/grounds.py", line 187, in __eq__
    return self.__cached_equals__(other)
  File "/Users/nehanene/Projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/common/grounds.py", line 203, in __cached_equals__
    return self.__equals__(other)
  File "/Users/nehanene/Projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/common/grounds.py", line 241, in __equals__
    return self.__args__ == other.__args__
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by cpcloud** [comment]
Ah, yeah it looks like there's around 370 tables in the mix there. There's nothing in principle preventing that, but it seems like it's related.

If you can pickle the unbound expression and dump that somewhere then we can probably reproduce it.

In the meantime, I will try to construct a big union of tables to see if I can reproduce this.

**Comment by cpcloud** [comment]
Ok, I can reproduce it with this

```python
def test_large_join():
    source = pd.read_csv(
        "https://github.com/ibis-project/ibis/files/12580336/source_pivot.csv",
        index_col=0,
    )
    diffs = pd.read_csv(
        "https://github.com/ibis-project/ibis/files/12580340/differences_pivot.csv",
        index_col=0,
    )
    con = ibis.pandas.connect({"source": source, "diffs": diffs})
    n = 200
    source = ibis.union(*[con.tables.source for _ in range(n)])
    diffs = ibis.union(*[con.tables.diffs for _ in range(n)])

    join_keys = set(source.columns) & set(diffs.columns)
    join = source.join(diffs, join_keys, how="outer").select(
        [source[key] for key in join_keys]
        + [
            source["validation_type"],
            source["aggregation_type"],
            source["table_name"],
            source["column_name"],
            source["primary_keys"],
            source["num_random_rows"],
            source["agg_value"],
            diffs["difference"],
            diffs["pct_difference"],
            diffs["pct_threshold"],
            diffs["validation_status"],
        ],
    )
    df = join.execute()
    assert not df.empty
```

**Comment by nehanene15** [comment]
It works if I execute the large expr before doing the join!

In this case differences_pivot and source_pivot are the large expressions with around 495 tables in the mix.
Working code:
```
differences_df = client.execute(differences_pivot)
source_df = client.execute(source_pivot)

con = ibis.pandas.connect({"source": source, "differences": differences, "target": target})
source = con.tables.source
differences = con.tables.differences

source_difference = source.join(differences, join_keys, how="outer")[
        [source[field] for field in join_keys]
        + [
            source["validation_type"],
            source["aggregation_type"],
            source["table_name"],
            source["column_name"],
            source["primary_keys"],
            source["num_random_rows"],
            source["agg_value"],
            differences["difference"],
            differences["pct_difference"],
            differences["pct_threshold"],
            differences["validation_status"],
        ]
    ]
```

**Comment by cpcloud** [comment]
It's failing for the same reason in that test, but at a slightly different location (the `execute` call)

**Comment by nehanene15** [comment]
I see. Seems like it's best practice to execute the Ibis expr beforehand to avoid the 300+ table union/join so I'll update our code to reflect that if you agree.

**Comment by cpcloud** [comment]
@kszucs I suspect we can construct a failing example without joins.

I suspect that there may be some `property`s we should turn into `attribute`s in a few places, to avoid huge traversals, for example the `schema` attribute of `Union`s.

We can probably also avoid storing a huge tree for set operations

**Comment by cpcloud** [comment]
@nehanene15 I think for your case it's a viable workaround, but I don't think it's best practice 😄, I think it's a bug in ibis that we will try to address.

**Comment by kszucs** [comment]
> I suspect that there may be some `property`s we should turn into `attribute`s in a few places, to avoid huge traversals, for example the `schema` attribute of `Union`s.

I was thinking of the same, I'm not sure how could we prevent call stacks like this, but we can certainly "delay" their occurrence.

**Comment by cpcloud** [comment]
Another thing that may help decrease call stack size is changing the representation of SetOp to be variadic.

**Comment by cpcloud** [comment]
@nehanene15 Can you try your code again against #7148? That should give you some breathing room for huge unions, though see the PR description (points 3 and 4) that might explain any new issues that look similar 😅

**Comment by cpcloud** [comment]
@nehanene15 You should have plenty of room for those big unions now :)

If anything else pops up don't hesitate to open another issue!
