### ISSUE TITLE
bug: Specifying the database and schema for a table does not work in Trino

### ISSUE THREAD

**Issue by aalbu** [ibis-project/ibis#7354]
### What happened?

Creating a dataframe from a "fully quallified" table name caused an exception:
```
connection = ibis.trino.connect(user='trino', host='localhost', port=8080)
countries = connection.table(name='nation', database='tpch', schema='tiny')
```

### What version of ibis are you using?

7.0.0

### What backend(s) are you using, if any?

Trino

### Relevant log output

```sh
/Users/alex.albu/Library/Caches/pypoetry/virtualenvs/pydantic-demo-0yMeIGuA-py3.11/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py:623: FutureWarning: `BaseBackend.database` is deprecated; use equivalent methods in the backend
  return self.database(name=database).table(name=name, schema=schema)
Traceback (most recent call last):
  File "/Users/alex.albu/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.9921.47/IntelliJ IDEA.app.plugins/python/helpers/pydev/pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex.albu/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.9921.47/IntelliJ IDEA.app.plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/alex.albu/tmp/pydantic-demo/pydantic_demo/ibis_test.py", line 6, in <module>
    countries = connection.table(name='nation', database='tpch', schema='tiny')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex.albu/Library/Caches/pypoetry/virtualenvs/pydantic-demo-0yMeIGuA-py3.11/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 623, in table
    return self.database(name=database).table(name=name, schema=schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Database.table() got an unexpected keyword argument 'schema'
python-BaseException
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @aalbu!

Thanks for the issue.

Can you try this instead?

```
connection = ibis.trino.connect(database=..., schema=..., user='trino', host='localhost', port=8080)
countries = connection.table(name='nation', schema='tpch.tiny')
```

I found another issue while testing this 😅. In short, you need to specify the catalog and schema in the connection.

We're working on making the database/schema parameters make a bit more sense. They are kind of all over the place at the moment.

**Comment by aalbu** [comment]
Yes, that works:
```
connection = ibis.trino.connect(user='sql', host='localhost', port=8080, database='tpch', schema='sf100')
countries = connection.table(name='nation', schema='tiny')
```
However this workaround does not work when trying to query across catalogs (databases) because as soon as you specify a database that is different that the connection one, you get the error above.  And federating datasources is something Trino shines at.

**Comment by aalbu** [comment]
Sorry, I didn't notice you had a qualified schema name.  That works, indeed.
