### ISSUE TITLE
bug: trino.backend con.table() won't accept schema and database

### ISSUE THREAD

**Issue by wolf-sigma** [ibis-project/ibis#7398]
### What happened?

The Trino backend (possibly other Alchemy-based ones) won't accept a schema and database defined simultaneously. This is useful when trying to switch between catalogs & schemas for different dataframes.

Repro steps:

```python
con = ibis.connect("trino://user:pass@my.url", port 443, http_scheme="https" ...) # Note no database or catalog defined
con.table("my_table", database="my_cat", schema="my_schema")
```

I ultimately worked around this by putting the catalog name in the schema:

```python
con.table("my_table", schema="my_cat.my_schema")
```

However, if an initial schema isn't defined a different error occurs (likely a second bug)

```
Traceback (most recent call last):
 File "/Users/--redacted--/Projects/ibis-testing/python_dashboard/my.py", line 29, in <module>
    query_history = con.table('--redacted--', schema=--redacted--.--redacted--").select("--redacted--", "--redacted--", "--redacted--", "--redacted--", "--redacted--")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/--redacted--/Projects/ibis-testing/.venv/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 625, in table
    sqla_table = self._get_sqla_table(name, schema=schema)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/--redacted--/Projects/ibis-testing/.venv/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 945, in _get_sqla_table
    with self._use_schema(ident, current_db, current_schema):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/--redacted--/Projects/ibis-testing/.venv/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 924, in _use_schema
    f"{use_prefix} {self._quote(current_db)}.{self._quote(current_schema)}"
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/--redacted--/Projects/ibis-testing/.venv/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 790, in _quote
    return preparer.quote(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/--redacted--/Projects/ibis-testing/.venv/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 7416, in quote
    if self._requires_quotes(ident):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/--redacted--/Projects/ibis-testing/.venv/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 7322, in _requires_quotes
    lc_value = value.lower()
               ^^^^^^^^^^^
```

### What version of ibis are you using?

7.0.0

### What backend(s) are you using, if any?

Trino

### Relevant log output

```sh
Open the following URL in browser for the external authentication:
--redacted--
/Users/--redacted--/Projects/ibis-testing/.venv/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py:623: FutureWarning: `BaseBackend.database` is deprecated; use equivalent methods in the backend
  return self.database(name=database).table(name=name, schema=schema)
Traceback (most recent call last):
  File "/Users/--redacted--/Projects/ibis-testing/python_dashboard/ibisDFs.py", line 26, in <module>
    accounts_latest = con.table('accounts_latest', database='crdb_scrape_prod', schema='data')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/--redacted--/Projects/ibis-testing/.venv/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 623, in table
    return self.database(name=database).table(name=name, schema=schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Database.table() got an unexpected keyword argument 'schema'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue @wolf-sigma!

The first issue is definitely something we'll fix, it's currently a rough edge with the sqlalchemy backends that support cross-database/schema table references. Glad you were able to workaround it.

The second bug was fixed in #7380 and will show up in a pre-release on PyPI this weekend if you'd like to test it out:

```
In [1]: from ibis.interactive import *

In [2]: con = ibis.trino.connect(database=None, schema=None)

In [3]: t = con.table("orders", schema="tpch.sf1")

In [4]: t.count()
Out[4]: 1500000
```
