### ISSUE TITLE
bug: DuckDB `IntervalValue.days` is broken

### ISSUE THREAD

**Issue by judahrand** [ibis-project/ibis#7502]
### What happened?

I would expect `IntervalValue.days` to return an integer which is the number of days in the interval.

### What version of ibis are you using?

`ca97dfba1dca428456a8c28b1c2e3b3692ec6547`

### What backend(s) are you using, if any?

DuckDB

### Relevant log output

```sh
import ibis
from ibis import _

conn = ibis.connect('duckdb://:memory:')

t = conn.sql("""
    SELECT
        CAST('2022-11-06 12:30:12' AS TIMESTAMP) AS ts1,
        CAST('2023-10-04 16:20:42' AS TIMESTAMP) AS ts2
    """,
).mutate(
    days=(_.ts2 - _.ts1).days,
).execute()


```
Traceback (most recent call last):
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/duckdb_engine/__init__.py", line 144, in execute
    self.__c.execute(statement, parameters)
duckdb.BinderException: Binder Error: No function matches the given name and argument types '*(DOUBLE, INTERVAL)'. You might need to add explicit type casts.
        Candidate functions:
        *(TINYINT, TINYINT) -> TINYINT
        *(SMALLINT, SMALLINT) -> SMALLINT
        *(INTEGER, INTEGER) -> INTEGER
        *(BIGINT, BIGINT) -> BIGINT
        *(HUGEINT, HUGEINT) -> HUGEINT
        *(FLOAT, FLOAT) -> FLOAT
        *(DOUBLE, DOUBLE) -> DOUBLE
        *(DECIMAL, DECIMAL) -> DECIMAL
        *(UTINYINT, UTINYINT) -> UTINYINT
        *(USMALLINT, USMALLINT) -> USMALLINT
        *(UINTEGER, UINTEGER) -> UINTEGER
        *(UBIGINT, UBIGINT) -> UBIGINT
        *(INTERVAL, BIGINT) -> INTERVAL
        *(BIGINT, INTERVAL) -> INTERVAL

LINE 1: ...0.ts1 AS BIGINT) / CAST(? AS INTEGER)) * INTERVAL '1 day' AS days
                                                  ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<redacted>/reproduce.py", line 14, in <module>
    ).execute()
      ^^^^^^^^^
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/ibis/expr/types/core.py", line 322, in execute
    return self._find_backend(use_default=True).execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/ibis/backends/base/sql/__init__.py", line 336, in execute
    with self._safe_raw_sql(sql, **kwargs) as cursor:
  File "/Users/Judah.Rand/.pyenv/versions/3.11.5/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 196, in _safe_raw_sql
    yield con.execute(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/<redacted>/.venv/lib/python3.11/site-packages/duckdb_engine/__init__.py", line 144, in execute
    self.__c.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (duckdb.BinderException) Binder Error: No function matches the given name and argument types '*(DOUBLE, INTERVAL)'. You might need to add explicit type casts.
        Candidate functions:
        *(TINYINT, TINYINT) -> TINYINT
        *(SMALLINT, SMALLINT) -> SMALLINT
        *(INTEGER, INTEGER) -> INTEGER
        *(BIGINT, BIGINT) -> BIGINT
        *(HUGEINT, HUGEINT) -> HUGEINT
        *(FLOAT, FLOAT) -> FLOAT
        *(DOUBLE, DOUBLE) -> DOUBLE
        *(DECIMAL, DECIMAL) -> DECIMAL
        *(UTINYINT, UTINYINT) -> UTINYINT
        *(USMALLINT, USMALLINT) -> USMALLINT
        *(UINTEGER, UINTEGER) -> UINTEGER
        *(UBIGINT, UBIGINT) -> UBIGINT
        *(INTERVAL, BIGINT) -> INTERVAL
        *(BIGINT, INTERVAL) -> INTERVAL

LINE 1: ...0.ts1 AS BIGINT) / CAST(? AS INTEGER)) * INTERVAL '1 day' AS days
                                                  ^
[SQL: SELECT t0.ts1, t0.ts2, floor(CAST(t0.ts2 - t0.ts1 AS BIGINT) / CAST(? AS INTEGER)) * INTERVAL '1 day' AS days
FROM (
    SELECT
        CAST('2022-11-06 12:30:12' AS TIMESTAMP) AS ts1,
        CAST('2023-10-04 16:20:42' AS TIMESTAMP) AS ts2
    ) AS t0]
[parameters: (86400,)]
(Background on this error at: https://sqlalche.me/e/14/f405)
```
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
We are likely going to remove the unit accessors on `IntervalValue`, because backends are all over the place with respect to whether such an operation is well-defined and implemented.

**Comment by judahrand** [comment]
> @judahrand Thanks for the report!
> 
> Can you try using the [`delta` method](https://ibis-project.org/reference/expression-temporal.html#ibis.expr.types.temporal.TimestampValue.delta) for your use case? The `delta` method should be preferred when computing an integer number of units between two temporal types:
> 
> ```python
> import ibis
> from ibis import _
> 
> conn = ibis.connect('duckdb://:memory:')
> 
> t = conn.sql("""
>     SELECT
>         CAST('2022-11-06 12:30:12' AS TIMESTAMP) AS ts1,
>         CAST('2023-10-04 16:20:42' AS TIMESTAMP) AS ts2
>     """,
> ).mutate(
>     days=_.ts2.delta(_.ts1, "day")
> ).execute()
> 
> print(t)
> ```
> 
> Running that as a script I get:
> 
> ```
>                   ts1                 ts2  days
> 0 2022-11-06 12:30:12 2023-10-04 16:20:42   332
> ```

Yes, I discovered this later as it does get to the number I'm after. I suppose it isn't quite as flexible as the unit accessors, however. Imagine that I want to split the days and hours into two separate columns. Using the `delta` method I end up needing to express the subtraction twice (not as 'DRY' as the unit accessors).

**Comment by cpcloud** [comment]
> Using the delta method I end up needing to express the subtraction twice (not as 'DRY' as the unit accessors).

Indeed, it's not as nice of an API. Happy to discuss other APIs that might DRY things up a bit.

Perhaps something like this?

```
d = t.a.delta(t.b)  # not an expression yet, or perhaps a struct that contains all available deltas for the type
d.days  # effectively "filling in" the unit
d.hours
...
```
