### ISSUE TITLE
bug(duckdb): backend doesn't support time-based range windows for aggregation

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis#7598]
### What happened?

```python
>>> import pandas as pd
>>> quotes = pd.DataFrame(
...     {
...         "time": [
...             pd.Timestamp("2016-05-25 13:30:00.023"),
...             pd.Timestamp("2016-05-25 13:30:00.023"),
...             pd.Timestamp("2016-05-25 13:30:00.030"),
...             pd.Timestamp("2016-05-25 13:30:00.041"),
...             pd.Timestamp("2016-05-25 13:30:00.048"),
...             pd.Timestamp("2016-05-25 13:30:00.049"),
...             pd.Timestamp("2016-05-25 13:30:00.072"),
...             pd.Timestamp("2016-05-25 13:30:00.075")
...         ],
...         "ticker": [
...                "GOOG",
...                "MSFT",
...                "MSFT",
...                "MSFT",
...                "GOOG",
...                "AAPL",
...                "GOOG",
...                "MSFT"
...            ],
...            "bid": [720.50, 51.95, 51.97, 51.99, 720.50, 97.99, 720.50, 52.01],
...            "ask": [720.93, 51.96, 51.98, 52.00, 720.93, 98.01, 720.88, 52.03]
...     }
... )
>>> con = ibis.duckdb.connect()
>>> t = con.create_table("quotes", quotes)
>>> agged = t[
...     "ticker",
...     t.bid.sum()
...     .over(range=(-ibis.interval(seconds=10), 0), order_by=t.time)
...     .name("total_bid_amount"),
... ]
>>> agged.to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deepyaman/github/claypotai/ibis/ibis/expr/types/relations.py", line 3232, in to_pandas
    return self.execute(**kwargs)
  File "/Users/deepyaman/github/claypotai/ibis/ibis/expr/types/core.py", line 322, in execute
    return self._find_backend(use_default=True).execute(
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/__init__.py", line 335, in execute
    sql = query_ast.compile()
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/compiler/base.py", line 37, in compile
    compiled_queries = [q.compile() for q in self.queries]
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/compiler/base.py", line 37, in <listcomp>
    compiled_queries = [q.compile() for q in self.queries]
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/alchemy/query_builder.py", line 216, in compile
    frag = step(frag)
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/alchemy/query_builder.py", line 248, in _add_select
    arg = self._translate(op, named=True)
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/compiler/query_builder.py", line 239, in _translate
    return translator.get_result()
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/compiler/translator.py", line 224, in get_result
    translated = self.translate(self.node)
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/compiler/translator.py", line 256, in translate
    return formatter(self, op)
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/alchemy/registry.py", line 227, in _alias
    return t.translate(op.arg)
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/compiler/translator.py", line 256, in translate
    return formatter(self, op)
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/alchemy/registry.py", line 355, in _window_function
    end = _translate_window_boundary(window.frame.end)
  File "/Users/deepyaman/github/claypotai/ibis/ibis/backends/base/sql/alchemy/registry.py", line 321, in _translate_window_boundary
    raise com.TranslationError("Window boundaries must be literal values")
ibis.common.exceptions.TranslationError: Window boundaries must be literal values
>>> 
```

### What did you expect to happen?

Same thing, but with `pandas` backend, yields:

```python
>>> agged.to_pandas()
  ticker  total_bid_amount
0   GOOG            720.50
1   MSFT            772.45
2   MSFT            824.42
3   MSFT            876.41
4   GOOG           1596.91
5   AAPL           1694.90
6   GOOG           2415.40
7   MSFT           2467.41
>>> 
```

### What version of ibis are you using?

7.1.0 (c572eabaef7e02ec36eff146e33b693e74d8a6f0)

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
It looks like there are an annoying number of missing pieces here:

1. Ibis doesn't allow non-literals through
2. Even if it did, sqlalchemy `sa.over` implicitly doesn't allow expressions there because it's calling `int` on the range bounds.
3. Even if we could workaround the previous point, the sqlalchemy compiler assumes the range bounds can be compared to other objects with `<` 😞

I'll look into a workaround. Worst case we have to compile `sa.Over` (capital-`O`) ourselves.

**Comment by cpcloud** [comment]
Ok, I was able to hack around this ... it's not pretty.

I'll PR it though, in case it's an acceptable hack :)
