### ISSUE TITLE
feat(impala): support dates

### ISSUE THREAD

**Issue by chris-park** [ibis-project/ibis#7827]
### What happened?

Unable to cast `timestamp` columns to `date` directly using the Impala backend. Here's a reproducible example:

```python

import ibis
ibis.options.interactive = True

df = ibis.memtable({
    'timestamp': ['2023-12-21 09:30:00']
})

to_date = lambda d: ibis.to_sql(df.timestamp.cast('date'), dialect=d)

# DuckDB 
to_date('duckdb')
# SELECT
#   CAST(t0.timestamp AS DATE) AS "Cast(timestamp, date)"
# FROM _ibis_pandas_memtable_y574b7whvjffrllsztk4jevkiu AS t0

# MySQL
to_date('mysql')
# SELECT
#   CAST(t0.timestamp AS DATE) AS `Cast(timestamp, date)`
# FROM (
#   SELECT
#     '2023-12-21 09:30:00' AS timestamp
# ) AS t0

# Impala
to_date('impala')
# KeyError: 'date'
# UnsupportedBackendType: date
#
# But both CAST(timestamp_column AS DATE) and TO_DATE(timestamp_column) is possible in Impala.
```

### What version of ibis are you using?

`8.0.0.dev321` on Windows 10

### What backend(s) are you using, if any?

Impala

### Relevant log output

```sh
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File .venv\lib\site-packages\ibis\backends\base\sql\registry\helpers.py:78, in type_to_sql_string(tval)
     77 try:
---> 78     return sql_type_names[name]
     79 except KeyError:

KeyError: 'date'

During handling of the above exception, another exception occurred:

UnsupportedBackendType                    Traceback (most recent call last)
Cell In[12], line 1
----> 1 to_date('impala')

Cell In[9], line 1
----> 1 to_date = lambda d: ibis.to_sql(df.timestamp.cast('date'), dialect=d)

File .venv\lib\site-packages\ibis\expr\sql.py:399, in to_sql(expr, dialect, **kwargs)
    396     else:
    397         read = write = getattr(backend, "_sqlglot_dialect", dialect)
--> 399 sql = backend._to_sql(expr, **kwargs)
    400 (pretty,) = sg.transpile(sql, read=read, write=write, pretty=True)
    401 return SQLString(pretty)

File .venv\lib\site-packages\ibis\backends\base\sql\__init__.py:392, in BaseSQLBackend._to_sql(self, expr, **kwargs)
    391 def _to_sql(self, expr: ir.Expr, **kwargs) -> str:
--> 392     return str(self.compile(expr, **kwargs))

File .venv\lib\site-packages\ibis\backends\base\sql\__init__.py:389, in BaseSQLBackend.compile(self, expr, limit, params, timecontext)
    368 """Compile an Ibis expression.
    369 
    370 Parameters
   (...)
    386     backend.
    387 """
    388 self._define_udf_translation_rules(expr)
--> 389 return self.compiler.to_ast_ensure_limit(expr, limit, params=params).compile()

File .venv\lib\site-packages\ibis\backends\base\sql\compiler\base.py:37, in QueryAST.compile(self)
     35 def compile(self):
     36     compiled_setup_queries = [q.compile() for q in self.setup_queries]
---> 37     compiled_queries = [q.compile() for q in self.queries]
     38     compiled_teardown_queries = [q.compile() for q in self.teardown_queries]
     39     return self.context.collapse(
     40         list(
     41             chain(
   (...)
     46         )
     47     )

File .venv\lib\site-packages\ibis\backends\base\sql\compiler\base.py:37, in <listcomp>(.0)
     35 def compile(self):
     36     compiled_setup_queries = [q.compile() for q in self.setup_queries]
---> 37     compiled_queries = [q.compile() for q in self.queries]
     38     compiled_teardown_queries = [q.compile() for q in self.teardown_queries]
     39     return self.context.collapse(
     40         list(
     41             chain(
   (...)
     46         )
     47     )

File .venv\lib\site-packages\ibis\backends\base\sql\compiler\query_builder.py:266, in Select.compile(self)
    263 with_frag = self.format_subqueries()
    265 # SELECT
--> 266 select_frag = self.format_select_set()
    268 # FROM, JOIN, UNION
    269 from_frag = self.format_table_set()

File .venv\lib\site-packages\ibis\backends\base\sql\compiler\query_builder.py:321, in Select.format_select_set(self)
    319 for node in self.select_set:
    320     if isinstance(node, ops.Value):
--> 321         expr_str = self._translate(node, named=True, permit_subquery=True)
    322     elif isinstance(node, ops.TableNode):
    323         alias = context.get_ref(node)

File .venv\lib\site-packages\ibis\backends\base\sql\compiler\query_builder.py:236, in Select._translate(self, expr, named, permit_subquery, within_where)
    228 def _translate(self, expr, named=False, permit_subquery=False, within_where=False):
    229     translator = self.translator_class(
    230         expr,
    231         context=self.context,
   (...)
    234         within_where=within_where,
    235     )
--> 236     return translator.get_result()

File .venv\lib\site-packages\ibis\backends\base\sql\compiler\translator.py:224, in ExprTranslator.get_result(self)
    222 def get_result(self):
    223     """Compile SQL expression into a string."""
--> 224     translated = self.translate(self.node)
    225     if self._needs_name(self.node):
    226         # TODO: this could fail in various ways
    227         translated = self.name(translated, self.node.name)

File .venv\lib\site-packages\ibis\backends\base\sql\compiler\translator.py:256, in ExprTranslator.translate(self, op)
    254 elif type(op) in self._registry:
    255     formatter = self._registry[type(op)]
--> 256     return formatter(self, op)
    257 else:
    258     raise com.OperationNotDefinedError(f"No translation rule for {type(op)}")

File .venv\lib\site-packages\ibis\backends\base\sql\registry\main.py:23, in alias(translator, op)
     20 def alias(translator, op):
     21     # just compile the underlying argument because the naming is handled
     22     # by the translator for the top level expression
---> 23     return translator.translate(op.arg)

File .venv\lib\site-packages\ibis\backends\base\sql\compiler\translator.py:256, in ExprTranslator.translate(self, op)
    254 elif type(op) in self._registry:
    255     formatter = self._registry[type(op)]
--> 256     return formatter(self, op)
    257 else:
    258     raise com.OperationNotDefinedError(f"No translation rule for {type(op)}")

File .venv\lib\site-packages\ibis\backends\base\sql\registry\main.py:109, in cast(translator, op)
    107     return f"1000000 * unix_timestamp({arg_formatted})"
    108 else:
--> 109     sql_type = helpers.type_to_sql_string(op.to)
    110     return f"CAST({arg_formatted} AS {sql_type})"

File .venv\lib\site-packages\ibis\backends\base\sql\registry\helpers.py:80, in type_to_sql_string(tval)
     78     return sql_type_names[name]
     79 except KeyError:
---> 80     raise com.UnsupportedBackendType(name)

UnsupportedBackendType: date
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@chris-park Thanks for the issue!

It wasn't until recently that we tested against a version of Impala that supported dates. I expect that it will take a bit of effort to flesh out date support here.

Can you talk a bit about how you're using Impala?

We'd generally like to avoid adding new features to Impala because its upstream development status is hard to understand.

If you're using this in a production setting we'd like to know and if you're exploring Ibis then we'd also like to know that as well!

**Comment by chris-park** [comment]
Thanks for addressing this so quickly @cpcloud.

I use Ibis with Impala primarily to validate outsourced developers' implementation of business logic and requirements in Impala tables. Ibis lets me run more readable and streamlined tests, and allows me to mix different backends which is particularly useful for leveraging functionality not readily available in Impala, such as `explode()` on arrays.

**Comment by chris-park** [comment]
@cpcloud - I'm now getting the following error using `8.0.0.dev71` (using `pip install git+https://https://github.com/ibis-project/ibis@master`):
```python
>>> # Impala
>>> to_date('impala')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
  File ".venv\lib\site-packages\ibis\expr\sql.py", line 371, in to_sql
    (pretty,) = sg.transpile(sql, read=read, write=write, pretty=True)
  File ".venv\lib\site-packages\sqlglot\__init__.py", line 163, in transpile
    for expression in parse(sql, read, error_level=error_level)
  File ".venv\lib\site-packages\sqlglot\__init__.py", line 87, in parse
    return dialect.parse(sql, **opts)
  File ".venv\lib\site-packages\sqlglot\dialects\dialect.py", line 320, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File ".venv\lib\site-packages\sqlglot\parser.py", line 1009, in parse
    return self._parse(
  File ".venv\lib\site-packages\sqlglot\parser.py", line 1075, in _parse
    expressions.append(parse_method(self))
  File ".venv\lib\site-packages\sqlglot\parser.py", line 1265, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File ".venv\lib\site-packages\sqlglot\parser.py", line 2243, in _parse_select
    from_ = self._parse_from()
  File ".venv\lib\site-packages\sqlglot\parser.py", line 2398, in _parse_from
    exp.From, comments=self._prev_comments, this=self._parse_table(joins=joins)
  File ".venv\lib\site-packages\sqlglot\parser.py", line 2725, in _parse_table
    values = self._parse_derived_table_values()
  File ".venv\lib\site-packages\sqlglot\parser.py", line 2846, in _parse_derived_table_values
    expressions = self._parse_csv(self._parse_value)
  File ".venv\lib\site-packages\sqlglot\parser.py", line 4971, in _parse_csv
    parse_result = parse_method()
  File ".venv\lib\site-packages\sqlglot\parser.py", line 2170, in _parse_value
    self._match_r_paren()
  File ".venv\lib\site-packages\sqlglot\parser.py", line 5462, in _match_r_paren
    self.raise_error("Expecting )")
  File ".venv\lib\site-packages\sqlglot\parser.py", line 1119, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 2, Col: 38.
  SELECT CAST(t0.`timestamp` AS date) AS `Cast(timestamp, date)`
FROM (VALUES ('2023-12-21 09:30:00' ←[4mAS←[0m `timestamp`)) t0
```
Is this in line with what you would expect?

**Comment by cpcloud** [comment]
Can you show the definition of `to_date`?

**Comment by chris-park** [comment]
```python
import ibis
ibis.options.interactive = True

df = ibis.memtable({
    'timestamp': ['2023-12-21 09:30:00']
})

to_date = lambda d: ibis.to_sql(df.timestamp.cast('date'), dialect=d)
```

**Comment by cpcloud** [comment]
Possibly a bug, looking into it!

**Comment by chris-park** [comment]
Thanks. Could this have something do with the fact that Impala isn't supported by `sqlglot` (https://github.com/tobymao/sqlglot/issues/2637)? There are some [minor differences](https://impala.apache.org/docs/build/html/topics/impala_langref_unsupported.html) in syntax between Hive and Impala.

**Comment by cpcloud** [comment]
No, it's a bug in sqlglot unrelated to Impala, but to Hive.

**Comment by cpcloud** [comment]
That list of differences, at least with respect to `SELECT` statements, is incredibly out of date. I don't think the material differences will be a huge burden for Ibis, because a lot of the differences are in parts of Hive and Impala that are unlikely to ever be supported in Ibis.

> * Extensibility mechanisms such as TRANSFORM, custom file formats, or custom SerDes.

We don't support anything like this Ibis

> * The DATE data type.

This is just incorrect, recent versions of Impala support `DATE`

> * XML functions.

Ibis doesn't support this at any level.

> * Certain aggregate functions from HiveQL: covar_pop, covar_samp, corr, percentile, percentile_approx, histogram_numeric, collect_set; Impala supports the set of aggregate functions listed in [Impala Aggregate Functions](https://impala.apache.org/docs/build/html/topics/impala_aggregate_functions.html#aggregate_functions) and analytic functions listed in [Impala Analytic Functions](https://impala.apache.org/docs/build/html/topics/impala_analytic_functions.html#analytic_functions).

This is a limitation of Impala, using sqlglot's hive dialect neither helps nor hurts here.

> * Sampling.

Ibis supports sampling, but for Impala it's going to be very limited. This limitation with respect to Ibis is unrelated to Impala's syntactic differences from Hive.

> * Lateral views. In Impala 2.3 and higher, Impala supports queries on complex types (STRUCT, ARRAY, or MAP), using join notation rather than the EXPLODE() keyword. See [Complex Types (Impala 2.3 or higher only)](https://impala.apache.org/docs/build/html/topics/impala_complex_types.html#complex_types) for details about Impala support for complex types.

This might be the only material thing on the list. However, we won't be prioritizing anything complex like unnest operations for the Impala backend without very strong justification because the development status of Impala remains unclear and it's almost certainly the case that this would need upstream support from whoever works on https://github.com/cloudera/impyla.

**Comment by cpcloud** [comment]
@chris-park See https://github.com/tobymao/sqlglot/issues/2717. That reproduces the problem without Impala, using only Hive.
