### ISSUE TITLE
bug(flink): Flink's docker setup does not work for arm64 (Apple M1/M2)

### ISSUE THREAD

**Issue by chloeh13q** [ibis-project/ibis#8507]
### What happened?

The `flink` docker container fails in the build process (i.e., when running `docker compose build flink`).

### What version of ibis are you using?

8.0

### What backend(s) are you using, if any?

Flink

### Relevant log output

```sh
92.06 Collecting pemja==0.3.0
92.16   Downloading pemja-0.3.0.tar.gz (48 kB)
92.46      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 KB 123.7 kB/s eta 0:00:00
92.65   Installing build dependencies: started
97.24   Installing build dependencies: finished with status 'done'
97.24   Getting requirements to build wheel: started
97.32   Getting requirements to build wheel: finished with status 'error'
97.32   error: subprocess-exited-with-error
97.32   
97.32   × Getting requirements to build wheel did not run successfully.
97.32   │ exit code: 255
97.32   ╰─> [1 lines of output]
97.32       Include folder should be at '/opt/java/openjdk/include' but doesn't exist. Please check you've installed the JDK properly.
97.32       [end of output]
97.32   
97.32   note: This error originates from a subprocess, and is likely not a problem with pip.
97.32 error: subprocess-exited-with-error
97.32 
97.32 × Getting requirements to build wheel did not run successfully.
97.32 │ exit code: 255
97.32 ╰─> See above for output.
97.32 
97.32 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: process "/bin/sh -c pip3 install apache-flink==1.18.1" did not complete successfully: exit code: 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chloeh13q** [comment]
I was able to resolve this by using the following Dockerfile
```
FROM flink:1.18.0

# install python3 and pip3
RUN apt-get update -y && \
apt-get install -y python3 python3-pip python3-dev openjdk-11-jdk-headless && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/python3 /usr/bin/python

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64

# install PyFlink
RUN pip3 install apache-flink==1.18.0
```
but it seems a bit much to have a separate Dockerfile. Should we document this somewhere? Is there a better way we can track different issues due to architecture differences, systems, etc?

**Comment by chloeh13q** [comment]
cc @ncclementi

**Comment by cpcloud** [comment]
We can set environment variables on container start. Would that work?

**Comment by ncclementi** [comment]
I was able to get the container up using virtualization of a `x86_64` architecture, but trying to run the tests 
`pytest ibis/backends/test_array.py -m flink` are all failing with 

```
```

**Comment by chloeh13q** [comment]
@ncclementi Can you go a little further down on the traceback? Or alternatively paste the full traceback? There should be a more clear error message somewhere further down in the traceback.

**Comment by ncclementi** [comment]
I don't know what changed from yesterday to today on main. But this time I only got one failure, and the rest passed or skipped. The full fail is:

<details open>
<summary>Traceback</summary>

```python-traceback

platform darwin -- Python 3.10.13, pytest-8.0.2, pluggy-1.4.0
Using --randomly-seed=1739207873
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/naty/Documents/git/my_forks/ibis
configfile: pyproject.toml
plugins: repeat-0.9.2, snapshot-0.0.0, anyio-4.3.0, randomly-3.15.0, cov-4.1.0, clarity-1.0.1, mock-3.12.0, hypothesis-6.98.15, xdist-3.5.0, benchmark-4.0.0, pytest_httpserver-1.0.10
collected 2660 items / 2527 deselected / 133 selected                                         

ibis/backends/tests/test_array.py Exception ignored in: <_io.FileIO name=32 mode='wb' closefd=True>
Traceback (most recent call last):
  File "/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 59, in __exit__
    del self.unraisable
ResourceWarning: unclosed file <_io.BufferedWriter name=32>
Exception ignored in: <_io.FileIO name=33 mode='rb' closefd=True>
Traceback (most recent call last):
  File "/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 59, in __exit__
    del self.unraisable
ResourceWarning: unclosed file <_io.BufferedReader name=33>
xxx.xx.xxx.xx.xx.xx.xx.Fxxx.xxxx.xxx.xxxx..xxxxxxxxxx [ 39%]
xxx..xx.xxx.x.xx.xx.x.xx.x.xxxxx.xx.x..xxxxxxxxx.xxxxxx.xxx.xxxxxxxxxxxxxxxxxx..        [100%]

========================================== FAILURES ===========================================
________________________________ test_np_array_literal[flink] _________________________________

con = <ibis.backends.flink.Backend object at 0x15fb63df0>

    def test_np_array_literal(con):
        arr = np.array([1, 2, 3])
        expr = ibis.literal(arr)
>       result = con.execute(expr.name("tmp"))

ibis/backends/tests/test_array.py:174: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ibis/backends/flink/__init__.py:346: in execute
    df = self._table_env.sql_query(sql).to_pandas()
/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/pyflink/table/table.py:948: in to_pandas
    table = pa.Table.from_batches(serializer.load_from_iterator(batches_iterator))
pyarrow/table.pxi:3843: in pyarrow.lib.Table.from_batches
    ???
/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/pyflink/table/serializers.py:76: in load_from_iterator
    reader = pa.ipc.open_stream(
/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/pyarrow/ipc.py:190: in open_stream
    return RecordBatchStreamReader(source, options=options,
/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/pyarrow/ipc.py:52: in __init__
    self._open(source, options=options, memory_pool=memory_pool)
pyarrow/ipc.pxi:858: in pyarrow.lib._RecordBatchStreamReader._open
    ???
pyarrow/error.pxi:144: in pyarrow.lib.pyarrow_internal_check_status
    ???
/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/pyflink/table/serializers.py:69: in readinto
    input = self.leftover or (self.iter.next() if self.iter.hasNext() else None)
/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/py4j/java_gateway.py:1322: in __call__
    return_value = get_return_value(
/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/pyflink/util/exceptions.py:146: in deco
    return f(*a, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

answer = 'xro4478', gateway_client = <py4j.java_gateway.GatewayClient object at 0x15fb62ef0>
target_id = 'o4418', name = 'next'

    def get_return_value(answer, gateway_client, target_id=None, name=None):
        """Converts an answer received from the Java gateway into a Python object.
    
        For example, string representation of integers are converted to Python
        integer, string representation of objects are converted to JavaObject
        instances, etc.
    
        :param answer: the string returned by the Java gateway
        :param gateway_client: the gateway client used to communicate with the Java
            Gateway. Only necessary if the answer is a reference (e.g., object,
            list, map)
        :param target_id: the name of the object from which the answer comes from
            (e.g., *object1* in `object1.hello()`). Optional.
        :param name: the name of the member from which the answer comes from
            (e.g., *hello* in `object1.hello()`). Optional.
        """
        if is_error(answer)[0]:
            if len(answer) > 1:
                type = answer[1]
                value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                if answer[1] == REFERENCE_TYPE:
>                   raise Py4JJavaError(
                        "An error occurred while calling {0}{1}{2}.\n".
                        format(target_id, ".", name), value)
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o4418.next.
E                   : java.lang.RuntimeException: Failed to serialize the data of the table
E                   	at org.apache.flink.table.runtime.arrow.ArrowUtils$2.next(ArrowUtils.java:602)
E                   	at org.apache.flink.table.runtime.arrow.ArrowUtils$2.next(ArrowUtils.java:582)
E                   	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
E                   	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
E                   	at org.apache.flink.api.python.shaded.py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at org.apache.flink.api.python.shaded.py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
E                   	at org.apache.flink.api.python.shaded.py4j.Gateway.invoke(Gateway.java:282)
E                   	at org.apache.flink.api.python.shaded.py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at org.apache.flink.api.python.shaded.py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at org.apache.flink.api.python.shaded.py4j.GatewayConnection.run(GatewayConnection.java:238)
E                   	at java.base/java.lang.Thread.run(Thread.java:1623)
E                   Caused by: java.lang.RuntimeException: Failed to fetch next result
E                   	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.nextResultFromFetcher(CollectResultIterator.java:109)
E                   	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.hasNext(CollectResultIterator.java:80)
E                   	at org.apache.flink.table.planner.connectors.CollectDynamicSink$CloseableRowIteratorWrapper.hasNext(CollectDynamicSink.java:222)
E                   	at org.apache.flink.table.runtime.arrow.ArrowUtils$1.hasNext(ArrowUtils.java:571)
E                   	at org.apache.flink.table.runtime.arrow.ArrowUtils$2.next(ArrowUtils.java:592)
E                   	... 10 more
E                   Caused by: java.io.IOException: Failed to fetch job execution result
E                   	at org.apache.flink.streaming.api.operators.collect.CollectResultFetcher.getAccumulatorResults(CollectResultFetcher.java:185)
E                   	at org.apache.flink.streaming.api.operators.collect.CollectResultFetcher.next(CollectResultFetcher.java:121)
E                   	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.nextResultFromFetcher(CollectResultIterator.java:106)
E                   	... 14 more
E                   Caused by: java.util.concurrent.ExecutionException: org.apache.flink.client.program.ProgramInvocationException: Job failed (JobID: 8bdf807df46eb1fbc1fac315d2abbb9d)
E                   	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
E                   	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
E                   	at org.apache.flink.streaming.api.operators.collect.CollectResultFetcher.getAccumulatorResults(CollectResultFetcher.java:183)
E                   	... 16 more
E                   Caused by: org.apache.flink.client.program.ProgramInvocationException: Job failed (JobID: 8bdf807df46eb1fbc1fac315d2abbb9d)
E                   	at org.apache.flink.client.deployment.ClusterClientJobClientAdapter.lambda$null$6(ClusterClientJobClientAdapter.java:130)
E                   	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
E                   	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
E                   	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
E                   	at org.apache.flink.util.concurrent.FutureUtils.lambda$retryOperationWithDelay$6(FutureUtils.java:302)
E                   	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
E                   	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
E                   	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
E                   	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
E                   	at org.apache.flink.client.program.rest.RestClusterClient.lambda$pollResourceAsync$33(RestClusterClient.java:794)
E                   	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
E                   	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
E                   	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
E                   	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
E                   	at org.apache.flink.util.concurrent.FutureUtils.lambda$retryOperationWithDelay$6(FutureUtils.java:302)
E                   	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
E                   	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
E                   	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
E                   	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
E                   	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1163)
E                   	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
E                   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
E                   	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
E                   	... 1 more
E                   Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
E                   	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
E                   	at org.apache.flink.client.deployment.ClusterClientJobClientAdapter.lambda$null$6(ClusterClientJobClientAdapter.java:128)
E                   	... 23 more
E                   Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
E                   	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:176)
E                   	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:107)
E                   	at org.apache.flink.runtime.scheduler.DefaultScheduler.recordTaskFailure(DefaultScheduler.java:285)
E                   	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:276)
E                   	at org.apache.flink.runtime.scheduler.DefaultScheduler.onTaskFailed(DefaultScheduler.java:269)
E                   	at org.apache.flink.runtime.scheduler.SchedulerBase.onTaskExecutionStateUpdate(SchedulerBase.java:764)
E                   	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:741)
E                   	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:83)
E                   	at org.apache.flink.runtime.jobmaster.JobMaster$1.onMissingDeploymentsOf(JobMaster.java:265)
E                   	at org.apache.flink.runtime.jobmaster.DefaultExecutionDeploymentReconciler.reconcileExecutionDeployments(DefaultExecutionDeploymentReconciler.java:61)
E                   	at org.apache.flink.runtime.jobmaster.JobMaster$TaskManagerHeartbeatListener.reportPayload(JobMaster.java:1487)
E                   	at org.apache.flink.runtime.jobmaster.JobMaster$TaskManagerHeartbeatListener.reportPayload(JobMaster.java:1452)
E                   	at org.apache.flink.runtime.heartbeat.HeartbeatManagerImpl.receiveHeartbeat(HeartbeatManagerImpl.java:214)
E                   	at org.apache.flink.runtime.jobmaster.JobMaster.heartbeatFromTaskManager(JobMaster.java:849)
E                   	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
E                   	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
E                   	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
E                   	at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.lambda$handleRpcInvocation$1(PekkoRpcActor.java:309)
E                   	at org.apache.flink.runtime.concurrent.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83)
E                   	at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcInvocation(PekkoRpcActor.java:307)
E                   	at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcMessage(PekkoRpcActor.java:222)
E                   	at org.apache.flink.runtime.rpc.pekko.FencedPekkoRpcActor.handleRpcMessage(FencedPekkoRpcActor.java:85)
E                   	at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleMessage(PekkoRpcActor.java:168)
E                   	at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:33)
E                   	at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:29)
E                   	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
E                   	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
E                   	at org.apache.pekko.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:29)
E                   	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
E                   	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
E                   	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
E                   	at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
E                   	at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545)
E                   	at org.apache.pekko.actor.AbstractActor.aroundReceive(AbstractActor.scala:229)
E                   	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
E                   	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
E                   	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
E                   	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
E                   	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
E                   	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
E                   	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
E                   	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
E                   	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
E                   	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
E                   Caused by: org.apache.flink.util.FlinkException: Execution dea71da8a8dbd591435dc383601bcf4f_cbc357ccb763df2852fee8c4fc7d55f2_0_0 is unexpectedly no longer running on task executor 172.21.0.3:39607-52f29e.
E                   	at org.apache.flink.runtime.jobmaster.JobMaster$1.onMissingDeploymentsOf(JobMaster.java:270)
E                   	... 36 more

/Users/naty/mambaforge/envs/ibis-dev-flink/lib/python3.10/site-packages/py4j/protocol.py:326: Py4JJavaError
=================================== short test summary info ===================================
FAILED ibis/backends/tests/test_array.py::test_np_array_literal[flink] - py4j.protocol.Py4JJavaError: An error occurred while calling o4418.next.
```

</details>

**Comment by deepyaman** [comment]
> I made some changes to the Dockerfile and got it to work. Here's a Dockerfile that worked for me on Apple M1
> 
> ```
> FROM flink:1.18.0
> 
> # install python3 and pip3
> RUN apt-get update -y && \
> apt-get install -y python3 python3-pip python3-dev openjdk-11-jdk-headless && rm -rf /var/lib/apt/lists/*
> RUN ln -s /usr/bin/python3 /usr/bin/python
> 
> ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64
> 
> # install PyFlink
> RUN pip3 install apache-flink==1.18.0
> ```
> 
> but it seems a bit much to have a separate Dockerfile. Should we document this somewhere? Is there a better way we can track different issues due to architecture differences, systems, etc?

@chloeh13q Yeah, this is quite similar to what I had for local build on M2:

```diff
diff --git a/docker/flink/Dockerfile b/docker/flink/Dockerfile
index 186aa37f7..ddee3a6d9 100644
--- a/docker/flink/Dockerfile
+++ b/docker/flink/Dockerfile
@@ -3,10 +3,14 @@ FROM flink:1.18.1
 # ibis-flink requires PyFlink dependency
 RUN wget -nv -P $FLINK_HOME/lib/ https://repo1.maven.org/maven2/org/apache/flink/flink-python/1.18.1/flink-python-1.18.1.jar
 
-# install python3 and pip3
-RUN apt-get update -y && \
-apt-get install -y python3 python3-pip python3-dev && rm -rf /var/lib/apt/lists/*
-RUN ln -s /usr/bin/python3 /usr/bin/python
+# install python3, pip3, and the JDK
+RUN \
+  apt-get update -y && \
+  apt-get install -y python3 python3-pip python3-dev git openjdk-11-jdk && \
+  rm -rf /var/lib/apt/lists/* && \
+  ln -s /usr/bin/python3 /usr/bin/python
+ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk-arm64/"
+ENV PATH="${JAVA_HOME}:${PATH}"
 
 # install PyFlink
 RUN pip3 install apache-flink==1.18.1
```

In the end, I didn't include the change, as it wasn't necessary for CI, and I wasn't sure whether it was specific to my machine. Sorry for not sharing this context earlier; could have saved some time.

I'd be happy to include this in the repo, as the CI will still pass.

**Comment by cpcloud** [comment]
I asked above whether we can set environment variables when the container starts. Can we do that?
