### ISSUE TITLE
bug(clickhouse): UDF is not visible

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis#8512]
```python
import os
import ibis
import ollama

from dotenv import load_dotenv
from pathlib import Path

import pandas as pd
import ibis.expr.datatypes as dt

rag_con = ibis.connect(f"clickhouse://localhost")


for table in rag_con.list_tables():
    rag_con.drop_table(table)

rag_con.list_tables()


table_name = "docs5"
for filepath in Path("/Users/markhneedham/projects/clickhouse-docs/docs").glob("**/*.md"):
    contents = filepath.read_text()

    data = {
        "filepath": [str(filepath).split("docs/")[-1]],
        "contents": [contents],
    }

    t = pd.DataFrame(data)
    schema = ibis.schema(
        names=["filepath", "contents"], 
        types=[dt.String(nullable=False), dt.String(nullable=False)]
    )

    if table_name not in rag_con.list_tables():
        rag_con.create_table(name=table_name, obj=t, schema=schema)
    else:
        rag_con.insert(name=table_name, obj=t)

rag_con.list_tables()


t = rag_con.table(table_name)

t = (
    t.mutate(tokens_estimate=t["contents"].length() // 4)
    .order_by(ibis._["tokens_estimate"].desc())
    .relocate("filepath", "tokens_estimate")
)
t

def _embed(text: str) -> list[float]:
    """Text to fixed-length array embedding."""
    text = text.replace("\n", " ")
    try:
        return (
            ollama.embeddings(model='nomic-embed-text', prompt=text)['embedding']
        )
    except Exception as e:
        print(e)
    return [0.0] * 768


@ibis.udf.scalar.python
def embed(text: str, tokens_estimate: int) -> list[float]:
    """Text to fixed-length array embedding."""
    if 0 < tokens_estimate < 8191:
        return _embed(text)
    return [0.0] * 768


t = t.mutate(
    embedding=embed(t["contents"], t["tokens_estimate"])
).cache()
t
```

So I'm now running against `ibis-framework` on the GitHub main branch. And I get this error:

```text
Traceback (most recent call last):
  File "/Users/markhneedham/projects/examples/LearnClickHouseWithMark/ibis/app_ch.py", line 101, in <module>
    ).cache()
      ^^^^^^^
  File "/Users/markhneedham/Library/Caches/pypoetry/virtualenvs/ibis-clickhouse-ZMCVYiHj-py3.11/lib/python3.11/site-packages/ibis/expr/types/relations.py", line 3414, in cache
    return current_backend._cached(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markhneedham/Library/Caches/pypoetry/virtualenvs/ibis-clickhouse-ZMCVYiHj-py3.11/lib/python3.11/site-packages/ibis/backends/__init__.py", line 1128, in _cached
    self._query_cache.store(expr)
  File "/Users/markhneedham/Library/Caches/pypoetry/virtualenvs/ibis-clickhouse-ZMCVYiHj-py3.11/lib/python3.11/site-packages/ibis/common/caching.py", line 122, in store
    self.populate(name, input)
  File "/Users/markhneedham/Library/Caches/pypoetry/virtualenvs/ibis-clickhouse-ZMCVYiHj-py3.11/lib/python3.11/site-packages/ibis/backends/sql/__init__.py", line 216, in _load_into_cache
    self.create_table(name, expr, schema=expr.schema(), temp=True)
  File "/Users/markhneedham/Library/Caches/pypoetry/virtualenvs/ibis-clickhouse-ZMCVYiHj-py3.11/lib/python3.11/site-packages/ibis/backends/clickhouse/__init__.py", line 722, in create_table
    self.con.raw_query(sql, external_data=external_data)
  File "/Users/markhneedham/Library/Caches/pypoetry/virtualenvs/ibis-clickhouse-ZMCVYiHj-py3.11/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 472, in raw_query
    return self._raw_request(body, params, fields=fields).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markhneedham/Library/Caches/pypoetry/virtualenvs/ibis-clickhouse-ZMCVYiHj-py3.11/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 437, in _raw_request
    self._error_handler(response)
  File "/Users/markhneedham/Library/Caches/pypoetry/virtualenvs/ibis-clickhouse-ZMCVYiHj-py3.11/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 361, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://localhost:8123 returned response code 404)
 Code: 46. DB::Exception: Unknown function embed_0: While processing filepath, CAST(floor(length(contents) / 4), 'Nullable(Int64)') AS tokens_estimate, contents, embed_0(contents, CAST(floor(length(contents) / 4), 'Nullable(Int64)')) AS embedding. (UNKNOWN_FUNCTION) (version 24.2.1.1933 (official build))
```

How do I go about debugging that? Is there a way to see a list of the functions that have been registered? I can't tell if my function failed to register or if it's registered with an unexpected signature?

_Originally posted by @mneedham in https://github.com/ibis-project/ibis/issues/8501#issuecomment-1972983092_

**Comment by mneedham** [comment]
No as far as I know your understanding is correct. So what happens when run the function with the `@ibis.udf.scalar.python` annotation - is that a noop?

And I guess my next question is whether there's a way to do what I'm attempting here? 

I think what you're suggesting is that I should configure an `embed` function using XML files and then register it to IBIS using `ibis.udf.scalar.builtin` and then I'd be able to run my script?

**Comment by mneedham** [comment]
At the risk of taking us down a bit of a rabbit hole, if I was to use `chDB` then we would be able to define Python UDFs.

![2024-03-01_13-01-41](https://github.com/ibis-project/ibis/assets/13220/f5fa0e85-06e1-47b1-88b7-1a892d581457)

https://doc.chdb.io/#/install?id=installation-1

**Comment by cpcloud** [comment]
> So what happens when I run the function with the @ibis.udf.scalar.python annotation - is that a noop?

We chose to keep the UDF definition API decoupled from the backend, so yes technically it's a no-op. The registration of UDFs in backends that support them happens just before execution.

> I think what you're suggesting is that I should configure an embed function using XML files and then register it to IBIS using ibis.udf.scalar.builtin and then I'd be able to run my script?

Yep, that's correct!

> At the risk of taking us down a bit of a rabbit hole, if I was to use chDB then we would be able to define Python UDFs.

Funny you mention chdb 😉 We have a [WIP PR to add chdb as a backend](https://github.com/ibis-project/ibis/pull/8497).

We're interested in supporting chdb for sure.

**Comment by cpcloud** [comment]
Closing as stale, we don't support defining Python UDFs in our current clickhouse backend.
