### ISSUE TITLE
docs: Unexpected side effects due to the hard dependency on `snowflake`'s `connector`'s `paramstyle`

### ISSUE THREAD

**Issue by yazad3** [ibis-project/ibis#8738]
### Please describe the issue

# Background

Snowflake Python connector API has a global level `paramstyle` property that controls how parameter placeholders are expressed in a query. The common obvious styles used on projects are `pyformat` (default) and `qmark`.

Here are examples of how these formats affect the way paramerets placeholders are represented in a query,

```sql
# pyformat
.execute("... WHERE my_column = %(name)s", {"name": value})
```

```
# qmark
.execute("... WHERE my_column = ?", (value,))
```

Please see the [paramstyle section](https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-api#:~:text=module%20and%20connections.-,paramstyle,-String%20constant%20stating) in the offical snowflake documentation.

> IMPORTANT TO NOTE: The `paramstyle` property change impacts ALL snowflake connections opened in an interpreter and is NOT a property at a specific `connection` level.

# Issue

If the following line is set **ANYWHERE** in the applicaton or it's upstream dependency - ibis-snowflake code will break in unexpected ways,

```python
connector.paramstyle = "qmark"
```

## E2E example to reproduce the issue

The root cause of the failure is the line `connector.paramstyle = "qmark"`.

```python
import json
import unittest

import ibis
import pandas as pd
from ibis.backends.snowflake import Backend as SnowflakeBackend
from ibis.expr.types import Table
from snowflake import connector


pd.set_option("display.max_columns", None)


def ibis_snowflake_backend(schema: str) -> SnowflakeBackend:
    with open("/tmp/config.json") as f:
        conf = json.loads(f.read())

    connection: SnowflakeBackend = ibis.snowflake.connect(
        user=conf["user"],
        account=conf["account"],
        database=f"""{conf["database"]}/{schema}""",
        warehouse=conf["warehouse"],
        authenticator="externalbrowser",
        role=conf["role"],
    )

    print(f"{type(connection)=}; {connection=}")

    return connection


class TestIbisCleanupSanity(unittest.TestCase):
    def test_reproduce(self):
        print(connector.paramstyle)
        ##################################
        # I am EVIL! Comment me!
        connector.paramstyle = "qmark"
        # I am EVIL! Comment me!
        ##################################

        snowflake_backend: SnowflakeBackend = ibis_snowflake_backend(
            schema="INFORMATION_SCHEMA"
        )

        tables_table: Table = snowflake_backend.table("TABLES")

        filtered_table_1: Table = tables_table.filter(
            tables_table.TABLE_SCHEMA == "TESTING"
        ).select(
            "TABLE_CATALOG",
            "TABLE_SCHEMA",
            "TABLE_NAME",
            "ROW_COUNT",
        )

        quantile_0_5_row_count: float = filtered_table_1.ROW_COUNT.quantile(0.5).execute()

        print(f"{quantile_0_5_row_count=}")

```

The error (`quantile` `execute` fails),

```
Error
Traceback (most recent call last):
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 904, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001015 (22023): SQL compilation error:
argument 0 to function PERCENTILE_CONT needs to be constant, found 'CAST(? AS NUMBER(18,0))'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xyz/
  ma/abc_ds/scratch/test_scratch/test_reproduce.py", line 56, in test_reproduce
    quantile_0_5_row_count: float = filtered_table_1.ROW_COUNT.quantile(0.5).execute()
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/ibis/expr/types/core.py", line 324, in execute
    return self._find_backend(use_default=True).execute(
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/ibis/backends/base/sql/__init__.py", line 342, in execute
    with self._safe_raw_sql(sql, **kwargs) as cursor:
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 205, in _safe_raw_sql
    yield con.execute(*args, **kwargs)
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 904, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/xyz/opt/anaconda3/envs/my_venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001015 (22023): SQL compilation error:
argument 0 to function PERCENTILE_CONT needs to be constant, found 'CAST(? AS NUMBER(18,0))'
[SQL: WITH t0 AS 
(SELECT t2."TABLE_CATALOG" AS "TABLE_CATALOG", t2."TABLE_SCHEMA" AS "TABLE_SCHEMA", t2."TABLE_NAME" AS "TABLE_NAME", t2."TABLE_OWNER" AS "TABLE_OWNER", t2."TABLE_TYPE" AS "TABLE_TYPE", t2."IS_TRANSIENT" AS "IS_TRANSIENT", t2."CLUSTERING_KEY" AS "CLUSTERING_KEY", t2."ROW_COUNT" AS "ROW_COUNT", t2."BYTES" AS "BYTES", t2."RETENTION_TIME" AS "RETENTION_TIME", t2."SELF_REFERENCING_COLUMN_NAME" AS "SELF_REFERENCING_COLUMN_NAME", t2."REFERENCE_GENERATION" AS "REFERENCE_GENERATION", t2."USER_DEFINED_TYPE_CATALOG" AS "USER_DEFINED_TYPE_CATALOG", t2."USER_DEFINED_TYPE_SCHEMA" AS "USER_DEFINED_TYPE_SCHEMA", t2."USER_DEFINED_TYPE_NAME" AS "USER_DEFINED_TYPE_NAME", t2."IS_INSERTABLE_INTO" AS "IS_INSERTABLE_INTO", t2."IS_TYPED" AS "IS_TYPED", t2."COMMIT_ACTION" AS "COMMIT_ACTION", t2."CREATED" AS "CREATED", t2."LAST_ALTERED" AS "LAST_ALTERED", t2."LAST_DDL" AS "LAST_DDL", t2."LAST_DDL_BY" AS "LAST_DDL_BY", t2."AUTO_CLUSTERING_ON" AS "AUTO_CLUSTERING_ON", t2."COMMENT" AS "COMMENT", t2."IS_TEMPORARY" AS "IS_TEMPORARY", t2."IS_ICEBERG" AS "IS_ICEBERG", t2."IS_DYNAMIC" AS "IS_DYNAMIC" 
FROM "INFORMATION_SCHEMA"."TABLES" AS t2 
WHERE t2."TABLE_SCHEMA" = ?)
 SELECT percentile_cont(?) WITHIN GROUP (ORDER BY t1."ROW_COUNT") AS "Quantile(ROW_COUNT, 0.5)" 
FROM (SELECT t0."TABLE_CATALOG" AS "TABLE_CATALOG", t0."TABLE_SCHEMA" AS "TABLE_SCHEMA", t0."TABLE_NAME" AS "TABLE_NAME", t0."ROW_COUNT" AS "ROW_COUNT" 
FROM t0) AS t1]
[parameters: ('TESTING', 0.5)]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

## `Snowflake-SQLAlchemy`

It can be argued that this is not an ibis issue at all and in fact an `SQLAlchemy` or `Snowflake-SQLAlchmey` issue (as seen in the trace) - which is correct, but this issue manifests in unintutive ways when using ibis.

This is why I am opening a documentation request instead of a bug with ibis. IMO, the true bug is in the design of `snowflake`'s core python API where the `paramstyle` is global.

## Environment for reproduction

I don't believe this is environment specific but providing for completeness,

### System
```
CPU - Apple M1 Max
Python - 3.10 (Anaconda VM)
```

Python Requirements,

```
snowflake-connector-python[pandas,secure-local-storage]==3.0.3
pandas==1.5.3
snowflake-sqlalchemy==1.5.1
sqlglot==20.11.0
ibis-framework[pandas,snowflake,duckdb]==8.0.0
```

# Conditions when this issue surfaces

It may be argued why do you even have `connector.paramstyle = "qmark"` in your code, but the issue is in a large project with many upstream dependencies, the change in paramstyle may be in code you do not control. To make matters worse, as noted earlier, this is a global setting for snowflake at the `connector` api level and NOT for individual `connection`s.

The error `SQL compilation error: argument 0 to function PERCENTILE_CONT needs to be constant, found 'CAST(? AS NUMBER(18,0))'` is also not intutive.

# Mitigation

Setting `connector.paramstyle = "pyformat"` before invoking `ibis` resolves the issue. Though it is not a robust solution, in a multi-threaded application with code using `qmark` `paramstyle` queries will fail. The hope is by documenting this issue developers using ibis for snowflake will be aware of this pitfall and hopefully find ways to avoid it.

# Case for documentation

As noted above, I don't believe this is a bug in ibis but rather a design issue in how paramstyle is handled by snowflake's python API. It would be helpful for the ibis community to know this pitfall so they can avoid it.

# Offering help

I spent an evening debugging this and would love to offer PRs so others don't have to deal with this issue,

* Document this pitfall in ibis's snowflake documentation.
* Add a check to fail-fast if `paramstyle` other than `pyformat` is detected.
* Anythiong else that ibis experts deem necessary for this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@yazad3 Welcome, and thanks for taking the time to create such a thorough issue.

I agree with your assessment of the problem.

Good news: with the next release this shouldn't be an issue, because we're no longer using SQLAlchemy to generate SQL for any backends, we're using [sqlglot](https://github.com/tobymao/sqlglot).

We're not too far away from that release, so it might be a bit of unnecessary work to document it only to have us remove that documentation before the 9.0 release.

It would be helpful if you could test your application/library with a pre-release of Ibis, which you can install using:

```
$ pip install --upgrade --pre 'ibis-framework[snowflake]'  # use whatever extras you need
```

Great to have you around these parts!

**Comment by yazad3** [comment]
Thank you @cpcloud :)

I had to cleanup the environment and reinstall ibis' latest dev version (`9.0.0.dev457`)


I can confirm there are no traces of `SQLAlchemy` (or `Snowflake-SQLAlchemy`) in the environment anymore.


See pipdeptree results below,

```
duckdb==0.10.1
ibis-framework==9.0.0.dev457
├── atpublic [required: >=2.3,<5, installed: 4.0]
├── bidict [required: >=0.22.1,<1, installed: 0.23.1]
├── numpy [required: >=1,<2, installed: 1.26.4]
├── pandas [required: >=1.2.5,<3, installed: 1.5.3]
│   ├── numpy [required: >=1.21.0, installed: 1.26.4]
│   ├── python-dateutil [required: >=2.8.1, installed: 2.9.0.post0]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   └── pytz [required: >=2020.1, installed: 2024.1]
├── parsy [required: >=2,<3, installed: 2.1]
├── pyarrow [required: >=2,<16, installed: 10.0.1]
│   └── numpy [required: >=1.16.6, installed: 1.26.4]
├── pyarrow-hotfix [required: >=0.4,<1, installed: 0.6]
├── python-dateutil [required: >=2.8.2,<3, installed: 2.9.0.post0]
│   └── six [required: >=1.5, installed: 1.16.0]
├── pytz [required: >=2022.7, installed: 2024.1]
├── rich [required: >=12.4.4,<14, installed: 13.7.1]
│   ├── markdown-it-py [required: >=2.2.0, installed: 3.0.0]
│   │   └── mdurl [required: ~=0.1, installed: 0.1.2]
│   └── Pygments [required: >=2.13.0,<3.0.0, installed: 2.17.2]
├── sqlglot [required: >=22.4,<22.6, installed: 22.5.0]
├── toolz [required: >=0.11,<1, installed: 0.12.1]
└── typing_extensions [required: >=4.3.0,<5, installed: 4.10.0]
keyring==23.13.1
├── importlib_metadata [required: >=4.11.4, installed: 7.1.0]
│   └── zipp [required: >=0.5, installed: 3.18.1]
└── jaraco.classes [required: Any, installed: 3.3.1]
    └── more-itertools [required: Any, installed: 10.2.0]
pip==23.3.1
pipdeptree==2.16.1
regex==2023.12.25
setuptools==68.2.2
snowflake-connector-python==3.0.3
├── asn1crypto [required: >0.24.0,<2.0.0, installed: 1.5.1]
├── certifi [required: >=2017.4.17, installed: 2024.2.2]
├── cffi [required: >=1.9,<2.0.0, installed: 1.16.0]
│   └── pycparser [required: Any, installed: 2.21]
├── charset-normalizer [required: >=2,<3, installed: 2.1.1]
├── cryptography [required: >=3.1.0,<41.0.0, installed: 40.0.2]
│   └── cffi [required: >=1.12, installed: 1.16.0]
│       └── pycparser [required: Any, installed: 2.21]
├── filelock [required: >=3.5,<4, installed: 3.13.1]
├── idna [required: >=2.5,<4, installed: 3.6]
├── oscrypto [required: <2.0.0, installed: 1.3.0]
│   └── asn1crypto [required: >=1.5.1, installed: 1.5.1]
├── packaging [required: Any, installed: 24.0]
├── pycryptodomex [required: >=3.2,<4.0.0,!=3.5.0, installed: 3.20.0]
├── PyJWT [required: <3.0.0, installed: 2.8.0]
├── pyOpenSSL [required: >=16.2.0,<24.0.0, installed: 23.2.0]
│   └── cryptography [required: >=38.0.0,<42,!=40.0.1,!=40.0.0, installed: 40.0.2]
│       └── cffi [required: >=1.12, installed: 1.16.0]
│           └── pycparser [required: Any, installed: 2.21]
├── pytz [required: Any, installed: 2024.1]
├── requests [required: <3.0.0, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2024.2.2]
│   ├── charset-normalizer [required: >=2,<4, installed: 2.1.1]
│   ├── idna [required: >=2.5,<4, installed: 3.6]
│   └── urllib3 [required: >=1.21.1,<3, installed: 1.26.18]
├── typing_extensions [required: >=4.3,<5, installed: 4.10.0]
└── urllib3 [required: >=1.21.1,<1.27, installed: 1.26.18]
wheel==0.41.2
```


However, the test waasn't successful due to an unrelated reason, see stacktrace below,

```
Traceback (most recent call last):
  File "/.../scratch/test_scratch/test_reproduce.py", line 41, in test_reproduce
    snowflake_backend: SnowflakeBackend = ibis_snowflake_backend(
  File "/.../scratch/test_scratch/test_reproduce.py", line 18, in ibis_snowflake_backend
    connection: SnowflakeBackend = ibis.snowflake.connect(
  File "/.../opt/anaconda3/envs/scratch_env/lib/python3.10/site-packages/ibis/__init__.py", line 108, in connect
    return backend.connect(*args, **kwargs)
  File "/.../opt/anaconda3/envs/scratch_env/lib/python3.10/site-packages/ibis/backends/__init__.py", line 764, in connect
    new_backend.reconnect()
  File "/.../opt/anaconda3/envs/scratch_env/lib/python3.10/site-packages/ibis/backends/__init__.py", line 778, in reconnect
    self.do_connect(*self._con_args, **self._con_kwargs)
  File "/.../opt/anaconda3/envs/scratch_env/lib/python3.10/site-packages/ibis/backends/snowflake/__init__.py", line 246, in do_connect
    con = sc.connect(**connect_args)
UnboundLocalError: local variable 'sc' referenced before assignment
```

I investigated this issue further and noticed, a conditional `import` but unconditional access (in `ibis/backends/snowflake/__init__.py`),


```
if vparse(
	importlib.metadata.version("snowflake-connector-python")
) >= vparse("3.3.0"):
	warnings.filterwarnings(
		"ignore",
		message="You have an incompatible version of 'pyarrow' installed",
		category=UserWarning,
	)
	import snowflake.connector as sc

...
...
...


con = sc.connect(**connect_args)
```

(Notice in the `pipdeptree` results the test uses `snowflake-connector-python==3.0.3`, so the if condition is not exercised)

I can confirm this code issue is still in `main` branch - see [here](https://github.com/ibis-project/ibis/blob/69d6c7386e6c79859037629dd247e2e07ec5e67c/ibis/backends/snowflake/__init__.py#L214-L246).

Happy to offer help fixing or re-test when the fix is available.

**Comment by yazad3** [comment]
_(let me know if you want me to close this issue and open a separate issue for the ^^^ error)_

**Comment by cpcloud** [comment]
I'll create an issue for that one. Should be a relatively simple fix.

**Comment by yazad3** [comment]
Thank you @cpcloud
