### ISSUE TITLE
thrift.transport.TTransport.TTransportException: Hostname we connected to "grid.company.corp" doesn't match certificate provided commonName "server.company.corp"

### ISSUE THREAD

**Issue by ZuluagaSD** [ibis-project/ibis#882]
I'm trying to connect to Impala server that uses kerberos using the ibis.impala.connect like so:

``` python
import ibis

client = ibis.impala.connect(host='grid.company.corp',
                             port=21050,
                             auth_mechanism='GSSAPI',
                             use_ssl=True,
                             kerberos_service_name='impala',
                             ca_cert='D:\Users\USERNAME\Documents\cachain')
```

But I keep getting the following error:

```
D:\Archivos de programa\Miniconda2\envs\anaconda\lib\site-packages\ibis\sql\postgres\compiler.py:175: UserWarning: locale specific date formats (%c, %x, %X) are not yet implemented for Windows
  'for %s' % platform.system()
Traceback (most recent call last):
  File "D:\Users\USERNAME\Documents\Jupyter Notebooks\PPCs\impyla.py", line 9, in <module>
    ca_cert='D:\Users\USERNAME\Documents\cachain')
  File "D:\Archivos de programa\Miniconda2\envs\anaconda\lib\site-packages\ibis\impala\api.py", line 97, in connect
    con = ImpalaConnection(pool_size=pool_size, **params)
  File "D:\Archivos de programa\Miniconda2\envs\anaconda\lib\site-packages\ibis\impala\client.py", line 87, in __init__
    self.ping()
  File "D:\Archivos de programa\Miniconda2\envs\anaconda\lib\site-packages\ibis\impala\client.py", line 182, in ping
    self._new_cursor()
  File "D:\Archivos de programa\Miniconda2\envs\anaconda\lib\site-packages\ibis\impala\client.py", line 167, in _new_cursor
    con = impyla.connect(database=self.database, **params)
  File "D:\Archivos de programa\Miniconda2\envs\anaconda\lib\site-packages\impala\dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "D:\Archivos de programa\Miniconda2\envs\anaconda\lib\site-packages\impala\hiveserver2.py", line 658, in connect
    transport.open()
  File "build\bdist.win-amd64\egg\thrift_sasl\__init__.py", line 61, in open
  File "D:\Archivos de programa\Miniconda2\envs\anaconda\lib\site-packages\thrift\transport\TSSLSocket.py", line 120, in open
    self._validate_cert()
  File "D:\Archivos de programa\Miniconda2\envs\anaconda\lib\site-packages\thrift\transport\TSSLSocket.py", line 157, in _validate_cert
    'provided commonName "%s"' % (self.host, certhost))
thrift.transport.TTransport.TTransportException: Hostname we connected to "grid.company.corp" doesn't match certificate provided commonName "server.company.corp"
```

I have the Impala ODBC set up and it works fine.

**Comment by wesm** [comment]
Do you need to pass a particular CA certificate when connecting?

**Comment by ZuluagaSD** [comment]
Yes, I have a working connection using the impala ODBC connector. For the ODBC configuration I have to enable SSL and pass the certificate file that I mention above.

**Comment by pyite1** [comment]
I assume grid.company.corp is a load balancer? I've been able to get around this error by using a specific Impala daemon.

**Comment by ZuluagaSD** [comment]
Hey @pyite1 thanks for your reply.

Yes grid.company.corp is indeed a load balancer.

**Comment by cpcloud** [comment]
@ZuluagaSD Can you try with a more recent version of impyla?
