### ISSUE TITLE
bug: april fools day ibish import failing on mac osx m1 

### ISSUE THREAD

**Issue by andrew-morris** [ibis-project/ibis#9166]
### What happened?

```
$ pip install ibish
Defaulting to user installation because normal site-packages is not writeable
Collecting ibish
  Downloading ibish-1.0.2-py3-none-any.whl.metadata (1.5 kB)
Collecting ibis-framework<9.0.0,>=8.0.0 (from ibish)
  Downloading ibis_framework-8.0.0-py3-none-any.whl.metadata (17 kB)
Collecting pandas<3.0.0,>=2.2.1 (from ibish)
  Downloading pandas-2.2.2-cp39-cp39-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting pyarrow<16.0.0,>=15.0.2 (from ibish)
  Downloading pyarrow-15.0.2-cp39-cp39-macosx_11_0_arm64.whl.metadata (3.0 kB)
Collecting atpublic<5,>=2.3 (from ibis-framework<9.0.0,>=8.0.0->ibish)
  Downloading atpublic-4.1.0-py3-none-any.whl.metadata (1.8 kB)
Collecting bidict<1,>=0.22.1 (from ibis-framework<9.0.0,>=8.0.0->ibish)
  Downloading bidict-0.23.1-py3-none-any.whl.metadata (8.7 kB)
Collecting multipledispatch<2,>=0.6 (from ibis-framework<9.0.0,>=8.0.0->ibish)
  Downloading multipledispatch-1.0.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: numpy<2,>=1 in /Users/andrew/Library/Python/3.9/lib/python/site-packages (from ibis-framework<9.0.0,>=8.0.0->ibish) (1.26.1)
Collecting parsy<3,>=2 (from ibis-framework<9.0.0,>=8.0.0->ibish)
  Downloading parsy-2.1-py3-none-any.whl.metadata (3.3 kB)
Collecting pyarrow-hotfix<1,>=0.4 (from ibis-framework<9.0.0,>=8.0.0->ibish)
  Downloading pyarrow_hotfix-0.6-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: python-dateutil<3,>=2.8.2 in /Users/andrew/Library/Python/3.9/lib/python/site-packages (from ibis-framework<9.0.0,>=8.0.0->ibish) (2.8.2)
Requirement already satisfied: pytz>=2022.7 in /Users/andrew/Library/Python/3.9/lib/python/site-packages (from ibis-framework<9.0.0,>=8.0.0->ibish) (2023.3)
Requirement already satisfied: rich<14,>=12.4.4 in /Users/andrew/Library/Python/3.9/lib/python/site-packages (from ibis-framework<9.0.0,>=8.0.0->ibish) (13.4.2)
Collecting sqlglot<=20.11,>=18.12.0 (from ibis-framework<9.0.0,>=8.0.0->ibish)
  Downloading sqlglot-20.11.0-py3-none-any.whl.metadata (16 kB)
Collecting toolz<1,>=0.11 (from ibis-framework<9.0.0,>=8.0.0->ibish)
  Downloading toolz-0.12.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /Users/andrew/Library/Python/3.9/lib/python/site-packages (from ibis-framework<9.0.0,>=8.0.0->ibish) (4.7.1)
Collecting tzdata>=2022.7 (from pandas<3.0.0,>=2.2.1->ibish)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil<3,>=2.8.2->ibis-framework<9.0.0,>=8.0.0->ibish) (1.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/andrew/Library/Python/3.9/lib/python/site-packages (from rich<14,>=12.4.4->ibis-framework<9.0.0,>=8.0.0->ibish) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/andrew/Library/Python/3.9/lib/python/site-packages (from rich<14,>=12.4.4->ibis-framework<9.0.0,>=8.0.0->ibish) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in /Users/andrew/Library/Python/3.9/lib/python/site-packages (from markdown-it-py>=2.2.0->rich<14,>=12.4.4->ibis-framework<9.0.0,>=8.0.0->ibish) (0.1.2)
Downloading ibish-1.0.2-py3-none-any.whl (10 kB)
Downloading ibis_framework-8.0.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 530.1 kB/s eta 0:00:00
Downloading pandas-2.2.2-cp39-cp39-macosx_11_0_arm64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 767.1 kB/s eta 0:00:00
Downloading pyarrow-15.0.2-cp39-cp39-macosx_11_0_arm64.whl (24.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 1.3 MB/s eta 0:00:00
Downloading atpublic-4.1.0-py3-none-any.whl (5.0 kB)
Downloading bidict-0.23.1-py3-none-any.whl (32 kB)
Downloading multipledispatch-1.0.0-py3-none-any.whl (12 kB)
Downloading parsy-2.1-py3-none-any.whl (9.1 kB)
Downloading pyarrow_hotfix-0.6-py3-none-any.whl (7.9 kB)
Downloading sqlglot-20.11.0-py3-none-any.whl (356 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 356.5/356.5 kB 586.9 kB/s eta 0:00:00
Downloading toolz-0.12.1-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.1/56.1 kB 687.4 kB/s eta 0:00:00
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 643.0 kB/s eta 0:00:00
Installing collected packages: multipledispatch, tzdata, toolz, sqlglot, pyarrow-hotfix, pyarrow, parsy, bidict, atpublic, pandas, ibis-framework, ibish
Successfully installed atpublic-4.1.0 bidict-0.23.1 ibis-framework-8.0.0 ibish-1.0.2 multipledispatch-1.0.0 pandas-2.2.2 parsy-2.1 pyarrow-15.0.2 pyarrow-hotfix-0.6 sqlglot-20.11.0 toolz-0.12.1 tzdata-2024.1
```

```
$ uname -a
Darwin marathon 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64
```

### What version of ibis are you using?

```
[andrew @ marathon] ~ $ python3 --version
Python 3.9.6
[andrew @ marathon] ~ $ ipython3 --version
8.14.0
```

### What backend(s) are you using, if any?

unix-backend

### Relevant log output

```sh
see above


```
 $ python3
Python 3.9.6 (default, Feb  3 2024, 15:58:27)
[Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibis
>>> import ibish
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrew/Library/Python/3.9/lib/python/site-packages/ibish/__init__.py", line 15, in <module>
    from ibis.backends import BaseBackend, NoUrl
ImportError: cannot import name 'BaseBackend' from 'ibis.backends' (/Users/andrew/Library/Python/3.9/lib/python/site-packages/ibis/backends/__init__.py)
>>> 
```
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrew-morris** [comment]
per: https://ibis-project.org/posts/unix-backend/

**Comment by deepyaman** [comment]
In Ibis 9.0, `ibis.backends.base.BaseBackend` moved to `ibis.backends.BaseBackend`. Try `pip install 'ibis-framework>=9'`.

**Comment by deepyaman** [comment]
Ah, this is just user error! The post clearly states, "Like all production-ready libraries `ibish` depends on the latest commit of `ibis-framework` [as of the time of posting]." Therefore, we should:

```bash
pip install git+https://github.com/ibis-project/ibis.git@1d5124365c1abefbc9a6d938c52ffc6e1f3285d1
```

@andrew-morris It should work then. :)

**Comment by ncclementi** [comment]
@andrew-morris looks like you got things sorted out 🎉 , can we close this issue?

**Comment by cpcloud** [comment]
FWIW I also released a new version of ibish that should work without pinning any commits (requires ibis-framework 9.0.0)
